fv_timing_mod Module Reference
The module 'fv_timing' contains FV3 timers.
Data Types
type tms
Public Member Functions
subroutine timing_init
The subroutine 'timing_init' initializes timers.
subroutine timing_on (blk_name)
The subroutine 'timing_on' starts a timer.
subroutine timing_off (blk_name)
The subroutine 'timing_off' stops a timer.
subroutine timing_clear ()
The subroutine 'timing_clear' resets a timer.
subroutine timing_prt (gid)
The subroutine 'timing_prt' prints all timers.
subroutine upper (string, length)
Private Attributes
integer, private nblks
character(len=20), dimension(nblks),
*
private blkname
integer, private tblk
real, private etime
real(kind=8), private totim
real, dimension(2), private tarray
type(tms), dimension(nblks),
*
private accum
type(tms), dimension(nblks),
*
private last
real, dimension(nblks, 2), private us_tmp1
real, dimension(nblks, 2), private us_tmp2
logical, private module_initialized = .false.
Detailed Description
The module 'fv_timing' contains FV3 timers.
Definition at line 24 of file fv_timing.F90.
Member Function/Subroutine Documentation
subroutine fv_timing_mod::timing_clear ()
The subroutine 'timing_clear' resets a timer.
Definition at line 239 of file fv_timing.F90.
subroutine fv_timing_mod::timing_init ()
The subroutine 'timing_init' initializes timers.
Definition at line 78 of file fv_timing.F90.
Referenced by fv_control_mod::fv_init(), and timing_on().
subroutine fv_timing_mod::timing_off (character(len=*) blk_name)
The subroutine 'timing_off' stops a timer.
Definition at line 179 of file fv_timing.F90.
References upper().
Referenced by atmosphere_mod::adiabatic_init(), atmosphere_mod::atmosphere_dynamics(), atmosphere_mod::atmosphere_end(), atmosphere_mod::atmosphere_init(), atmosphere_mod::atmosphere_state_update(), fv_grid_utils_mod::c2l_ord4(), dyn_core_mod::del2_cubed(), fv_update_phys_mod::del2_phys(), fv_nwp_nudge_mod::del2_scalar(), dyn_core_mod::dyn_core(), fv_restart_mod::fill_nested_grid_data(), fv_restart_mod::fill_nested_grid_topo(), fv_dynamics_mod::fv_dynamics(), fv_control_mod::fv_end(), fv_update_phys_mod::fv_update_phys(), external_ic_mod::get_external_ic(), fv_mapz_mod::lagrangian_to_eulerian(), boundary_mod::nested_grid_bc_2d_mpp(), boundary_mod::nested_grid_bc_mpp(), boundary_mod::nested_grid_bc_mpp_send(), boundary_mod::nested_grid_bc_recv(), boundary_mod::nested_grid_bc_send(), fv_dynamics_mod::rayleigh_friction(), fv_dynamics_mod::rayleigh_super(), fv_nesting_mod::setup_nested_grid_bcs(), fv_surf_map_mod::surfdrv(), fv_tracer2d_mod::tracer_2d(), fv_tracer2d_mod::tracer_2d_1l(), fv_tracer2d_mod::tracer_2d_nested(), fv_update_phys_mod::update2d_dwinds_phys(), and boundary_mod::update_coarse_grid_mpp().
subroutine fv_timing_mod::timing_on (character(len=*) blk_name)
The subroutine 'timing_on' starts a timer.
Definition at line 115 of file fv_timing.F90.
References timing_init(), and upper().
Referenced by atmosphere_mod::adiabatic_init(), atmosphere_mod::atmosphere_dynamics(), atmosphere_mod::atmosphere_end(), atmosphere_mod::atmosphere_init(), atmosphere_mod::atmosphere_state_update(), fv_grid_utils_mod::c2l_ord4(), dyn_core_mod::del2_cubed(), fv_update_phys_mod::del2_phys(), fv_nwp_nudge_mod::del2_scalar(), dyn_core_mod::dyn_core(), fv_restart_mod::fill_nested_grid_data(), fv_restart_mod::fill_nested_grid_topo(), fv_dynamics_mod::fv_dynamics(), fv_control_mod::fv_init(), fv_update_phys_mod::fv_update_phys(), external_ic_mod::get_external_ic(), fv_mapz_mod::lagrangian_to_eulerian(), boundary_mod::nested_grid_bc_2d_mpp(), boundary_mod::nested_grid_bc_mpp(), boundary_mod::nested_grid_bc_mpp_send(), boundary_mod::nested_grid_bc_recv(), boundary_mod::nested_grid_bc_send(), fv_dynamics_mod::rayleigh_friction(), fv_dynamics_mod::rayleigh_super(), fv_nesting_mod::setup_nested_grid_bcs(), fv_surf_map_mod::surfdrv(), fv_tracer2d_mod::tracer_2d(), fv_tracer2d_mod::tracer_2d_1l(), fv_tracer2d_mod::tracer_2d_nested(), fv_update_phys_mod::update2d_dwinds_phys(), and boundary_mod::update_coarse_grid_mpp().
subroutine fv_timing_mod::timing_prt (integer gid)
The subroutine 'timing_prt' prints all timers.
Definition at line 248 of file fv_timing.F90.
Referenced by fv_control_mod::fv_end().
subroutine fv_timing_mod::upper (character (len=*), intent(inout) string, integer, intent(in) length)
Definition at line 294 of file fv_timing.F90.
Referenced by timing_off(), and timing_on().
Member Data Documentation
type (tms), dimension(nblks), private fv_timing_mod::accum [private]
Definition at line 68 of file fv_timing.F90.
character(len=20), dimension(nblks), private fv_timing_mod::blkname [private]
Definition at line 52 of file fv_timing.F90.
real, private fv_timing_mod::etime [private]
Definition at line 59 of file fv_timing.F90.
type (tms), dimension(nblks), private fv_timing_mod::last [private]
Definition at line 68 of file fv_timing.F90.
logical, private fv_timing_mod::module_initialized = .false. [private]
Definition at line 73 of file fv_timing.F90.
integer, private fv_timing_mod::nblks [private]
Definition at line 49 of file fv_timing.F90.
real, dimension(2), private fv_timing_mod::tarray [private]
Definition at line 61 of file fv_timing.F90.
integer, private fv_timing_mod::tblk [private]
Definition at line 54 of file fv_timing.F90.
real(kind=8), private fv_timing_mod::totim [private]
Definition at line 60 of file fv_timing.F90.
real, dimension(nblks,2), private fv_timing_mod::us_tmp1 [private]
Definition at line 70 of file fv_timing.F90.
real, dimension(nblks,2), private fv_timing_mod::us_tmp2 [private]
Definition at line 71 of file fv_timing.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_timing.F90