fv_grid_tools_mod Module Reference
Public Member Functions
subroutine, public init_grid (Atm, grid_name, grid_file, npx, npy, npz, ndims, nregions, ng)
The subroutine 'init_grid' reads the grid from the input file and sets up grid descriptors.
subroutine, public spherical_to_cartesian (lon, lat, r, x, y, z)
Public Attributes
real(kind=r_grid), parameter,
*
public todeg = 180.0d0/pi
convert to degrees
real(kind=r_grid), parameter,
*
public missing = 1.d25
Private Member Functions
subroutine read_grid (Atm, grid_file, ndims, nregions, ng)
The subroutine 'read_grid' reads the grid from the mosaic grid file.
subroutine get_symmetry (data_in, data_out, ishift, jshift, npes_x, npes_y, domain, tile, npx_g, bd)
subroutine cartesian_to_spherical (x, y, z, lon, lat, r)
subroutine rot_3d (axis, x1in, y1in, z1in, angle, x2out, y2out, z2out, degrees, convert)
The subroutine 'rot_3d' rotates points on a sphere in xyz coordinates.
real(kind=R_GRID) function get_area_tri (ndims, p_1, p_2, p_3)
brief The function 'get_area_tri' gets the surface area of a cell defined as a triangle on the sphere.
subroutine grid_area (nx, ny, ndims, nregions, nested, gridstruct, domain, bd, regional)
The subroutine 'grid_area' gets the surface area on a grid in lat/lon or xyz coordinates.
real(kind=R_GRID) function get_angle (ndims, p1, p2, p3, rad)
The function 'get_angle' gets the angle between 3 points on a sphere in lat/lon or xyz coordinates.
subroutine mirror_grid (grid_global, ng, npx, npy, ndims, nregions)
The subroutine 'mirror_grid' mirrors the grid across the 0-longitude line.
Private Attributes
real(kind=r_grid), parameter radius = cnst_radius
real(kind=r_grid), parameter torad = pi/180.0d0
convert to radians
real(kind=r_grid) csfac
logical, parameter debug_message_size = .false.
logical write_grid_char_file = .false.
Detailed Description
Definition at line 21 of file fv_grid_tools.F90.
Member Function/Subroutine Documentation
subroutine fv_grid_tools_mod::cartesian_to_spherical (real(kind=r_grid), intent(in) x, real(kind=r_grid), intent(in) y, real(kind=r_grid), intent(in) z, real(kind=r_grid), intent(out) lon, real(kind=r_grid), intent(out) lat, real(kind=r_grid), intent(out) r) [private]
Definition at line 1922 of file fv_grid_tools.F90.
Referenced by rot_3d().
real(kind=R_GRID) function fv_grid_tools_mod::get_angle (integer, intent(in) ndims, real(kind=r_grid), dimension(ndims), intent(in) p1, real(kind=r_grid), dimension(ndims), intent(in) p2, real(kind=r_grid), dimension(ndims), intent(in) p3, integer, intent(in), optional rad) [private]
The function 'get_angle' gets the angle between 3 points on a sphere in lat/lon or xyz coordinates.
Determined by the 'ndims' argument: 2=lat/lon, 3=xyz The angle is returned in degrees.
Parameters
in ndims 2=lat/lon, 3=xyz
Definition at line 2261 of file fv_grid_tools.F90.
References fv_grid_utils_mod::spherical_angle(), and spherical_to_cartesian().
Referenced by get_area_tri(), and init_grid().
real(kind=R_GRID) function fv_grid_tools_mod::get_area_tri (integer, intent(in) ndims, real(kind=r_grid), dimension(ndims), intent(in) p_1, real(kind=r_grid), dimension(ndims), intent(in) p_2, real(kind=r_grid), dimension(ndims), intent(in) p_3) [private]
brief The function 'get_area_tri' gets the surface area of a cell defined as a triangle on the sphere.
The area is computed as the spherical excess [area units are based on the units of radius]
Parameters
in ndims 2=lat/lon, 3=xyz
Definition at line 2018 of file fv_grid_tools.F90.
References get_angle(), and fv_grid_utils_mod::spherical_angle().
Referenced by grid_area().
subroutine fv_grid_tools_mod::get_symmetry (real(kind=r_grid), dimension(bd%is:bd%ie+ishift, bd%js:bd%je+jshift), intent(in) data_in, real(kind=r_grid), dimension(bd%is:bd%ie+jshift, bd%js:bd%je+ishift), intent(out) data_out, integer, intent(in) ishift, integer, intent(in) jshift, integer, intent(in) npes_x, integer, intent(in) npes_y, type(domain2d) domain, integer tile, integer npx_g, type(fv_grid_bounds_type), intent(in) bd) [private]
Definition at line 306 of file fv_grid_tools.F90.
References fv_regional_mod::check().
Referenced by init_grid().
subroutine fv_grid_tools_mod::grid_area (integer, intent(in) nx, integer, intent(in) ny, integer, intent(in) ndims, integer, intent(in) nregions, logical, intent(in) nested, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) domain, type(fv_grid_bounds_type), intent(in) bd, logical, intent(in) regional) [private]
The subroutine 'grid_area' gets the surface area on a grid in lat/lon or xyz coordinates.
Determined by 'ndims' argument: 2=lat/lon, 3=xyz) The area is returned in m^2 on a unit sphere.
Definition at line 2045 of file fv_grid_tools.F90.
References fv_grid_utils_mod::get_area(), and get_area_tri().
Referenced by init_grid().
subroutine, public fv_grid_tools_mod::init_grid (type(fv_atmos_type), intent(inout), target Atm, character(len=80), intent(in) grid_name, character(len=120), intent(in) grid_file, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ndims, integer, intent(in) nregions, integer, intent(in) ng)
The subroutine 'init_grid' reads the grid from the input file and sets up grid descriptors.
Definition at line 529 of file fv_grid_tools.F90.
References fv_grid_utils_mod::cell_center2(), fv_grid_utils_mod::direct_transform(), get_angle(), fv_grid_utils_mod::get_area(), get_symmetry(), fv_grid_utils_mod::gnomonic_grids(), fv_grid_utils_mod::great_circle_dist(), grid_area(), fv_grid_utils_mod::mid_pt_sphere(), mirror_grid(), read_grid(), setup_aligned_nest(), setup_cartesian(), sorted_index_mod::sorted_inta(), and sorted_index_mod::sorted_intb().
Referenced by fv_control_mod::fv_init().
subroutine fv_grid_tools_mod::mirror_grid (real(kind=r_grid), dimension(1-ng:npx +ng,1-ng:npy +ng,ndims,1:nregions), intent(inout) grid_global, integer, intent(in) ng, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ndims, integer, intent(in) nregions) [private]
The subroutine 'mirror_grid' mirrors the grid across the 0-longitude line.
Definition at line 2289 of file fv_grid_tools.F90.
References rot_3d().
Referenced by init_grid().
subroutine fv_grid_tools_mod::read_grid (type(fv_atmos_type), intent(inout), target Atm, character(len=*), intent(in) grid_file, integer, intent(in) ndims, integer, intent(in) nregions, integer, intent(in) ng) [private]
The subroutine 'read_grid' reads the grid from the mosaic grid file.
Definition at line 174 of file fv_grid_tools.F90.
Referenced by init_grid().
subroutine fv_grid_tools_mod::rot_3d (integer, intent(in) axis, real(kind=r_grid), intent(in) x1in, real(kind=r_grid), intent(in) y1in, real(kind=r_grid), intent(in) z1in, real(kind=r_grid), intent(inout) angle, real(kind=r_grid), intent(out) x2out, real(kind=r_grid), intent(out) y2out, real(kind=r_grid), intent(out) z2out, integer, intent(in), optional degrees, integer, intent(in), optional convert) [private]
The subroutine 'rot_3d' rotates points on a sphere in xyz coordinates.
Converts angle from degrees to radians if necessary
Parameters
in axis axis of rotation 1=x, 2=y, 3=z
in,out angle angle to rotate in radians
in degrees if present convert angle from degrees to radians
in convert if present convert input point from spherical to cartesian, rotate, and convert back
Definition at line 1955 of file fv_grid_tools.F90.
References cartesian_to_spherical(), and spherical_to_cartesian().
Referenced by mirror_grid().
subroutine, public fv_grid_tools_mod::spherical_to_cartesian (real(kind=r_grid), intent(in) lon, real(kind=r_grid), intent(in) lat, real(kind=r_grid), intent(in) r, real(kind=r_grid), intent(out) x, real(kind=r_grid), intent(out) y, real(kind=r_grid), intent(out) z)
Definition at line 1940 of file fv_grid_tools.F90.
Referenced by get_angle(), test_cases_mod::get_unit_vector(), and rot_3d().
Member Data Documentation
real(kind=r_grid) fv_grid_tools_mod::csfac [private]
Definition at line 163 of file fv_grid_tools.F90.
logical, parameter fv_grid_tools_mod::debug_message_size = .false. [private]
Definition at line 165 of file fv_grid_tools.F90.
real(kind=r_grid), parameter, public fv_grid_tools_mod::missing = 1.d25
Definition at line 161 of file fv_grid_tools.F90.
real(kind=r_grid), parameter fv_grid_tools_mod::radius = cnst_radius [private]
Definition at line 157 of file fv_grid_tools.F90.
real(kind=r_grid), parameter, public fv_grid_tools_mod::todeg = 180.0d0/pi
convert to degrees
Definition at line 159 of file fv_grid_tools.F90.
real(kind=r_grid), parameter fv_grid_tools_mod::torad = pi/180.0d0 [private]
convert to radians
Definition at line 160 of file fv_grid_tools.F90.
logical fv_grid_tools_mod::write_grid_char_file = .false. [private]
Definition at line 166 of file fv_grid_tools.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_grid_tools.F90