fv_cmp_mod Module Reference
The module 'fv_cmp' implements the fast procesesses in the GFDL microphysics >
Public Member Functions
subroutine, public fv_sat_adj (mdt, zvir, is, ie, js, je, ng, hydrostatic, consv_te, te0,
The subroutine 'fv_sat_adj' performs the fast processes in the GFDL microphysics.
subroutine, public qs_init (kmp)
The subroutine 'qs_init' initializes lookup tables for the saturation mixing ratio.
Private Member Functions
real function wqs1 (ta, den)
the function 'wqs1' computes the saturated specific humidity for table ii
real function iqs1 (ta, den)
the function 'wqs1' computes the saturated specific humidity for table iii
real function wqs2 (ta, den, dqdt)
The function 'wqs2'computes the gradient of saturated specific humidity for table ii.
subroutine wqs2_vect (is, ie, ta, den, wqsat, dqdt)
The function wqs2_vect computes the gradient of saturated specific humidity for table ii. It is the same as `wqs2`, but written as vector function.
real function iqs2 (ta, den, dqdt)
The function 'iqs2' computes the gradient of saturated specific humidity for table iii.
subroutine qs_table (n)
subroutine qs_tablew (n)
subroutine qs_table2 (n)
Private Attributes
real, parameter cp_vap = 4.0 * rvgas
1846.0, heat capacity of water vapor at constant pressure
real, parameter cv_air = cp_air - rdgas
717.55, heat capacity of dry air at constant volume
real, parameter cv_vap = 3.0 * rvgas
1384.5, heat capacity of water vapor at constant volume
real, parameter c_ice = 1972.0
gfdl: heat capacity of ice at - 15 deg c
real, parameter c_liq = 4185.5
gfdl: heat capacity of liquid at 15 deg c
real, parameter dc_vap = cp_vap - c_liq
real, parameter dc_ice = c_liq - c_ice
2213.5, isobaric heating / colling
real, parameter tice = 273.16
freezing temperature
real, parameter t_wfr = tice - 40.
homogeneous freezing temperature
real, parameter lv0 = hlv - dc_vap * tice
3.13905782e6, evaporation latent heat coefficient at 0 deg k
real, parameter li00 = hlf - dc_ice * tice
real(kind=r_grid), parameter e00 = 611.21
ifs: saturation vapor pressure at 0 deg c
real(kind=r_grid), parameter d2ice = dc_vap + dc_ice
real(kind=r_grid), parameter li2 = lv0 + li00
2.86799816e6, sublimation latent heat coefficient at 0 deg k
real, parameter lat2 = (hlv + hlf) ** 2
used in bigg mechanism
real d0_vap
the same as dc_vap, except that cp_vap can be cp_vap or cv_vap
real lv00
the same as lv0, except that cp_vap can be cp_vap or cv_vap
real, dimension(:), allocatable table
real, dimension(:), allocatable table2
real, dimension(:), allocatable tablew
real, dimension(:), allocatable des2
real, dimension(:), allocatable desw
logical mp_initialized = .false.
Detailed Description
The module 'fv_cmp' implements the fast procesesses in the GFDL microphysics >
Author
Shian-Jiann Lin, Linjiong Zhou
Definition at line 29 of file fv_cmp.F90.
Member Function/Subroutine Documentation
subroutine, public fv_cmp_mod::fv_sat_adj (real, intent(in) mdt, real, intent(in) zvir, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ng, logical, intent(in) hydrostatic, logical, intent(in) consv_te, real, dimension (is - ng:ie + ng, js - ng:je + ng), intent(out) te0)
The subroutine 'fv_sat_adj' performs the fast processes in the GFDL microphysics.
This is designed for single-moment 6-class cloud microphysics schemes. It handles the heat release due to in situ phase changes.
Definition at line 122 of file fv_cmp.F90.
References iqs1(), iqs2(), multi_gases_mod::vicpqd_qpz(), multi_gases_mod::vicvqd_qpz(), multi_gases_mod::virq_qpz(), wqs1(), and wqs2_vect().
Referenced by fv_mapz_mod::lagrangian_to_eulerian().
real function fv_cmp_mod::iqs1 (real, intent(in) ta, real, intent(in) den) [private]
the function 'wqs1' computes the saturated specific humidity for table iii
Definition at line 902 of file fv_cmp.F90.
Referenced by fv_sat_adj().
real function fv_cmp_mod::iqs2 (real, intent(in) ta, real, intent(in) den, real, intent(out) dqdt) [private]
The function 'iqs2' computes the gradient of saturated specific humidity for table iii.
Definition at line 996 of file fv_cmp.F90.
Referenced by fv_sat_adj().
subroutine, public fv_cmp_mod::qs_init (integer, intent(in) kmp)
The subroutine 'qs_init' initializes lookup tables for the saturation mixing ratio.
Definition at line 1028 of file fv_cmp.F90.
References qs_table(), qs_table2(), and qs_tablew().
Referenced by fv_mapz_mod::lagrangian_to_eulerian().
subroutine fv_cmp_mod::qs_table (integer, intent(in) n) [private]
Definition at line 1070 of file fv_cmp.F90.
Referenced by qs_init(), and fv_sg_mod::qsmith_init().
subroutine fv_cmp_mod::qs_table2 (integer, intent(in) n) [private]
Definition at line 1164 of file fv_cmp.F90.
Referenced by qs_init().
subroutine fv_cmp_mod::qs_tablew (integer, intent(in) n) [private]
Definition at line 1132 of file fv_cmp.F90.
Referenced by qs_init().
real function fv_cmp_mod::wqs1 (real, intent(in) ta, real, intent(in) den) [private]
the function 'wqs1' computes the saturated specific humidity for table ii
Definition at line 876 of file fv_cmp.F90.
Referenced by fv_sat_adj().
real function fv_cmp_mod::wqs2 (real, intent(in) ta, real, intent(in) den, real, intent(out) dqdt) [private]
The function 'wqs2'computes the gradient of saturated specific humidity for table ii.
Definition at line 928 of file fv_cmp.F90.
Referenced by fv_sg_mod::fv_subgrid_z().
subroutine fv_cmp_mod::wqs2_vect (integer, intent(in) is, integer, intent(in) ie, real, dimension (is:ie), intent(in) ta, real, dimension (is:ie), intent(in) den, real, dimension (is:ie), intent(out) wqsat, real, dimension (is:ie), intent(out) dqdt) [private]
The function wqs2_vect computes the gradient of saturated specific humidity for table ii. It is the same as `wqs2`, but written as vector function.
Definition at line 960 of file fv_cmp.F90.
Referenced by fv_sat_adj().
Member Data Documentation
real, parameter fv_cmp_mod::c_ice = 1972.0 [private]
gfdl: heat capacity of ice at - 15 deg c
Definition at line 90 of file fv_cmp.F90.
real, parameter fv_cmp_mod::c_liq = 4185.5 [private]
gfdl: heat capacity of liquid at 15 deg c
Definition at line 91 of file fv_cmp.F90.
real, parameter fv_cmp_mod::cp_vap = 4.0 * rvgas [private]
1846.0, heat capacity of water vapor at constant pressure
Definition at line 75 of file fv_cmp.F90.
real, parameter fv_cmp_mod::cv_air = cp_air - rdgas [private]
717.55, heat capacity of dry air at constant volume
Definition at line 76 of file fv_cmp.F90.
real, parameter fv_cmp_mod::cv_vap = 3.0 * rvgas [private]
1384.5, heat capacity of water vapor at constant volume
Definition at line 77 of file fv_cmp.F90.
real fv_cmp_mod::d0_vap [private]
the same as dc_vap, except that cp_vap can be cp_vap or cv_vap
Definition at line 110 of file fv_cmp.F90.
real (kind = r_grid), parameter fv_cmp_mod::d2ice = dc_vap + dc_ice [private]
126, isobaric heating / cooling
Definition at line 105 of file fv_cmp.F90.
real, parameter fv_cmp_mod::dc_ice = c_liq - c_ice [private]
2213.5, isobaric heating / colling
Definition at line 94 of file fv_cmp.F90.
real, parameter fv_cmp_mod::dc_vap = cp_vap - c_liq [private]
2339.5, isobaric heating / cooling
Definition at line 93 of file fv_cmp.F90.
real, dimension (:), allocatable fv_cmp_mod::des2 [private]
Definition at line 113 of file fv_cmp.F90.
real, dimension (:), allocatable fv_cmp_mod::desw [private]
Definition at line 113 of file fv_cmp.F90.
real (kind = r_grid), parameter fv_cmp_mod::e00 = 611.21 [private]
ifs: saturation vapor pressure at 0 deg c
Definition at line 103 of file fv_cmp.F90.
real, parameter fv_cmp_mod::lat2 = (hlv + hlf) ** 2 [private]
used in bigg mechanism
Definition at line 108 of file fv_cmp.F90.
real, parameter fv_cmp_mod::li00 = hlf - dc_ice * tice [private]
2.7105966e5, fusion latent heat coefficient at 0 deg k
Definition at line 100 of file fv_cmp.F90.
real (kind = r_grid), parameter fv_cmp_mod::li2 = lv0 + li00 [private]
2.86799816e6, sublimation latent heat coefficient at 0 deg k
Definition at line 106 of file fv_cmp.F90.
real, parameter fv_cmp_mod::lv0 = hlv - dc_vap * tice [private]
3.13905782e6, evaporation latent heat coefficient at 0 deg k
Definition at line 99 of file fv_cmp.F90.
real fv_cmp_mod::lv00 [private]
the same as lv0, except that cp_vap can be cp_vap or cv_vap
Definition at line 111 of file fv_cmp.F90.
logical fv_cmp_mod::mp_initialized = .false. [private]
Definition at line 115 of file fv_cmp.F90.
real, parameter fv_cmp_mod::t_wfr = tice - 40. [private]
homogeneous freezing temperature
Definition at line 97 of file fv_cmp.F90.
real, dimension (:), allocatable fv_cmp_mod::table [private]
Definition at line 113 of file fv_cmp.F90.
real, dimension (:), allocatable fv_cmp_mod::table2 [private]
Definition at line 113 of file fv_cmp.F90.
real, dimension (:), allocatable fv_cmp_mod::tablew [private]
Definition at line 113 of file fv_cmp.F90.
real, parameter fv_cmp_mod::tice = 273.16 [private]
freezing temperature
Definition at line 96 of file fv_cmp.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_cmp.F90