a2b_edge_mod Module Reference
The module 'a2b_edge' performs FV-consistent interpolation of pressure to corners.
Public Member Functions
subroutine, public a2b_ord4 (qin, qout, gridstruct, npx, npy, is, ie, js, je, ng, replace)
subroutine, public a2b_ord2 (qin, qout, gridstruct, npx, npy, is, ie, js, je, ng, replace)
Public Attributes
real, parameter r3 = 1./3.
real, parameter a1 = 0.5625
9/16
real, parameter a2 = -0.0625
-1/16
real, parameter b1 = 7./12.
0.58333333
real, parameter b2 = -1./12.
Private Member Functions
real function extrap_corner (p0, p1, p2, q1, q2)
Detailed Description
The module 'a2b_edge' performs FV-consistent interpolation of pressure to corners.
Definition at line 24 of file a2b_edge.F90.
Member Function/Subroutine Documentation
subroutine, public a2b_edge_mod::a2b_ord2 (real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(inout) qin, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(out) qout, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ng, logical, intent(in), optional replace)
Parameters
in,out qin A-grid field
out qout Output B-grid field
Definition at line 697 of file a2b_edge.F90.
Referenced by dyn_core_mod::adv_pe(), dyn_core_mod::dyn_core(), dyn_core_mod::grad1_p_update(), and dyn_core_mod::one_grad_p().
subroutine, public a2b_edge_mod::a2b_ord4 (real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(inout) qin, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(inout) qout, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ng, logical, intent(in), optional replace)
Parameters
in,out qin A-grid field
in,out qout Output B-grid field
Definition at line 69 of file a2b_edge.F90.
References extrap_corner().
Referenced by sw_core_mod::d_sw(), dyn_core_mod::grad1_p_update(), fv_diagnostics_mod::init_mq(), dyn_core_mod::nh_p_grad(), dyn_core_mod::one_grad_p(), fv_grid_utils_mod::project_sphere_v(), sw_core_mod::smag_corner(), and dyn_core_mod::split_p_grad().
real function a2b_edge_mod::extrap_corner (real, dimension(2), intent(in) p0, real, dimension(2), intent(in) p1, real, dimension(2), intent(in) p2, real, intent(in) q1, real, intent(in) q2) [private]
Definition at line 820 of file a2b_edge.F90.
References fv_grid_utils_mod::great_circle_dist().
Referenced by a2b_ord4().
Member Data Documentation
real, parameter a2b_edge_mod::a1 = 0.5625
9/16
Definition at line 55 of file a2b_edge.F90.
real, parameter a2b_edge_mod::a2 = -0.0625
-1/16
Definition at line 56 of file a2b_edge.F90.
real, parameter a2b_edge_mod::b1 = 7./12.
0.58333333
Definition at line 60 of file a2b_edge.F90.
real, parameter a2b_edge_mod::b2 = -1./12.
Definition at line 61 of file a2b_edge.F90.
real, parameter a2b_edge_mod::r3 = 1./3.
Definition at line 51 of file a2b_edge.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/a2b_edge.F90