nh_core_mod Module Reference
The module 'nh_core' peforms non-hydrostatic computations.
Public Member Functions
subroutine, public riem_solver3 (ms, dt,is,ie,js, je, km, ng,isd, ied, jsd, jed, akap, cappa, cp,
Private Attributes
real, parameter r3 = 1./3.
Detailed Description
The module 'nh_core' peforms non-hydrostatic computations.
Author
S. J. Lin, NOAA/GFDL
Definition at line 26 of file nh_core.F90.
Member Function/Subroutine Documentation
subroutine, public nh_core_mod::riem_solver3 (integer, intent(in) ms, real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, integer, intent(in) ng, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, intent(in) akap, real, dimension(isd:,jsd:,1:), intent(in) cappa, real, intent(in) cp)
Parameters
in dt the BIG horizontal Lagrangian time step
Definition at line 65 of file nh_core.F90.
References nh_utils_mod::rim_2d(), nh_utils_mod::sim1_solver(), nh_utils_mod::sim3_solver(), nh_utils_mod::sim3p0_solver(), and nh_utils_mod::sim_solver().
Referenced by dyn_core_mod::dyn_core().
Member Data Documentation
real, parameter nh_core_mod::r3 = 1./3. [private]
Definition at line 60 of file nh_core.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/nh_core.F90