sim_nc_mod Module Reference
The module 'sim_nc' is a netcdf file reader.
Public Member Functions
subroutine, public open_ncfile (iflnm, ncid)
subroutine, public close_ncfile (ncid)
subroutine, public get_ncdim1 (ncid, var1_name, im)
subroutine, public get_var1_double (ncid, var1_name, im, var1, var_exist)
The 'get_var' subroutines read in variables from netcdf files.
subroutine, public get_var1_real (ncid, var1_name, im, var1, var_exist)
subroutine, public get_var2_real (ncid, var_name, im, jm, var2)
subroutine, public get_var2_r4 (ncid, var2_name, is, ie, js, je, var2, time_slice)
subroutine, public get_var2_double (ncid, var2_name, im, jm, var2)
subroutine, public get_var3_double (ncid, var3_name, im, jm, km, var3)
subroutine, public get_var3_real (ncid, var3_name, im, jm, km, var3)
subroutine, public check_var_exists (ncid, var_name, status)
subroutine, public get_var3_r4 (ncid, var3_name, is, ie, js, je, ks, ke, var3, time_slice)
logical function, public check_var (ncid, var3_name)
subroutine, public get_var_att_double (ncid, var_name, att_name, value)
subroutine, public handle_err (idstr, status)
Private Member Functions
subroutine get_var4_real (ncid, var4_name, im, jm, km, nt, var4)
subroutine get_var4_double (ncid, var4_name, im, jm, km, nt, var4)
subroutine get_real3 (ncid, var4_name, im, jm, nt, var4)
subroutine get_var_att_str (ncid, var_name, att_name, att)
subroutine calendar (year, month, day, hour)
The subroutine 'calendar' computes the current GMT.
Detailed Description
The module 'sim_nc' is a netcdf file reader.
The code is necessary to circumvent issues with the FMS 'read_data' utility, which opens too many files and uses excessive memory.
Author
Shian-Jiann Lin
Definition at line 28 of file sim_nc_mod.F90.
Member Function/Subroutine Documentation
subroutine sim_nc_mod::calendar (integer, intent(inout) year, integer, intent(inout) month, integer, intent(inout) day, integer, intent(inout) hour) [private]
The subroutine 'calendar' computes the current GMT.
Definition at line 428 of file sim_nc_mod.F90.
logical function, public sim_nc_mod::check_var (integer, intent(in) ncid, character(len=*), intent(in) var3_name)
Definition at line 371 of file sim_nc_mod.F90.
subroutine, public sim_nc_mod::check_var_exists (integer, intent(in) ncid, character(len=*), intent(in) var_name, integer, intent(inout) status)
Definition at line 237 of file sim_nc_mod.F90.
Referenced by apply_inc_on_3d_scalar(), and fv_iau_mod::interp_inc().
subroutine, public sim_nc_mod::close_ncfile (integer, intent(in) ncid)
Definition at line 66 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
Referenced by fv_nwp_nudge_mod::fv_nwp_nudge_init(), fv_nwp_nudge_mod::get_ncep_analysis(), external_ic_mod::get_ncep_ic(), fv_iau_mod::iau_initialize(), and fv_iau_mod::read_iau_forcing().
subroutine, public sim_nc_mod::get_ncdim1 (integer, intent(in) ncid, character(len=*), intent(in) var1_name, integer, intent(out) im)
Definition at line 77 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
Referenced by fv_nwp_nudge_mod::fv_nwp_nudge_init(), external_ic_mod::get_ecmwf_ic(), external_ic_mod::get_ncep_ic(), fv_iau_mod::iau_initialize(), and fv_treat_da_inc_mod::read_da_inc().
subroutine sim_nc_mod::get_real3 (integer, intent(in) ncid, character(len=*), intent(in) var4_name, integer, intent(in) im, integer, intent(in) jm, integer, intent(in) nt, real(kind=4), dimension(im,jm), intent(out) var4) [private]
Definition at line 344 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine, public sim_nc_mod::get_var1_double (integer, intent(in) ncid, character(len=*), intent(in) var1_name, integer, intent(in) im, real(kind=8), dimension(im), intent(out) var1, logical, intent(out), optional var_exist)
The 'get_var' subroutines read in variables from netcdf files.
Definition at line 92 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine, public sim_nc_mod::get_var1_real (integer, intent(in) ncid, character(len=*), intent(in) var1_name, integer, intent(in) im, real(kind=4), dimension(im), intent(out) var1, logical, intent(out), optional var_exist)
Definition at line 115 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine, public sim_nc_mod::get_var2_double (integer, intent(in) ncid, character(len=*), intent(in) var2_name, integer, intent(in) im, integer, intent(in) jm, real(kind=8), dimension(im,jm), intent(out) var2)
Definition at line 180 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine, public sim_nc_mod::get_var2_r4 (integer, intent(in) ncid, character(len=*), intent(in) var2_name, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, real(kind=4), dimension(is:ie,js:je), intent(out) var2, integer, intent(in), optional time_slice)
Definition at line 152 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
Referenced by external_ic_mod::get_ecmwf_ic().
subroutine, public sim_nc_mod::get_var2_real (integer, intent(in) ncid, character(len=*), intent(in) var_name, integer, intent(in) im, integer, intent(in) jm, real(kind=4), dimension(im), intent(out) var2)
Definition at line 136 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
Referenced by external_ic_mod::get_ncep_ic().
subroutine, public sim_nc_mod::get_var3_double (integer, intent(in) ncid, character(len=*), intent(in) var3_name, integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, real(kind=8), dimension(im,jm,km), intent(out) var3)
Definition at line 198 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine, public sim_nc_mod::get_var3_r4 (integer, intent(in) ncid, character(len=*), intent(in) var3_name, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ks, integer, intent(in) ke, real(kind=4), dimension(is:ie,js:je,ks:ke), intent(out) var3, integer, intent(in), optional time_slice)
Definition at line 245 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
Referenced by apply_inc_on_3d_scalar(), external_ic_mod::get_ecmwf_ic(), fv_nwp_nudge_mod::get_ncep_analysis(), external_ic_mod::get_ncep_ic(), fv_iau_mod::interp_inc(), and fv_treat_da_inc_mod::read_da_inc().
subroutine, public sim_nc_mod::get_var3_real (integer, intent(in) ncid, character(len=*), intent(in) var3_name, integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, real(kind=4), dimension(im,jm,km), intent(out) var3)
Definition at line 217 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine sim_nc_mod::get_var4_double (integer, intent(in) ncid, character(len=*), intent(in) var4_name, integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, integer, intent(in) nt, real(kind=8), dimension(im,jm,km,1), intent(out) var4) [private]
Definition at line 317 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine sim_nc_mod::get_var4_real (integer, intent(in) ncid, character*(*), intent(in) var4_name, integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, integer, intent(in) nt, real*4, dimension(im,jm), intent(out) var4) [private]
Definition at line 275 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine, public sim_nc_mod::get_var_att_double (integer, intent(in) ncid, character*(*), intent(in) var_name, character*(*), intent(in) att_name, real(kind=8), intent(out) value)
Definition at line 398 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
Referenced by external_ic_mod::get_ecmwf_ic().
subroutine sim_nc_mod::get_var_att_str (integer, intent(in) ncid, character*(*), intent(in) var_name, character*(*), intent(in) att_name, character*(*), intent(out) att) [private]
Definition at line 382 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
subroutine, public sim_nc_mod::handle_err (character(len=*) idstr, integer status)
Definition at line 415 of file sim_nc_mod.F90.
subroutine, public sim_nc_mod::open_ncfile (character(len=*), intent(in) iflnm, integer, intent(out) ncid)
Definition at line 54 of file sim_nc_mod.F90.
References fv_surf_map_mod::handle_err().
Referenced by fv_nwp_nudge_mod::fv_nwp_nudge_init(), external_ic_mod::get_ecmwf_ic(), fv_nwp_nudge_mod::get_ncep_analysis(), external_ic_mod::get_ncep_ic(), fv_iau_mod::iau_initialize(), fv_treat_da_inc_mod::read_da_inc(), and fv_iau_mod::read_iau_forcing().
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/sim_nc_mod.F90