fv_fill_mod Module Reference
Public Member Functions
subroutine, public fillz (im, km, nq, q, dp)
The subroutine 'fillz' is for mass-conservative filling of nonphysical negative values in the tracers.
subroutine, public fill_gfs (im, km, pe2, q, q_min)
The subroutine 'fill_gfs' is for mass-conservative filling of nonphysical negative values in the tracers.
subroutine, public fill2d (is, ie, js, je, ng, km, q, delp, area, domain, nested, regional, npx, npy)
The subroutine 'fill2D' fills in nonphysical negative values in a single scalar field using a two-dimensional diffusive approach which conserves mass.
Detailed Description
Definition at line 21 of file fv_fill.F90.
Member Function/Subroutine Documentation
subroutine, public fv_fill_mod::fill2d (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ng, integer, intent(in) km, real, dimension(is-ng:ie+ng, js-ng:je+ng, km), intent(inout) q, real, dimension(is-ng:ie+ng, js-ng:je+ng, km), intent(in) delp, real, dimension(is-ng:ie+ng, js-ng:je+ng), intent(in) area, type(domain2d), intent(inout) domain, logical, intent(in) nested, logical, intent(in) regional, integer, intent(in) npx, integer, intent(in) npy)
The subroutine 'fill2D' fills in nonphysical negative values in a single scalar field using a two-dimensional diffusive approach which conserves mass.
Definition at line 206 of file fv_fill.F90.
Referenced by fv_dynamics_mod::fv_dynamics().
subroutine, public fv_fill_mod::fill_gfs (integer, intent(in) im, integer, intent(in) km, real(kind=kind_phys), dimension(im,km+1), intent(in) pe2, real(kind=kind_phys), dimension(im,km), intent(inout) q, real(kind=kind_phys), intent(in) q_min)
The subroutine 'fill_gfs' is for mass-conservative filling of nonphysical negative values in the tracers.
This routine is the same as 'fillz', but only fills one scalar field using specified q_min instead of 0 with the k-index flipped as in the GFS physics. It accepts edge pressure instead of delp.
Parameters
in pe2 pressure interface
Definition at line 162 of file fv_fill.F90.
Referenced by atmosphere_mod::atmosphere_state_update().
subroutine, public fv_fill_mod::fillz (integer, intent(in) im, integer, intent(in) km, integer, intent(in) nq, real, dimension(im,km,nq), intent(inout) q, real, dimension(im,km), intent(in) dp)
The subroutine 'fillz' is for mass-conservative filling of nonphysical negative values in the tracers.
This routine takes mass from adjacent cells in the same column to fill negatives, if possible.
Parameters
in im No. of longitudes
in km No. of levels
in nq Total number of tracers
in dp pressure thickness
in,out q tracer mixing ratio
Definition at line 51 of file fv_fill.F90.
Referenced by fv_mapz_mod::lagrangian_to_eulerian(), fv_mapz_mod::mapn_tracer(), external_ic_mod::remap_scalar_ec(), external_ic_mod::remap_scalar_nggps(), fv_regional_mod::remap_scalar_nggps_regional_bc(), and external_ic_mod::remap_scalar_single().
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_fill.F90