fv_surf_map_mod Module Reference
Public Member Functions
subroutine, public surfdrv (npx, npy, grid, agrid, area, dx, dy, dxa, dya, dxc, dyc, sin_sg, phis, stretch_fac, nested, npx_global, domain, grid_number, bd, regional)
subroutine, public fv3_zs_filter (bd, isd, ied, jsd, jed, npx, npy, npx_global, stretch_fac, nested, domain, area, dxa, dya, dx, dy, dxc, dyc, grid, agrid, sin_sg, phis, oro, regional)
subroutine, public del2_cubed_sphere (npx, npy, q, area, dx, dy, dxc, dyc, sin_sg, nmax, cd, zero_ocean, oro, nested, domain, bd, regional)
subroutine, public del4_cubed_sphere (npx, npy, q, area, dx, dy, dxc, dyc, sin_sg, nmax, zero_ocean, oro, nested, domain, bd, regional)
Public Attributes
real, dimension(:,:),
*
allocatable, public zs_g
real, dimension(:,:),
*
allocatable, public sgh_g
real, dimension(:,:),
*
allocatable, public oro_g
Private Member Functions
subroutine two_delta_filter (npx, npy, q, area, dx, dy, dxa, dya, dxc, dyc, sin_sg, cd, zero_ocean, check_slope, filter_type, oro, nested, domain, bd, ntmax, regional)
subroutine map_to_cubed_raw (igh, im, jt, lat1, lon1, zs, ft, grid, agrid, q2, f2, h2, npx, npy, jstart, jend, stretch_fac, nested, npx_global, bd, regional)
subroutine handle_err (status)
The subroutine 'handle_err' returns an error when it cannot find or correctly read in an external file.
subroutine remove_ice_sheets (lon, lat, lfrac, bd)
subroutine read_namelist
The subroutine 'read_namelis' reads the namelist file, writes the namelist to log file, and initializes constants.
subroutine zonal_mean (im, p, zmean)
The sugroutine 'zonal_mean' replaces 'p' with its zonal mean.
Private Attributes
logical zs_filter = .true.
logical zero_ocean = .true.
integer nlon = 21600
integer nlat = 10800
real cd4 = 0.15
Dimensionless coeff for del-4 diffusion (with FCT)
real cd2 = -1.
Dimensionless coeff for del-2 diffusion (-1 gives resolution-determined value)
real peak_fac = 1.05
overshoot factor for the mountain peak
real max_slope = 0.15
max allowable terrain slope: 1 --> 45 deg 0.15 for C768 or lower; 0.25 C1536; 0.3 for C3072
integer n_del2_weak = 12
integer n_del2_strong = -1
integer n_del4 = -1
character(len=128) surf_file = `INPUT/topo1min.nc`
character(len=6) surf_format = 'netcdf'
logical namelist_read = .false.
real(kind=r_grid) da_min
real cos_grid
character(len=3) grid_string = ''
Detailed Description
Definition at line 22 of file fv_surf_map.F90.
Member Function/Subroutine Documentation
subroutine, public fv_surf_map_mod::del2_cubed_sphere (integer, intent(in) npx, integer, intent(in) npy, real, dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng), intent(inout) q, real(kind=r_grid), dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) area, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1), intent(in) dx, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed), intent(in) dy, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed), intent(in) dxc, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1), intent(in) dyc, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,9), intent(in) sin_sg, integer, intent(in) nmax, real(kind=r_grid), intent(in) cd, logical, intent(in) zero_ocean, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) oro, logical, intent(in) nested, type(domain2d), intent(inout) domain, type(fv_grid_bounds_type), intent(in) bd, logical, intent(in) regional)
Parameters
in oro 0==water, 1==land
Definition at line 859 of file fv_surf_map.F90.
Referenced by fv_restart_mod::fv_restart(), and external_ic_mod::get_nggps_ic().
subroutine, public fv_surf_map_mod::del4_cubed_sphere (integer, intent(in) npx, integer, intent(in) npy, real, dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng), intent(inout) q, real(kind=r_grid), dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) area, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1), intent(in) dx, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed), intent(in) dy, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed), intent(in) dxc, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1), intent(in) dyc, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,9), intent(in) sin_sg, integer, intent(in) nmax, logical, intent(in) zero_ocean, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) oro, logical, intent(in) nested, type(domain2d), intent(inout) domain, type(fv_grid_bounds_type), intent(in) bd, logical, intent(in) regional)
Parameters
in oro 0==water, 1==land
Definition at line 961 of file fv_surf_map.F90.
Referenced by fv3_zs_filter(), fv_restart_mod::fv_restart(), external_ic_mod::get_nggps_ic(), and surfdrv().
subroutine, public fv_surf_map_mod::fv3_zs_filter (type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npx_global, real(kind=r_grid), intent(in) stretch_fac, logical, intent(in) nested, type(domain2d), intent(inout) domain, real(kind=r_grid), dimension(isd:ied,jsd:jed), intent(in) area, real, dimension(isd:ied,jsd:jed), intent(in) dxa, real, dimension(isd:ied,jsd:jed), intent(in) dya, real, dimension(isd:ied, jsd:jed+1), intent(in) dx, real, dimension(isd:ied+1,jsd:jed), intent(in) dy, real, dimension(isd:ied+1,jsd:jed), intent(in) dxc, real, dimension(isd:ied, jsd:jed+1), intent(in) dyc, real(kind=r_grid), dimension(isd:ied+1, jsd:jed+1,2), intent(in) grid, real(kind=r_grid), dimension(isd:ied, jsd:jed, 2), intent(in) agrid, real, dimension(isd:ied,jsd:jed,9), intent(in) sin_sg, real, dimension(isd:ied,jsd,jed), intent(inout) phis, real, dimension(isd:ied,jsd,jed), intent(inout) oro, logical, intent(in) regional)
Definition at line 511 of file fv_surf_map.F90.
References del4_cubed_sphere(), fv_grid_utils_mod::global_mx(), read_namelist(), and two_delta_filter().
Referenced by external_ic_mod::get_nggps_ic(), and surfdrv().
subroutine fv_surf_map_mod::handle_err (integer status) [private]
The subroutine 'handle_err' returns an error when it cannot find or correctly read in an external file.
Definition at line 1533 of file fv_surf_map.F90.
Referenced by sim_nc_mod::close_ncfile(), sim_nc_mod::get_ncdim1(), sim_nc_mod::get_real3(), sim_nc_mod::get_var1_double(), sim_nc_mod::get_var1_real(), sim_nc_mod::get_var2_double(), sim_nc_mod::get_var2_r4(), sim_nc_mod::get_var2_real(), sim_nc_mod::get_var3_double(), sim_nc_mod::get_var3_r4(), sim_nc_mod::get_var3_real(), sim_nc_mod::get_var4_double(), sim_nc_mod::get_var4_real(), sim_nc_mod::get_var_att_double(), sim_nc_mod::get_var_att_str(), sim_nc_mod::open_ncfile(), and surfdrv().
subroutine fv_surf_map_mod::map_to_cubed_raw (integer, intent(in) igh, integer, intent(in) im, integer, intent(in) jt, real, dimension(jt+1), intent(in) lat1, real, dimension(im+1), intent(in) lon1, real(kind=4), dimension(-igh:im+igh,jt), intent(in) zs, real(kind=4), dimension(-igh:im+igh,jt), intent(in) ft, real(kind=r_grid), dimension(bd%isd:bd%ied+1, bd%jsd:bd%jed+1,2), intent(in) grid, real(kind=r_grid), dimension(bd%isd:bd%ied, bd%jsd:bd%jed, 2), intent(in) agrid, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(out) q2, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(out) f2, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(out) h2, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) jstart, integer, intent(in) jend, real(kind=r_grid), intent(in) stretch_fac, logical, intent(in) nested, integer, intent(in) npx_global, type(fv_grid_bounds_type), intent(in) bd, logical, intent(in) regional) [private]
Parameters
in lat1 original southern edge of the cell [-pi/2:pi/2]
in lon1 original western edge of the cell [0:2*pi]
out q2 Mapped data at the target resolution
out f2 oro
out h2 variances of terrain
Definition at line 1195 of file fv_surf_map.F90.
References fv_grid_utils_mod::latlon2xyz(), fv_grid_utils_mod::normalize_vect(), fv_grid_utils_mod::v_prod(), and fv_grid_utils_mod::vect_cross().
Referenced by surfdrv().
subroutine fv_surf_map_mod::read_namelist () [private]
The subroutine 'read_namelis' reads the namelist file, writes the namelist to log file, and initializes constants.
Definition at line 1596 of file fv_surf_map.F90.
Referenced by fv3_zs_filter(), and surfdrv().
subroutine fv_surf_map_mod::remove_ice_sheets (real(kind=r_grid), dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(in) lon, real(kind=r_grid), dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(in) lat, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(inout) lfrac, type(fv_grid_bounds_type), intent(in) bd) [private]
Definition at line 1544 of file fv_surf_map.F90.
subroutine, public fv_surf_map_mod::surfdrv (integer, intent(in) npx, integer, intent(in) npy, real(kind=r_grid), dimension(bd%is-ng:bd%ie+ng+1, bd%js-ng:bd%je+ng+1,2), intent(in) grid, real(kind=r_grid), dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng,2), intent(in) agrid, real(kind=r_grid), dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng), intent(in) area, real, dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng+1), intent(in) dx, real, dimension(bd%is-ng:bd%ie+ng+1, bd%js-ng:bd%je+ng), intent(in) dy, real, dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng), intent(in) dxa, real, dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng), intent(in) dya, real, dimension(bd%is-ng:bd%ie+ng+1, bd%js-ng:bd%je+ng), intent(in) dxc, real, dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng+1), intent(in) dyc, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,9), intent(in) sin_sg, real, dimension(bd%is-ng:bd%ie+ng, bd%js-ng:bd%je+ng), intent(out) phis, real(kind=r_grid), intent(in) stretch_fac, logical, intent(in) nested, integer, intent(in) npx_global, type(domain2d), intent(inout) domain, integer, intent(in) grid_number, type(fv_grid_bounds_type), intent(in) bd, logical, intent(in) regional)
Definition at line 133 of file fv_surf_map.F90.
References del4_cubed_sphere(), fv3_zs_filter(), fv_grid_utils_mod::g_sum(), fv_grid_utils_mod::global_mx(), handle_err(), map_to_cubed_raw(), read_namelist(), fv_timing_mod::timing_off(), and fv_timing_mod::timing_on().
Referenced by external_ic_mod::get_cubed_sphere_terrain(), and test_cases_mod::init_case().
subroutine fv_surf_map_mod::two_delta_filter (integer, intent(in) npx, integer, intent(in) npy, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(inout) q, real(kind=r_grid), dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) area, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1), intent(in) dx, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed), intent(in) dy, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) dxa, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) dya, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed), intent(in) dxc, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1), intent(in) dyc, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,9), intent(in) sin_sg, real, intent(in) cd, logical, intent(in) zero_ocean, logical, intent(in) check_slope, integer, intent(in) filter_type, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed), intent(in) oro, logical, intent(in) nested, type(domain2d), intent(inout) domain, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) ntmax, logical, intent(in) regional) [private]
Parameters
in filter_type 0: strong, 1: weak
in oro 0==water, 1==land
Definition at line 576 of file fv_surf_map.F90.
References fv_grid_utils_mod::global_mx().
Referenced by fv3_zs_filter().
subroutine fv_surf_map_mod::zonal_mean (integer, intent(in) im, real(kind=4), dimension(im), intent(inout) p, real, intent(out) zmean) [private]
The sugroutine 'zonal_mean' replaces 'p' with its zonal mean.
Definition at line 1628 of file fv_surf_map.F90.
Member Data Documentation
real fv_surf_map_mod::cd2 = -1. [private]
Dimensionless coeff for del-2 diffusion (-1 gives resolution-determined value)
Definition at line 105 of file fv_surf_map.F90.
real fv_surf_map_mod::cd4 = 0.15 [private]
Dimensionless coeff for del-4 diffusion (with FCT)
Definition at line 104 of file fv_surf_map.F90.
real fv_surf_map_mod::cos_grid [private]
Definition at line 119 of file fv_surf_map.F90.
real(kind=r_grid) fv_surf_map_mod::da_min [private]
Definition at line 118 of file fv_surf_map.F90.
character(len=3) fv_surf_map_mod::grid_string = '' [private]
Definition at line 120 of file fv_surf_map.F90.
real fv_surf_map_mod::max_slope = 0.15 [private]
max allowable terrain slope: 1 --> 45 deg 0.15 for C768 or lower; 0.25 C1536; 0.3 for C3072
Definition at line 107 of file fv_surf_map.F90.
integer fv_surf_map_mod::n_del2_strong = -1 [private]
Definition at line 110 of file fv_surf_map.F90.
integer fv_surf_map_mod::n_del2_weak = 12 [private]
Definition at line 109 of file fv_surf_map.F90.
integer fv_surf_map_mod::n_del4 = -1 [private]
Definition at line 111 of file fv_surf_map.F90.
logical fv_surf_map_mod::namelist_read = .false. [private]
Definition at line 116 of file fv_surf_map.F90.
integer fv_surf_map_mod::nlat = 10800 [private]
Definition at line 103 of file fv_surf_map.F90.
integer fv_surf_map_mod::nlon = 21600 [private]
Definition at line 102 of file fv_surf_map.F90.
real, dimension(:,:), allocatable, public fv_surf_map_mod::oro_g
Definition at line 125 of file fv_surf_map.F90.
real fv_surf_map_mod::peak_fac = 1.05 [private]
overshoot factor for the mountain peak
Definition at line 106 of file fv_surf_map.F90.
real, dimension(:,:), allocatable, public fv_surf_map_mod::sgh_g
Definition at line 125 of file fv_surf_map.F90.
character(len=128) fv_surf_map_mod::surf_file = `INPUT/topo1min.nc` [private]
Definition at line 114 of file fv_surf_map.F90.
character(len=6) fv_surf_map_mod::surf_format = 'netcdf' [private]
Definition at line 115 of file fv_surf_map.F90.
logical fv_surf_map_mod::zero_ocean = .true. [private]
Definition at line 101 of file fv_surf_map.F90.
logical fv_surf_map_mod::zs_filter = .true. [private]
Definition at line 100 of file fv_surf_map.F90.
real, dimension(:,:), allocatable, public fv_surf_map_mod::zs_g
Definition at line 125 of file fv_surf_map.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_surf_map.F90