fv_arrays_mod Module Reference
The module 'fv_arrays' contains the 'fv_atmos_type' and associated datatypes.
Data Types
interface allocate_fv_nest_bc_type
'allocate_fv_nest_BC_type' is an interface to subroutines that allocate the 'fv_nest_BC_type' structure that holds the nested-grid BCs.
interface deallocate_fv_nest_bc_type
'deallocate_fv_nest_BC_type' is an interface to a subroutine that deallocates the 'fv_nest_BC_type' structure that holds the nested-grid BCs.
type fv_atmos_type
type fv_diag_type
type fv_flags_type
type fv_grid_bounds_type
type fv_grid_type
The type 'fv_grid_type' is made up of grid-dependent information from fv_grid_tools and fv_grid_utils.
type fv_nest_bc_type_3d
type fv_nest_bc_type_4d
type fv_nest_type
type fv_regional_bc_bounds_type
Public Member Functions
subroutine allocate_fv_atmos_type (Atm, isd_in, ied_in, jsd_in, jed_in, is_in, ie_in, js_in, je_in, npx_in, npy_in, npz_in, ndims_in, ncnst_in, nq_in, ng_in, dummy, alloc_2d, ngrids_in)
The subroutine 'allocate_fv_atmos_type' allocates the fv_atmos_type.
subroutine deallocate_fv_atmos_type (Atm)
The subroutine 'deallocate_fv_atmos_type' deallocates the fv_atmos_type.
subroutine allocate_fv_nest_bc_type_3d_atm (BC, Atm, ns, istag, jstag, dummy)
subroutine allocate_fv_nest_bc_type_3d (BC, is, ie, js, je, isd, ied, jsd, jed, npx, npy, npz, ng, ns, istag, jstag, dummy)
subroutine deallocate_fv_nest_bc_type_3d (BC)
Public Attributes
integer, parameter, public r_grid = r8_kind
integer, parameter max_step = 1000
real, parameter real_big = 1.e30
real, parameter real_snan =x'FFF7FFFFFFFFFFFF'
real, parameter i4_in =-huge(1)
Detailed Description
The module 'fv_arrays' contains the 'fv_atmos_type' and associated datatypes.
Definition at line 24 of file fv_arrays.F90.
Member Function/Subroutine Documentation
subroutine fv_arrays_mod::allocate_fv_atmos_type (type(fv_atmos_type), intent(inout), target Atm, integer, intent(in) isd_in, integer, intent(in) ied_in, integer, intent(in) jsd_in, integer, intent(in) jed_in, integer, intent(in) is_in, integer, intent(in) ie_in, integer, intent(in) js_in, integer, intent(in) je_in, integer, intent(in) npx_in, integer, intent(in) npy_in, integer, intent(in) npz_in, integer, intent(in) ndims_in, integer, intent(in) ncnst_in, integer, intent(in) nq_in, integer, intent(in) ng_in, logical, intent(in) dummy, logical, intent(in) alloc_2d, integer, intent(in) ngrids_in)
The subroutine 'allocate_fv_atmos_type' allocates the fv_atmos_type.
It includes an option to define dummy grids that have scalar and small arrays defined as null 3D arrays.
Definition at line 1322 of file fv_arrays.F90.
Referenced by fv_control_mod::fv_init().
subroutine fv_arrays_mod::allocate_fv_nest_bc_type_3d (type(fv_nest_bc_type_3d), intent(inout) BC, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ng, integer, intent(in) ns, integer, intent(in) istag, integer, intent(in) jstag, logical, intent(in) dummy)
Definition at line 2015 of file fv_arrays.F90.
subroutine fv_arrays_mod::allocate_fv_nest_bc_type_3d_atm (type(fv_nest_bc_type_3d), intent(inout) BC, type(fv_atmos_type), intent(in) Atm, integer, intent(in) ns, integer, intent(in) istag, integer, intent(in) jstag, logical, intent(in) dummy)
Definition at line 1983 of file fv_arrays.F90.
References fv_arrays_mod::allocate_fv_nest_bc_type::allocate_fv_nest_bc_type_3d().
subroutine fv_arrays_mod::deallocate_fv_atmos_type (type(fv_atmos_type), intent(inout) Atm)
The subroutine 'deallocate_fv_atmos_type' deallocates the fv_atmos_type.
Definition at line 1769 of file fv_arrays.F90.
Referenced by fv_control_mod::fv_end().
subroutine fv_arrays_mod::deallocate_fv_nest_bc_type_3d (type(fv_nest_bc_type_3d) BC)
Definition at line 2094 of file fv_arrays.F90.
Member Data Documentation
real, parameter fv_arrays_mod::i4_in =-huge(1)
Definition at line 52 of file fv_arrays.F90.
integer, parameter fv_arrays_mod::max_step = 1000
Definition at line 43 of file fv_arrays.F90.
integer, parameter, public fv_arrays_mod::r_grid = r8_kind
Definition at line 35 of file fv_arrays.F90.
real, parameter fv_arrays_mod::real_big = 1.e30
Definition at line 49 of file fv_arrays.F90.
real, parameter fv_arrays_mod::real_snan =x'FFF7FFFFFFFFFFFF'
Definition at line 50 of file fv_arrays.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_arrays.F90