fv_iau_mod Module Reference
incremental analysis update module
Data Types
type iau_external_data_type
type iau_internal_data_type
type iau_state_type
Public Member Functions
subroutine, public iau_initialize (IPD_Control, IAU_Data, Init_parm)
subroutine, public getiauforcing (IPD_Control, IAU_Data)
Private Member Functions
subroutine updateiauforcing (IPD_Control, IAU_Data, wt)
subroutine setiauforcing (IPD_Control, IAU_Data, wt)
subroutine read_iau_forcing (IPD_Control, increments, fname)
subroutine interp_inc (field_name, var, jbeg, jend)
Private Attributes
real, dimension(:,:,:), allocatable s2c
integer, dimension(:,:),
*
allocatable id1
integer, dimension(:,:),
*
allocatable id2
integer, dimension(:,:),
*
allocatable jdc
real deg2rad
real dt
real rdt
integer im
integer jm
integer km
integer nfiles
integer ncid
integer is
integer ie
integer js
integer je
integer npz
integer ntracers
character(len=32), dimension(:),
*
allocatable tracer_names
integer, dimension(:), allocatable tracer_indicies
real(kind=4), dimension(:,:,:),
*
allocatable wk3
type(iau_state_type) iau_state
Detailed Description
incremental analysis update module
Author
Xi.Chen - author of fv_treat_da_inc.F90
Philip Pegion philip.pegion@noaa.gov
Date
09/13/2017 REVISION HISTORY: 09/13/2017 - Initial Version based on fv_treat_da_inc.F90
Definition at line 38 of file fv_iau_mod.F90.
Member Function/Subroutine Documentation
subroutine, public fv_iau_mod::getiauforcing (type (ipd_control_type), intent(in) IPD_Control, type(iau_external_data_type), intent(inout) IAU_Data)
Definition at line 286 of file fv_iau_mod.F90.
References read_iau_forcing(), setiauforcing(), and updateiauforcing().
subroutine, public fv_iau_mod::iau_initialize (type (ipd_control_type), intent(in) IPD_Control, type (iau_external_data_type), intent(inout) IAU_Data, type (ipd_init_type), intent(in) Init_parm)
Definition at line 109 of file fv_iau_mod.F90.
References sim_nc_mod::close_ncfile(), sim_nc_mod::get_ncdim1(), sim_nc_mod::open_ncfile(), read_iau_forcing(), external_ic_mod::remap_coef(), and setiauforcing().
subroutine fv_iau_mod::interp_inc (character(len=*), intent(in) field_name, real, dimension(is:ie,js:je,1:km), intent(inout) var, integer, intent(in) jbeg, integer, intent(in) jend) [private]
Definition at line 477 of file fv_iau_mod.F90.
References sim_nc_mod::check_var_exists(), and sim_nc_mod::get_var3_r4().
Referenced by read_iau_forcing().
subroutine fv_iau_mod::read_iau_forcing (type (ipd_control_type), intent(in) IPD_Control, type(iau_internal_data_type), intent(inout) increments, character(len=*), intent(in) fname) [private]
Definition at line 419 of file fv_iau_mod.F90.
References sim_nc_mod::close_ncfile(), interp_inc(), and sim_nc_mod::open_ncfile().
Referenced by getiauforcing(), and iau_initialize().
subroutine fv_iau_mod::setiauforcing (type (ipd_control_type), intent(in) IPD_Control, type(iau_external_data_type), intent(inout) IAU_Data, real(kind_phys) wt) [private]
Definition at line 393 of file fv_iau_mod.F90.
Referenced by getiauforcing(), and iau_initialize().
subroutine fv_iau_mod::updateiauforcing (type (ipd_control_type), intent(in) IPD_Control, type(iau_external_data_type), intent(inout) IAU_Data, real(kind_phys) wt) [private]
Definition at line 366 of file fv_iau_mod.F90.
Referenced by getiauforcing().
Member Data Documentation
real fv_iau_mod::deg2rad [private]
Definition at line 72 of file fv_iau_mod.F90.
real fv_iau_mod::dt [private]
Definition at line 72 of file fv_iau_mod.F90.
type(iau_state_type) fv_iau_mod::iau_state [private]
Definition at line 105 of file fv_iau_mod.F90.
integer, dimension(:,:), allocatable fv_iau_mod::id1 [private]
Definition at line 70 of file fv_iau_mod.F90.
integer, dimension(:,:), allocatable fv_iau_mod::id2 [private]
Definition at line 70 of file fv_iau_mod.F90.
integer fv_iau_mod::ie [private]
Definition at line 74 of file fv_iau_mod.F90.
integer fv_iau_mod::im [private]
Definition at line 73 of file fv_iau_mod.F90.
integer fv_iau_mod::is [private]
Definition at line 74 of file fv_iau_mod.F90.
integer, dimension(:,:), allocatable fv_iau_mod::jdc [private]
Definition at line 70 of file fv_iau_mod.F90.
integer fv_iau_mod::je [private]
Definition at line 74 of file fv_iau_mod.F90.
integer fv_iau_mod::jm [private]
Definition at line 73 of file fv_iau_mod.F90.
integer fv_iau_mod::js [private]
Definition at line 74 of file fv_iau_mod.F90.
integer fv_iau_mod::km [private]
Definition at line 73 of file fv_iau_mod.F90.
integer fv_iau_mod::ncid [private]
Definition at line 73 of file fv_iau_mod.F90.
integer fv_iau_mod::nfiles [private]
Definition at line 73 of file fv_iau_mod.F90.
integer fv_iau_mod::npz [private]
Definition at line 75 of file fv_iau_mod.F90.
integer fv_iau_mod::ntracers [private]
Definition at line 75 of file fv_iau_mod.F90.
real fv_iau_mod::rdt [private]
Definition at line 72 of file fv_iau_mod.F90.
real, dimension(:,:,:), allocatable fv_iau_mod::s2c [private]
Definition at line 66 of file fv_iau_mod.F90.
integer, dimension(:), allocatable fv_iau_mod::tracer_indicies [private]
Definition at line 77 of file fv_iau_mod.F90.
character(len=32), dimension(:), allocatable fv_iau_mod::tracer_names [private]
Definition at line 76 of file fv_iau_mod.F90.
real(kind=4), dimension(:,:,:), allocatable fv_iau_mod::wk3 [private]
Definition at line 79 of file fv_iau_mod.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_iau_mod.F90