fv_nwp_nudge_mod Module Reference
The module fv_nwp_nudge contains routines for nudging to input analyses. note This module is currently not supported in fvGFS of FV3GFS.
Public Member Functions
subroutine, public fv_nwp_nudge (Time, dt, npx, npy, npz, ps_dt, u_dt, v_dt, t_dt, q_dt, zvir, ptop, ak, bk, ts, ps, delp, ua, va, pt, nwat, q, phis, gridstruct, bd, domain)
Ths subroutine 'fv_nwp_nudge' computes and returns time tendencies for nudging to analysis.
subroutine, public fv_nwp_nudge_init (time, axes, npz, zvir, ak, bk, ts, phis, gridstruct, ks, npx, neststruct, bd)
The subroutine 'fv_nwp_nudge_init' initializes the nudging module.
subroutine, public fv_nwp_nudge_end
The subroutine 'fv_nwp_nudge_end' terminates the nudging module.
subroutine, public breed_slp_inline (nstep, dt, npz, ak, bk, phis, pe, pk, peln, pkz, delp, u, v, pt, q, nwat, zvir, gridstruct, ks, domain_local, bd, hydrostatic)
The subroutine 'breed_slp_inline' performs vortex breeding by nudging sea level pressure toward single point observations.
Public Attributes
logical, public do_adiabatic_init
logical, public t_is_tv = .false.
Private Member Functions
subroutine ps_nudging (dt, factor, npz, ak, bk, ps_obs, mask, tm, ps, phis, delp, ua, va, pt, nwat, q, bd, npx, npy, gridstruct, domain)
subroutine ps_bias_correction (ps_dt, is, ie, js, je, isd, ied, jsd, jed, area)
real function g0_sum (p, ifirst, ilast, jfirst, jlast, mode, reproduce, isd, ied, jsd, jed, area)
Fast version of global sum that is reproduced if the result is rounded to 4-byte.
subroutine compute_slp (isc, iec, jsc, jec, tm, ps, gz, slp)
subroutine get_obs (Time, dt, zvir, ak, bk, ps, ts, ps_obs, delp, pt, nwat, q, u_obs, v_obs, t_obs, q_obs, phis, ua, va, u_dt, v_dt, npx, npy, npz, factor, mask, ptop, bd, gridstruct, domain)
subroutine get_ncep_analysis (ps, u, v, t, q, zvir, ts, nfile, fname, bd)
subroutine remap_coef (agrid)
subroutine ncep2fms (sst)
subroutine get_int_hght (npz, ak, bk, ps, delp, ps0, tv)
subroutine remap_tq (npz, ak, bk, ps, delp, t, q, kmd, ps0, ta, qa, zvir, ptop)
subroutine remap_uv (npz, ak, bk, ps, delp, u, v, kmd, ps0, u0, v0, ptop)
subroutine get_tc_mask (time, mask, agrid)
subroutine breed_srf_w10 (time, dt, npz, ak, bk, ps, phis, slp, delp, u, v, gridstruct)
The subroutine 'breed_srf_w10' performs vortex breeding by nudging 10-m winds.
subroutine breed_srf_winds (time, dt, npz, u_obs, v_obs, ak, bk, ps, phis, delp, ua, va, u_dt, v_dt, pt, q, nwat, zvir, gridstruct)
The subroutine 'breed_srf_winds' performs vortex breeding by nudging 1-m winds.
subroutine tangent_wind (elon, elat, speed, po, pp, ut, vt)
subroutine get_slp_obs (time, nobs, lon_obs, lat_obs, w10, mslp, slp_out, r_out, time_obs, x_o, y_o, w10_o, slp_o, r_vor, p_vor, stime, fact)
subroutine slp_obs_init
real function calday (year, month, day, hour, minute, sec)
The function 'calday' performs time interpolation:
logical function leap_year (ny)
subroutine pmaxmin (qname, a, imax, jmax, fac)
subroutine del2_uv (du, dv, cd, kmd, ntimes, bd, npx, npy, gridstruct, domain)
The subroutine 'del2_uv' filters the wind tendency.
subroutine del2_scalar (qdt, cd, kmd, nmax, bd, npx, npy, gridstruct, domain)
The subroutine 'del2_scalar' filters the physics tendency.
subroutine rmse_bias (a, rms, bias, area)
subroutine corr (a, b, co, area)
subroutine std (a, mean, stdv, area)
Private Attributes
real(kind=r_grid), parameter radius = cnst_radius
integer im
Data x-dimension.
integer jm
Data y-dimension.
integer km
Data z-dimension.
real, dimension(:), allocatable ak0
real, dimension(:), allocatable bk0
real, dimension(:), allocatable lat
real, dimension(:), allocatable lon
logical module_is_initialized = .false.
logical master
logical no_obs
real deg2rad
real rad2deg
real time_nudge = 0.
integer time_interval = 6*3600
dataset time interval (seconds)
integer, parameter nfile_max = 29280
maximum: 20-year analysis data, 4*366*20=29280
integer nfile
integer k_breed = 0
integer k_trop = 0
real p_trop = 950.E2
real dps_min = 50.
maximum PS increment (pa; each step) due to inline breeding
real del2_cd = 0.16
real, dimension(:,:,:), allocatable s2c
integer, dimension(:,:),
*
allocatable id1
integer, dimension(:,:),
*
allocatable id2
integer, dimension(:,:),
*
allocatable jdc
real, dimension(:,:,:), allocatable ps_dat
real(kind=4), dimension(:,:,:,:),
*
allocatable u_dat
real(kind=4), dimension(:,:,:,:),
*
allocatable v_dat
real(kind=4), dimension(:,:,:,:),
*
allocatable t_dat
real(kind=4), dimension(:,:,:,:),
*
allocatable q_dat
real(kind=4), dimension(:,:,:),
*
allocatable gz3
work array
real, dimension(:,:), allocatable gz0
character(len=128) input_fname_list =``
a file lists the input NCEP analysis data
character(len=128) analysis_file_first =``
the first NCEP analysis file to be used for nudging, by default, the first file in the `input_fname_list`
character(len=128) analysis_file_last =``
the last NCEP analysis file to be used for nudging by default, the last file in the `input_fname_list`
real p_relax = 30.E2
from P_relax upwards, nudging is reduced linearly proportional to pfull/P_relax
real p_norelax = 0.0
from P_norelax upwards, no nudging
character(len=128), dimension(nfile_max) file_names
character(len=128) track_file_name
integer nfile_total = 0
=5 for 1-day (if datasets are 6-hr apart)
real p_wvp = 100.E2
cutoff level for specific humidity nudging
integer kord_data = 8
real mask_fac = 0.25
[0,1] 0: no mask; 1: full strength
logical use_pt_inc = .false.
logical use_high_top = .false.
logical add_bg_wind = .true.
logical conserve_mom = .true.
logical conserve_hgt = .true.
logical tc_mask = .false.
logical strong_mask = .false.
logical ibtrack = .true.
logical nudge_debug = .false.
logical do_ps_bias = .false.
logical nudge_ps = .false.
logical nudge_q = .false.
logical nudge_winds = .true.
logical nudge_virt = .true.
logical nudge_hght = .true.
logical time_varying = .true.
logical print_end_breed = .true.
logical print_end_nudge = .true.
real tau_ps = 21600.
1-day
real tau_q = 86400.
1-day
real tau_winds = 21600.
6-hr
real tau_virt = 43200.
real tau_hght = 43200.
real q_min = 1.E-8
integer jbeg
integer jend
integer nf_uv = 0
integer nf_ps = 0
integer nf_t = 2
integer nf_ht = 1
integer kstart = 2
integer kbot_winds = 0
integer kbot_t = 0
integer kbot_q = 0
logical analysis_time
logical breed_srf_w = .false.
real grid_size = 28.E3
real tau_vt_slp = 1200.
real tau_vt_wind = 1200.
real tau_vt_rad = 4.0
real pt_lim = 0.2
real slp_env = 101010.
storm environment pressure (pa)
real pre0_env = 100000.
critical storm environment pressure (pa) for size computation
real, parameter tm_max = 315.
real r_lo = 2.0
real r_hi = 5.0
real r_fac = 1.2
real r_min = 200.E3
real r_inc = 25.E3
real, parameter del_r = 50.E3
real elapsed_time = 0.0
real nudged_time = 1.E12
seconds
integer year_track_data
integer, parameter max_storm = 140
max # of storms to process
integer, parameter nobs_max = 125
Max # of observations per storm.
integer nstorms = 0
integer, dimension(max_storm) nobs_tc
integer min_nobs = 16
real min_mslp = 1009.E2
real(kind=4), dimension(nobs_max,
*
max_storm) x_obs
longitude in degrees
real(kind=4), dimension(nobs_max,
*
max_storm) y_obs
latitude in degrees
real(kind=4), dimension(nobs_max,
*
max_storm) wind_obs
observed 10-m wind speed (m/s)
real(kind=4), dimension(nobs_max,
*
max_storm) mslp_obs
observed SLP in mb
real(kind=4), dimension(nobs_max,
*
max_storm) mslp_out
outer ring SLP in mb
real(kind=4), dimension(nobs_max,
*
max_storm) rad_out
outer ring radius in meters
real(kind=4), dimension(nobs_max,
*
max_storm) time_tc
start time of the track
integer id_ht_err
integer is
integer ie
integer js
integer je
integer isd
integer ied
integer jsd
integer jed
Detailed Description
The module fv_nwp_nudge contains routines for nudging to input analyses. note This module is currently not supported in fvGFS of FV3GFS.
Definition at line 32 of file fv_nudge.F90.
Member Function/Subroutine Documentation
subroutine, public fv_nwp_nudge_mod::breed_slp_inline (integer, intent(in) nstep, real, intent(in) dt, integer, intent(in) npz, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(isd:ied,jsd:jed), intent(in) phis, real, dimension(is-1:ie+1, npz+1,js-1:je+1), intent(inout) pe, real, dimension(is:ie,js:je, npz+1), intent(inout) pk, real, dimension(is:ie,npz+1,js:je), intent(out) peln, real, dimension(is:ie,js:je,npz), intent(inout) pkz, real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied,jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed,npz), intent(inout) v, real, dimension(isd:ied,jsd:jed,npz), intent(inout) pt, real, dimension(isd:ied,jsd:jed,npz,*), intent(inout) q, integer, intent(in) nwat, real, intent(in) zvir, type(fv_grid_type), target gridstruct, integer, intent(in) ks, type(domain2d), intent(inout) domain_local, type(fv_grid_bounds_type), intent(in) bd, logical, intent(in) hydrostatic)
The subroutine 'breed_slp_inline' performs vortex breeding by nudging sea level pressure toward single point observations.
This is a tropical cyclone 'bogusing' routine that currently only works for hydrostatic dynamics.
Note
Note: conserve water mass, geopotential, and momentum at the expense of dry air mass
Parameters
in dt (small) time step in seconds
in,out pk pe**kappa
in,out pe edge pressure (pascal)
out peln ln(pe)
Definition at line 2155 of file fv_nudge.F90.
References calday(), compute_slp(), get_slp_obs(), fv_grid_utils_mod::great_circle_dist(), fv_diagnostics_mod::p_sum(), fv_diagnostics_mod::prt_maxmin(), multi_gases_mod::vicpqd(), and multi_gases_mod::virqd().
Referenced by dyn_core_mod::dyn_core().
subroutine fv_nwp_nudge_mod::breed_srf_w10 (type(time_type), intent(in) time, real, intent(in) dt, integer, intent(in) npz, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(isd:ied,jsd:jed), intent(in) ps, real, dimension(isd:ied,jsd:jed), intent(in) phis, real, dimension(is:ie,js:je), intent(in) slp, real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied,jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed,npz), intent(inout) v, type(fv_grid_type), intent(in), target gridstruct) [private]
The subroutine 'breed_srf_w10' performs vortex breeding by nudging 10-m winds.
This is the inline version.
Parameters
in dt time step in seconds
Definition at line 2648 of file fv_nudge.F90.
References get_slp_obs(), fv_grid_utils_mod::great_circle_dist(), and tangent_wind().
subroutine fv_nwp_nudge_mod::breed_srf_winds (type(time_type), intent(in) time, real, intent(in) dt, integer, intent(in) npz, real, dimension(is:ie,js:je,npz), intent(in) u_obs, real, dimension(is:ie,js:je,npz), intent(in) v_obs, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(isd:ied,jsd:jed), intent(in) ps, real, dimension(isd:ied,jsd:jed), intent(in) phis, real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied,jsd:jed,npz), intent(inout) ua, real, dimension(isd:ied,jsd:jed,npz), intent(inout) va, real, dimension(isd:ied,jsd:jed,npz), intent(inout) u_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) v_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) pt, real, dimension(isd:ied,jsd:jed,npz,nwat), intent(inout) q, integer, intent(in) nwat, real, intent(in) zvir, type(fv_grid_type), intent(in), target gridstruct) [private]
The subroutine 'breed_srf_winds' performs vortex breeding by nudging 1-m winds.
Parameters
in dt time step in seconds
Definition at line 2927 of file fv_nudge.F90.
References get_slp_obs(), fv_grid_utils_mod::great_circle_dist(), and tangent_wind().
Referenced by fv_nwp_nudge().
real function fv_nwp_nudge_mod::calday (integer, intent(in) year, integer, intent(in) month, integer, intent(in) day, integer, intent(in) hour, integer, intent(in) minute, integer, intent(in) sec) [private]
The function 'calday' performs time interpolation:
Definition at line 3408 of file fv_nudge.F90.
References leap_year().
Referenced by breed_slp_inline(), get_slp_obs(), and slp_obs_init().
subroutine fv_nwp_nudge_mod::compute_slp (integer, intent(in) isc, integer, intent(in) iec, integer, intent(in) jsc, integer, intent(in) jec, real, dimension(isc:iec,jsc:jec), intent(in) tm, real, dimension(isc:iec,jsc:jec), intent(in) ps, real, dimension(isc:iec,jsc:jec), intent(in) gz, real, dimension(isc:iec,jsc:jec), intent(out) slp) [private]
Definition at line 1077 of file fv_nudge.F90.
Referenced by breed_slp_inline(), and fv_nwp_nudge().
subroutine fv_nwp_nudge_mod::corr (real, dimension(is:ie,js:je), intent(in) a, real, dimension(is:ie,js:je), intent(in) b, real, intent(out) co, real, dimension(isd:ied,jsd:jed), intent(in) area) [private]
Definition at line 3692 of file fv_nudge.F90.
References std().
Referenced by fv_nwp_nudge().
subroutine fv_nwp_nudge_mod::del2_scalar (real, dimension(is:ie,js:je,kmd), intent(inout) qdt, real, intent(in) cd, integer, intent(in) kmd, integer, intent(in) nmax, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) domain) [private]
The subroutine 'del2_scalar' filters the physics tendency.
Parameters
in nmax must be no greater than 3
in cd cd = K * da_min; 0 < K < 0.25
Definition at line 3549 of file fv_nudge.F90.
References tp_core_mod::copy_corners(), fv_timing_mod::timing_off(), and fv_timing_mod::timing_on().
Referenced by del2_uv(), fv_nwp_nudge(), and ps_nudging().
subroutine fv_nwp_nudge_mod::del2_uv (real, dimension(is:ie,js:je,kmd), intent(inout) du, real, dimension(is:ie,js:je,kmd), intent(inout) dv, real, intent(in) cd, integer, intent(in) kmd, integer, intent(in) ntimes, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) domain) [private]
The subroutine 'del2_uv' filters the wind tendency.
Parameters
in cd cd = K * da_min; 0 < K < 0.25
Definition at line 3501 of file fv_nudge.F90.
References del2_scalar().
Referenced by fv_nwp_nudge().
subroutine, public fv_nwp_nudge_mod::fv_nwp_nudge (type(time_type), intent(in) Time, real, intent(in) dt, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, real, dimension(is:ie,js:je), intent(out) ps_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) u_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) v_dt, real, dimension(is:ie,js:je,npz), intent(out) t_dt, real, dimension(is:ie,js:je,npz), intent(out) q_dt, real, intent(in) zvir, real, intent(in) ptop, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(is:ie,js:je), intent(out) ts, real, dimension(isd:ied,jsd:jed), intent(inout) ps, real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied,jsd:jed,npz), intent(inout) ua, real, dimension(isd:ied,jsd:jed,npz), intent(inout) va, real, dimension(isd:ied,jsd:jed,npz), intent(inout) pt, integer, intent(in) nwat, real, dimension(isd:ied,jsd:jed,npz,nwat), intent(inout) q, real, dimension(isd:ied,jsd:jed), intent(in) phis, type(fv_grid_type), intent(inout), target gridstruct, type(fv_grid_bounds_type), intent(in) bd, type(domain2d), intent(inout), target domain)
Ths subroutine 'fv_nwp_nudge' computes and returns time tendencies for nudging to analysis.
This nudging is typically applied to fv_update_phys.
Parameters
in npz vertical dimension
Definition at line 303 of file fv_nudge.F90.
References breed_srf_winds(), compute_slp(), corr(), del2_scalar(), del2_uv(), g0_sum(), get_obs(), get_tc_mask(), fv_diagnostics_mod::prt_maxmin(), rmse_bias(), and multi_gases_mod::virq().
Referenced by fv_update_phys_mod::fv_update_phys().
subroutine, public fv_nwp_nudge_mod::fv_nwp_nudge_end ()
The subroutine 'fv_nwp_nudge_end' terminates the nudging module.
Definition at line 2084 of file fv_nudge.F90.
subroutine, public fv_nwp_nudge_mod::fv_nwp_nudge_init (type(time_type), intent(in) time, integer, dimension(4), intent(in) axes, integer, intent(in) npz, real, intent(in) zvir, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(bd%is:bd%ie,bd%js:bd%je), intent(out) ts, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(in) phis, type(fv_grid_type), target gridstruct, integer, intent(in) ks, integer, intent(in) npx, type(fv_nest_type) neststruct, type(fv_grid_bounds_type), intent(in) bd)
The subroutine 'fv_nwp_nudge_init' initializes the nudging module.
This module opens analysis files and computes remapping coefficients.
Parameters
in npz vertical dimension
Definition at line 1256 of file fv_nudge.F90.
References sim_nc_mod::close_ncfile(), sim_nc_mod::get_ncdim1(), get_ncep_analysis(), sim_nc_mod::open_ncfile(), external_ic_mod::remap_coef(), and slp_obs_init().
real function fv_nwp_nudge_mod::g0_sum (real, dimension(ifirst:ilast,jfirst:jlast), intent(in) p, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) jfirst, integer, intent(in) jlast, integer, intent(in) mode, logical, intent(in) reproduce, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, dimension(isd:ied,jsd:jed), intent(in) area) [private]
Fast version of global sum that is reproduced if the result is rounded to 4-byte.
Parameters
in mode if ==1 divided by global area
in p field to be summed
Definition at line 1044 of file fv_nudge.F90.
Referenced by fv_nwp_nudge(), and ps_bias_correction().
subroutine fv_nwp_nudge_mod::get_int_hght (integer, intent(in) npz, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(is:ie,js:je), intent(in) ps, real, dimension(isd:ied,jsd:jed,npz), intent(in) delp, real, dimension(is:ie,js:je), intent(in) ps0, real(kind=4), dimension(is:ie,js:je,km), intent(in) tv) [private]
Definition at line 1894 of file fv_nudge.F90.
Referenced by get_obs().
subroutine fv_nwp_nudge_mod::get_ncep_analysis (real, dimension(is:ie,js:je), intent(out) ps, real(kind=4), dimension(is:ie,js:je,km), intent(out) u, real(kind=4), dimension(is:ie,js:je,km), intent(out) v, real(kind=4), dimension(is:ie,js:je,km), intent(out) t, real(kind=4), dimension(is:ie,js:je,km), intent(out) q, real, intent(in) zvir, real, dimension(is:ie,js:je), intent(out) ts, integer, intent(inout) nfile, character(len=128), intent(in) fname, type(fv_grid_bounds_type), intent(in) bd) [private]
Definition at line 1485 of file fv_nudge.F90.
References sim_nc_mod::close_ncfile(), sim_nc_mod::get_var3_r4(), external_ic_mod::ncep2fms(), sim_nc_mod::open_ncfile(), external_ic_mod::pmaxmin(), and fv_diagnostics_mod::prt_maxmin().
Referenced by fv_nwp_nudge_init(), and get_obs().
subroutine fv_nwp_nudge_mod::get_obs (type(time_type), intent(in) Time, real, intent(in) dt, real, intent(in) zvir, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(isd:ied,jsd:jed), intent(inout) ps, real, dimension(is:ie,js:je), intent(out) ts, real, dimension(is:ie,js:je), intent(out) ps_obs, real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied,jsd:jed,npz), intent(inout) pt, integer, intent(in) nwat, real, dimension(isd:ied,jsd:jed,npz,*), intent(inout) q, real, dimension(is:ie,js:je,npz), intent(out) u_obs, real, dimension(is:ie,js:je,npz), intent(out) v_obs, real, dimension(is:ie,js:je,npz), intent(out) t_obs, real, dimension(is:ie,js:je,npz), intent(out) q_obs, real, dimension(isd:ied,jsd:jed), intent(in) phis, real, dimension(isd:ied,jsd:jed,npz), intent(inout) ua, real, dimension(isd:ied,jsd:jed,npz), intent(inout) va, real, dimension(isd:ied,jsd:jed,npz), intent(inout) u_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) v_dt, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, real, intent(in) factor, real, dimension(is:ie,js:je), intent(in) mask, real, intent(in) ptop, type(fv_grid_bounds_type), intent(in) bd, type(fv_grid_type), intent(in) gridstruct, type(domain2d), intent(inout) domain) [private]
Definition at line 1093 of file fv_nudge.F90.
References get_int_hght(), get_ncep_analysis(), ps_nudging(), remap_tq(), and remap_uv().
Referenced by fv_nwp_nudge().
subroutine fv_nwp_nudge_mod::get_slp_obs (type(time_type), intent(in) time, integer, intent(in) nobs, real(kind=4), dimension(nobs), intent(in) lon_obs, real(kind=4), dimension(nobs), intent(in) lat_obs, real(kind=4), dimension(nobs), intent(in) w10, real(kind=4), dimension(nobs), intent(in) mslp, real(kind=4), dimension(nobs), intent(in) slp_out, real(kind=4), dimension(nobs), intent(in) r_out, real(kind=4), dimension(nobs), intent(in) time_obs, real(kind=r_grid), intent(out) x_o, real(kind=r_grid), intent(out) y_o, real, intent(out) w10_o, real, intent(out) slp_o, real, intent(out) r_vor, real, intent(out) p_vor, real, intent(in), optional stime, real, intent(out), optional fact) [private]
Parameters
in nobs number of observations in this particular storm
in w10 observed 10-m widn speed
in mslp observed SLP in pa
in slp_out slp at r_out
out y_o position of the storm center
out w10_o 10-m wind speed
out slp_o Observed sea-level-pressure (pa)
Definition at line 3185 of file fv_nudge.F90.
References calday(), and fv_grid_utils_mod::intp_great_circle().
Referenced by breed_slp_inline(), breed_srf_w10(), breed_srf_winds(), and get_tc_mask().
subroutine fv_nwp_nudge_mod::get_tc_mask (type(time_type), intent(in) time, real, dimension(is:ie,js:je), intent(inout) mask, real(kind=r_grid), dimension(isd:ied,jsd:jed,2), intent(in) agrid) [private]
Definition at line 2110 of file fv_nudge.F90.
References get_slp_obs(), and fv_grid_utils_mod::great_circle_dist().
Referenced by fv_nwp_nudge().
logical function fv_nwp_nudge_mod::leap_year (integer, intent(in) ny) [private]
The function 'leap_year' determines if year 'ny' is a leap year.
Author
Shian-Jiann Lin
Definition at line 3442 of file fv_nudge.F90.
Referenced by calday().
subroutine fv_nwp_nudge_mod::ncep2fms (real(kind=4), dimension(im,jm), intent(in) sst) [private]
Definition at line 1808 of file fv_nudge.F90.
subroutine fv_nwp_nudge_mod::pmaxmin (character(len=*) qname, real, dimension(imax,jmax) a, integer imax, integer jmax, real fac) [private]
Definition at line 3465 of file fv_nudge.F90.
subroutine fv_nwp_nudge_mod::ps_bias_correction (real, dimension(is:ie,js:je), intent(inout) ps_dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, dimension(isd:ied,jsd:jed), intent(in) area) [private]
Definition at line 976 of file fv_nudge.F90.
References g0_sum().
Referenced by ps_nudging().
subroutine fv_nwp_nudge_mod::ps_nudging (real, intent(in) dt, real, intent(in) factor, integer, intent(in) npz, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(is:ie,js:je), intent(in) ps_obs, real, dimension(is:ie,js:je), intent(in) mask, real, dimension(is:ie,js:je), intent(in) tm, real, dimension(isd:ied,jsd:jed), intent(inout) ps, real, dimension(isd:ied,jsd:jed), intent(in) phis, real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied,jsd:jed,npz), intent(inout) ua, real, dimension(isd:ied,jsd:jed,npz), intent(inout) va, real, dimension(isd:ied,jsd:jed,npz), intent(inout) pt, integer, intent(in) nwat, real, dimension(isd:ied,jsd:jed,npz,nwat), intent(inout) q, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) domain) [private]
Definition at line 795 of file fv_nudge.F90.
References del2_scalar(), ps_bias_correction(), multi_gases_mod::vicpqd(), and multi_gases_mod::virqd().
Referenced by get_obs().
subroutine fv_nwp_nudge_mod::remap_coef (real, dimension(isd:ied,jsd:jed,2), intent(in) agrid) [private]
Definition at line 1732 of file fv_nudge.F90.
subroutine fv_nwp_nudge_mod::remap_tq (integer, intent(in) npz, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(is:ie,js:je), intent(inout) ps, real, dimension(isd:ied,jsd:jed,npz), intent(in) delp, real(kind=4), dimension(is:ie,js:je,npz), intent(out) t, real(kind=4), dimension(is:ie,js:je,npz), intent(out) q, integer, intent(in) kmd, real, dimension(is:ie,js:je), intent(in) ps0, real(kind=4), dimension(is:ie,js:je,kmd), intent(in) ta, real(kind=4), dimension(is:ie,js:je,kmd), intent(in) qa, real, intent(in) zvir, real, intent(in) ptop) [private]
Definition at line 1929 of file fv_nudge.F90.
References fv_mapz_mod::mappm().
Referenced by get_obs().
subroutine fv_nwp_nudge_mod::remap_uv (integer, intent(in) npz, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(is:ie,js:je), intent(inout) ps, real, dimension(isd:ied,jsd:jed,npz), intent(in) delp, real(kind=4), dimension(is:ie,js:je,npz), intent(inout) u, real(kind=4), dimension(is:ie,js:je,npz), intent(inout) v, integer, intent(in) kmd, real, dimension(is:ie,js:je), intent(in) ps0, real(kind=4), dimension(is:ie,js:je,kmd), intent(in) u0, real(kind=4), dimension(is:ie,js:je,kmd), intent(in) v0, real, intent(in) ptop) [private]
Definition at line 2009 of file fv_nudge.F90.
References fv_mapz_mod::mappm().
Referenced by get_obs().
subroutine fv_nwp_nudge_mod::rmse_bias (real, dimension(is:ie,js:je), intent(in) a, real, intent(out) rms, real, intent(out) bias, real, dimension(isd:ied,jsd:jed), intent(in) area) [private]
Definition at line 3666 of file fv_nudge.F90.
Referenced by fv_nwp_nudge().
subroutine fv_nwp_nudge_mod::slp_obs_init () [private]
Definition at line 3278 of file fv_nudge.F90.
References calday().
Referenced by fv_nwp_nudge_init().
subroutine fv_nwp_nudge_mod::std (real, dimension(is:ie,js:je), intent(in) a, real, intent(out) mean, real, intent(out) stdv, real, dimension(isd:ied,jsd:jed), intent(in) area) [private]
Definition at line 3718 of file fv_nudge.F90.
Referenced by corr().
subroutine fv_nwp_nudge_mod::tangent_wind (real(kind=r_grid), dimension(3), intent(in) elon, real(kind=r_grid), dimension(3), intent(in) elat, real, intent(in) speed, real(kind=r_grid), dimension(2), intent(in) po, real(kind=r_grid), dimension(2), intent(in) pp, real, intent(out) ut, real, intent(out) vt) [private]
Definition at line 3157 of file fv_nudge.F90.
References fv_grid_utils_mod::latlon2xyz(), fv_grid_utils_mod::normalize_vect(), and fv_grid_utils_mod::vect_cross().
Referenced by breed_srf_w10(), and breed_srf_winds().
Member Data Documentation
logical fv_nwp_nudge_mod::add_bg_wind = .true. [private]
Definition at line 198 of file fv_nudge.F90.
real, dimension(:), allocatable fv_nwp_nudge_mod::ak0 [private]
Definition at line 145 of file fv_nudge.F90.
character(len=128) fv_nwp_nudge_mod::analysis_file_first =`` [private]
the first NCEP analysis file to be used for nudging, by default, the first file in the `input_fname_list`
Definition at line 176 of file fv_nudge.F90.
character(len=128) fv_nwp_nudge_mod::analysis_file_last =`` [private]
the last NCEP analysis file to be used for nudging by default, the last file in the `input_fname_list`
Definition at line 178 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::analysis_time [private]
Definition at line 239 of file fv_nudge.F90.
real, dimension(:), allocatable fv_nwp_nudge_mod::bk0 [private]
Definition at line 145 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::breed_srf_w = .false. [private]
Definition at line 245 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::conserve_hgt = .true. [private]
Definition at line 200 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::conserve_mom = .true. [private]
Definition at line 199 of file fv_nudge.F90.
real fv_nwp_nudge_mod::deg2rad [private]
Definition at line 151 of file fv_nudge.F90.
real fv_nwp_nudge_mod::del2_cd = 0.16 [private]
Definition at line 164 of file fv_nudge.F90.
real, parameter fv_nwp_nudge_mod::del_r = 50.E3 [private]
Definition at line 262 of file fv_nudge.F90.
logical, public fv_nwp_nudge_mod::do_adiabatic_init
Definition at line 138 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::do_ps_bias = .false. [private]
Definition at line 205 of file fv_nudge.F90.
real fv_nwp_nudge_mod::dps_min = 50. [private]
maximum PS increment (pa; each step) due to inline breeding
Definition at line 163 of file fv_nudge.F90.
real fv_nwp_nudge_mod::elapsed_time = 0.0 [private]
Definition at line 263 of file fv_nudge.F90.
character(len=128), dimension(nfile_max) fv_nwp_nudge_mod::file_names [private]
Definition at line 187 of file fv_nudge.F90.
real fv_nwp_nudge_mod::grid_size = 28.E3 [private]
Definition at line 246 of file fv_nudge.F90.
real, dimension(:,:), allocatable fv_nwp_nudge_mod::gz0 [private]
Definition at line 171 of file fv_nudge.F90.
real(kind=4), dimension(:,:,:), allocatable fv_nwp_nudge_mod::gz3 [private]
work array
Definition at line 170 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::ibtrack = .true. [private]
Definition at line 203 of file fv_nudge.F90.
integer, dimension(:,:), allocatable fv_nwp_nudge_mod::id1 [private]
Definition at line 167 of file fv_nudge.F90.
integer, dimension(:,:), allocatable fv_nwp_nudge_mod::id2 [private]
Definition at line 167 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::id_ht_err [private]
Definition at line 284 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::ie [private]
Definition at line 287 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::ied [private]
Definition at line 288 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::im [private]
Data x-dimension.
Definition at line 142 of file fv_nudge.F90.
character(len=128) fv_nwp_nudge_mod::input_fname_list =`` [private]
a file lists the input NCEP analysis data
Definition at line 175 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::is [private]
Definition at line 287 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::isd [private]
Definition at line 288 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::jbeg [private]
Definition at line 226 of file fv_nudge.F90.
integer, dimension(:,:), allocatable fv_nwp_nudge_mod::jdc [private]
Definition at line 167 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::je [private]
Definition at line 287 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::jed [private]
Definition at line 288 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::jend [private]
Definition at line 226 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::jm [private]
Data y-dimension.
Definition at line 143 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::js [private]
Definition at line 287 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::jsd [private]
Definition at line 288 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::k_breed = 0 [private]
Definition at line 160 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::k_trop = 0 [private]
Definition at line 161 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::kbot_q = 0 [private]
Definition at line 238 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::kbot_t = 0 [private]
Definition at line 237 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::kbot_winds = 0 [private]
Definition at line 236 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::km [private]
Data z-dimension.
Definition at line 144 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::kord_data = 8 [private]
Definition at line 191 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::kstart = 2 [private]
Definition at line 233 of file fv_nudge.F90.
real, dimension(:), allocatable fv_nwp_nudge_mod::lat [private]
Definition at line 146 of file fv_nudge.F90.
real, dimension(:), allocatable fv_nwp_nudge_mod::lon [private]
Definition at line 146 of file fv_nudge.F90.
real fv_nwp_nudge_mod::mask_fac = 0.25 [private]
[0,1] 0: no mask; 1: full strength
Definition at line 193 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::master [private]
Definition at line 149 of file fv_nudge.F90.
integer, parameter fv_nwp_nudge_mod::max_storm = 140 [private]
max # of storms to process
Definition at line 269 of file fv_nudge.F90.
real fv_nwp_nudge_mod::min_mslp = 1009.E2 [private]
Definition at line 275 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::min_nobs = 16 [private]
Definition at line 274 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::module_is_initialized = .false. [private]
Definition at line 148 of file fv_nudge.F90.
real(kind=4), dimension(nobs_max,max_storm) fv_nwp_nudge_mod::mslp_obs [private]
observed SLP in mb
Definition at line 279 of file fv_nudge.F90.
real(kind=4), dimension(nobs_max,max_storm) fv_nwp_nudge_mod::mslp_out [private]
outer ring SLP in mb
Definition at line 280 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::nf_ht = 1 [private]
Definition at line 230 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::nf_ps = 0 [private]
Definition at line 228 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::nf_t = 2 [private]
Definition at line 229 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::nf_uv = 0 [private]
Definition at line 227 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::nfile [private]
Definition at line 158 of file fv_nudge.F90.
integer, parameter fv_nwp_nudge_mod::nfile_max = 29280 [private]
maximum: 20-year analysis data, 4*366*20=29280
Definition at line 156 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::nfile_total = 0 [private]
=5 for 1-day (if datasets are 6-hr apart)
Definition at line 189 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::no_obs [private]
Definition at line 150 of file fv_nudge.F90.
integer, parameter fv_nwp_nudge_mod::nobs_max = 125 [private]
Max # of observations per storm.
Definition at line 270 of file fv_nudge.F90.
integer, dimension(max_storm) fv_nwp_nudge_mod::nobs_tc [private]
Definition at line 273 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::nstorms = 0 [private]
Definition at line 272 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::nudge_debug = .false. [private]
Definition at line 204 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::nudge_hght = .true. [private]
Definition at line 210 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::nudge_ps = .false. [private]
Definition at line 206 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::nudge_q = .false. [private]
Definition at line 207 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::nudge_virt = .true. [private]
Definition at line 209 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::nudge_winds = .true. [private]
Definition at line 208 of file fv_nudge.F90.
real fv_nwp_nudge_mod::nudged_time = 1.E12 [private]
seconds
Definition at line 264 of file fv_nudge.F90.
real fv_nwp_nudge_mod::p_norelax = 0.0 [private]
from P_norelax upwards, no nudging
Definition at line 184 of file fv_nudge.F90.
real fv_nwp_nudge_mod::p_relax = 30.E2 [private]
from P_relax upwards, nudging is reduced linearly proportional to pfull/P_relax
Definition at line 181 of file fv_nudge.F90.
real fv_nwp_nudge_mod::p_trop = 950.E2 [private]
Definition at line 162 of file fv_nudge.F90.
real fv_nwp_nudge_mod::p_wvp = 100.E2 [private]
cutoff level for specific humidity nudging
Definition at line 190 of file fv_nudge.F90.
real fv_nwp_nudge_mod::pre0_env = 100000. [private]
critical storm environment pressure (pa) for size computation
Definition at line 253 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::print_end_breed = .true. [private]
Definition at line 212 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::print_end_nudge = .true. [private]
Definition at line 213 of file fv_nudge.F90.
real, dimension(:,:,:), allocatable fv_nwp_nudge_mod::ps_dat [private]
Definition at line 168 of file fv_nudge.F90.
real fv_nwp_nudge_mod::pt_lim = 0.2 [private]
Definition at line 251 of file fv_nudge.F90.
real(kind=4), dimension(:,:,:,:), allocatable fv_nwp_nudge_mod::q_dat [private]
Definition at line 169 of file fv_nudge.F90.
real fv_nwp_nudge_mod::q_min = 1.E-8 [private]
Definition at line 224 of file fv_nudge.F90.
real fv_nwp_nudge_mod::r_fac = 1.2 [private]
Definition at line 259 of file fv_nudge.F90.
real fv_nwp_nudge_mod::r_hi = 5.0 [private]
Definition at line 257 of file fv_nudge.F90.
real fv_nwp_nudge_mod::r_inc = 25.E3 [private]
Definition at line 261 of file fv_nudge.F90.
real fv_nwp_nudge_mod::r_lo = 2.0 [private]
Definition at line 256 of file fv_nudge.F90.
real fv_nwp_nudge_mod::r_min = 200.E3 [private]
Definition at line 260 of file fv_nudge.F90.
real fv_nwp_nudge_mod::rad2deg [private]
Definition at line 151 of file fv_nudge.F90.
real(kind=4), dimension(nobs_max,max_storm) fv_nwp_nudge_mod::rad_out [private]
outer ring radius in meters
Definition at line 281 of file fv_nudge.F90.
real(kind=r_grid), parameter fv_nwp_nudge_mod::radius = cnst_radius [private]
Definition at line 132 of file fv_nudge.F90.
real, dimension(:,:,:), allocatable fv_nwp_nudge_mod::s2c [private]
Definition at line 166 of file fv_nudge.F90.
real fv_nwp_nudge_mod::slp_env = 101010. [private]
storm environment pressure (pa)
Definition at line 252 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::strong_mask = .false. [private]
Definition at line 202 of file fv_nudge.F90.
real(kind=4), dimension(:,:,:,:), allocatable fv_nwp_nudge_mod::t_dat [private]
Definition at line 169 of file fv_nudge.F90.
logical, public fv_nwp_nudge_mod::t_is_tv = .false.
Definition at line 195 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_hght = 43200. [private]
Definition at line 222 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_ps = 21600. [private]
1-day
Definition at line 218 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_q = 86400. [private]
1-day
Definition at line 219 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_virt = 43200. [private]
Definition at line 221 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_vt_rad = 4.0 [private]
Definition at line 249 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_vt_slp = 1200. [private]
Definition at line 247 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_vt_wind = 1200. [private]
Definition at line 248 of file fv_nudge.F90.
real fv_nwp_nudge_mod::tau_winds = 21600. [private]
6-hr
Definition at line 220 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::tc_mask = .false. [private]
Definition at line 201 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::time_interval = 6*3600 [private]
dataset time interval (seconds)
Definition at line 153 of file fv_nudge.F90.
real fv_nwp_nudge_mod::time_nudge = 0. [private]
Definition at line 152 of file fv_nudge.F90.
real(kind=4), dimension(nobs_max,max_storm) fv_nwp_nudge_mod::time_tc [private]
start time of the track
Definition at line 282 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::time_varying = .true. [private]
Definition at line 211 of file fv_nudge.F90.
real, parameter fv_nwp_nudge_mod::tm_max = 315. [private]
Definition at line 254 of file fv_nudge.F90.
character(len=128) fv_nwp_nudge_mod::track_file_name [private]
Definition at line 188 of file fv_nudge.F90.
real(kind=4), dimension(:,:,:,:), allocatable fv_nwp_nudge_mod::u_dat [private]
Definition at line 169 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::use_high_top = .false. [private]
Definition at line 197 of file fv_nudge.F90.
logical fv_nwp_nudge_mod::use_pt_inc = .false. [private]
Definition at line 196 of file fv_nudge.F90.
real(kind=4), dimension(:,:,:,:), allocatable fv_nwp_nudge_mod::v_dat [private]
Definition at line 169 of file fv_nudge.F90.
real(kind=4), dimension(nobs_max,max_storm) fv_nwp_nudge_mod::wind_obs [private]
observed 10-m wind speed (m/s)
Definition at line 278 of file fv_nudge.F90.
real(kind=4), dimension(nobs_max,max_storm) fv_nwp_nudge_mod::x_obs [private]
longitude in degrees
Definition at line 276 of file fv_nudge.F90.
real(kind=4), dimension(nobs_max,max_storm) fv_nwp_nudge_mod::y_obs [private]
latitude in degrees
Definition at line 277 of file fv_nudge.F90.
integer fv_nwp_nudge_mod::year_track_data [private]
Definition at line 268 of file fv_nudge.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_nudge.F90