multi_gases_mod Module Reference
The module 'multi_gases' peforms multi constitutents computations.
Public Member Functions
subroutine, public multi_gases_init (ngas, nwat)
pure real function, public virq (q)
pure real function, public virq_nodq (q)
pure real function, public virq_max (q, qmin)
pure real function, public virq_qpz (q, qpz)
pure real function, public virqd (q)
pure real function, public vicpqd (q)
pure real function, public vicpqd_qpz (q, qpz)
pure real function, public vicvqd (q)
pure real function, public vicvqd_qpz (q, qpz)
Public Attributes
integer, public num_gas
integer, public ind_gas
real, dimension(:), allocatable ri
real, dimension(:), allocatable cpi
real, dimension(:),
*
allocatable, public vir
real, dimension(:),
*
allocatable, public vicp
real, dimension(:),
*
allocatable, public vicv
Private Attributes
integer, private num_wat
integer, private sphum
integer, private sphump1
Detailed Description
The module 'multi_gases' peforms multi constitutents computations.
Author
H.-M. H. Juang, NOAA/NWS/NCEP/EMC
Definition at line 25 of file multi_gases.F90.
Member Function/Subroutine Documentation
subroutine, public multi_gases_mod::multi_gases_init (integer, intent(in) ngas, integer, intent(in) nwat)
Definition at line 69 of file multi_gases.F90.
Referenced by fv_control_mod::run_setup().
pure real function, public multi_gases_mod::vicpqd (real, dimension(num_gas), intent(in) q)
Definition at line 238 of file multi_gases.F90.
Referenced by fv_nwp_nudge_mod::breed_slp_inline(), fv_diagnostics_mod::eqv_pot(), fv_dynamics_mod::fv_dynamics(), fv_sg_mod::fv_subgrid_z(), fv_update_phys_mod::fv_update_phys(), fv_mapz_mod::lagrangian_to_eulerian(), fv_mapz_mod::moist_cp(), nh_utils_mod::nest_halo_nh(), init_hydro_mod::p_var(), fv_nwp_nudge_mod::ps_nudging(), external_ic_mod::remap_xyz(), and fv_diagnostics_mod::rh_calc().
pure real function, public multi_gases_mod::vicpqd_qpz (real, dimension(num_gas), intent(in) q, real, intent(in) qpz)
Definition at line 258 of file multi_gases.F90.
Referenced by fv_cmp_mod::fv_sat_adj(), and fv_sg_mod::neg_adj3().
pure real function, public multi_gases_mod::vicvqd (real, dimension(num_gas), intent(in) q)
Definition at line 279 of file multi_gases.F90.
Referenced by fv_mapz_mod::compute_total_energy(), dyn_core_mod::dyn_core(), fv_sg_mod::fv_subgrid_z(), fv_mapz_mod::lagrangian_to_eulerian(), fv_mapz_mod::moist_cv(), nh_utils_mod::nest_halo_nh(), and fv_diagnostics_mod::nh_total_energy().
pure real function, public multi_gases_mod::vicvqd_qpz (real, dimension(num_gas), intent(in) q, real, intent(in) qpz)
Definition at line 299 of file multi_gases.F90.
Referenced by fv_cmp_mod::fv_sat_adj(), and fv_sg_mod::neg_adj3().
pure real function, public multi_gases_mod::virq (real, dimension(num_gas), intent(in) q)
Definition at line 135 of file multi_gases.F90.
Referenced by atmosphere_mod::adiabatic_init(), atmosphere_mod::atmosphere_get_bottom_layer(), fv_diagnostics_mod::bunkers_vector(), fv_diagnostics_mod::dbzcalc(), fv_diagnostics_mod::eqv_pot(), fv_restart_mod::fill_nested_grid_data(), fv_diagnostics_mod::fv_diag(), fv_dynamics_mod::fv_dynamics(), fv_nggps_diags_mod::fv_nggps_diag(), fv_nwp_nudge_mod::fv_nwp_nudge(), fv_sg_mod::fv_subgrid_z(), atmosphere_mod::get_bottom_mass(), fv_diagnostics_mod::get_height_field(), fv_diagnostics_mod::helicity_relative(), fv_diagnostics_mod::helicity_relative_caps(), fv_mapz_mod::lagrangian_to_eulerian(), fv_sg_mod::neg_adj3(), init_hydro_mod::p_var(), fv_sg_mod::qsmith(), external_ic_mod::remap_scalar(), external_ic_mod::remap_scalar_ec(), external_ic_mod::remap_scalar_nggps(), external_ic_mod::remap_xyz(), fv_mapz_mod::rst_remap(), and fv_diagnostics_mod::updraft_helicity().
pure real function, public multi_gases_mod::virq_max (real, dimension(num_gas), intent(in) q, real, intent(in) qmin)
Definition at line 174 of file multi_gases.F90.
Referenced by atmosphere_mod::atmos_phys_driver_statein().
pure real function, public multi_gases_mod::virq_nodq (real, dimension(num_gas), intent(in) q)
Definition at line 155 of file multi_gases.F90.
pure real function, public multi_gases_mod::virq_qpz (real, dimension(num_gas), intent(in) q, real, intent(in) qpz)
Definition at line 196 of file multi_gases.F90.
Referenced by fv_cmp_mod::fv_sat_adj(), and fv_sg_mod::fv_subgrid_z().
pure real function, public multi_gases_mod::virqd (real, dimension(num_gas), intent(in) q)
Definition at line 218 of file multi_gases.F90.
Referenced by fv_nwp_nudge_mod::breed_slp_inline(), dyn_core_mod::dyn_core(), fv_diagnostics_mod::eqv_pot(), fv_dynamics_mod::fv_dynamics(), fv_sg_mod::fv_subgrid_z(), fv_update_phys_mod::fv_update_phys(), fv_mapz_mod::lagrangian_to_eulerian(), init_hydro_mod::p_var(), fv_nwp_nudge_mod::ps_nudging(), external_ic_mod::remap_xyz(), and fv_diagnostics_mod::rh_calc().
Member Data Documentation
real, dimension(:), allocatable multi_gases_mod::cpi
Definition at line 49 of file multi_gases.F90.
integer, public multi_gases_mod::ind_gas
Definition at line 45 of file multi_gases.F90.
integer, public multi_gases_mod::num_gas
Definition at line 44 of file multi_gases.F90.
integer, private multi_gases_mod::num_wat [private]
Definition at line 46 of file multi_gases.F90.
real, dimension(:), allocatable multi_gases_mod::ri
Definition at line 48 of file multi_gases.F90.
integer, private multi_gases_mod::sphum [private]
Definition at line 47 of file multi_gases.F90.
integer, private multi_gases_mod::sphump1 [private]
Definition at line 47 of file multi_gases.F90.
real, dimension(:), allocatable, public multi_gases_mod::vicp
Definition at line 51 of file multi_gases.F90.
real, dimension(:), allocatable, public multi_gases_mod::vicv
Definition at line 52 of file multi_gases.F90.
real, dimension(:), allocatable, public multi_gases_mod::vir
Definition at line 50 of file multi_gases.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/multi_gases.F90