init_hydro_mod Module Reference
Public Member Functions
subroutine, public p_var (km, ifirst, ilast, jfirst, jlast, ptop, ptop_min, delp, delz, pt, ps, pe, peln, pk, pkz, cappa, q, ng, nq, area, dry_mass, adjust_dry_mass, mountain, moist_phys, hydrostatic, nwat, domain, make_nh)
the subroutine 'p_var' computes auxiliary pressure variables for a hydrostatic state.
subroutine, public hydro_eq (km, is, ie, js, je, ps, hs, drym, delp, ak, bk, pt, delz, area, ng, mountain, hydrostatic, hybrid_z, domain)
The subroutine 'hydro_eq' computes a hydrostatically balanced and isothermal basic state from input heights.
Private Member Functions
subroutine drymadj (km, ifirst, ilast, jfirst, jlast, ng, cappa, ptop, ps, delp, q, nq, area, nwat, dry_mass, adjust_dry_mass, moist_phys, dpd, domain)
Detailed Description
Definition at line 23 of file init_hydro.F90.
Member Function/Subroutine Documentation
subroutine init_hydro_mod::drymadj (integer km, integer ifirst, integer ilast, integer jfirst, integer jlast, integer ng, real, intent(in) cappa, real, intent(in) ptop, real, dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng), intent(inout) ps, real, dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng,km), intent(in) delp, real, dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng,km,nq), intent(in) q, integer nq, real(kind=r_grid), dimension(ifirst-ng:ilast+ng, jfirst-ng:jlast+ng), intent(in) area, integer nwat, real, intent(in) dry_mass, logical, intent(in) adjust_dry_mass, logical, intent(in) moist_phys, real, intent(out) dpd, type(domain2d), intent(in) domain) [private]
Parameters
   ilast Longitude strip
   jlast Latitude strip
in,out ps surface pressure
Definition at line 246 of file init_hydro.F90.
References fv_grid_utils_mod::g_sum().
Referenced by p_var().
subroutine, public init_hydro_mod::hydro_eq (integer, intent(in) km, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(out) ps, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(in) hs, real, intent(in) drym, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(out) delp, real, dimension(km+1), intent(in) ak, real, dimension(km+1), intent(in) bk, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(out) pt, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(inout) delz, real(kind=r_grid), dimension(is-ng:ie+ng,js-ng:je+ng), intent(in) area, integer, intent(in) ng, logical, intent(in) mountain, logical, intent(in) hydrostatic, logical, intent(in) hybrid_z, type(domain2d), intent(in) domain)
The subroutine 'hydro_eq' computes a hydrostatically balanced and isothermal basic state from input heights.
Definition at line 328 of file init_hydro.F90.
References fv_grid_utils_mod::g_sum().
Referenced by test_cases_mod::init_case(), and test_cases_mod::init_double_periodic().
subroutine, public init_hydro_mod::p_var (integer, intent(in) km, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) jfirst, integer, intent(in) jlast, real, intent(in) ptop, real, intent(in) ptop_min, real, dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng, km), intent(inout) delp, real, dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng, km), intent(inout) delz, real, dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng, km), intent(in) pt, real, dimension(ifirst-ng:ilast+ng, jfirst-ng:jlast+ng), intent(out) ps, real, dimension(ifirst-1:ilast+1,km+1,jfirst-1:jlast+1), intent(out) pe, real, dimension(ifirst:ilast, km+1, jfirst:jlast), intent(out) peln, real, dimension(ifirst:ilast, jfirst:jlast, km+1), intent(out) pk, real, dimension(ifirst:ilast, jfirst:jlast, km), intent(out) pkz, real, intent(in) cappa, real, dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng, km, nq), intent(inout) q, integer, intent(in) ng, integer, intent(in) nq, real(kind=r_grid), dimension(ifirst-ng:ilast+ng,jfirst-ng:jlast+ng), intent(in) area, real, intent(in) dry_mass, logical, intent(in) adjust_dry_mass, logical, intent(in) mountain, logical, intent(in) moist_phys, logical, intent(in) hydrostatic, integer, intent(in) nwat, type(domain2d), intent(in) domain, logical, optional make_nh)
the subroutine 'p_var' computes auxiliary pressure variables for a hydrostatic state.
The variables are: surfce, interface, layer-mean pressure, exener function Given (ptop, delp) computes (ps, pk, pe, peln, pkz)
Parameters
in ilast Longitude strip
in jlast Latitude strip
out pe Ghosted Edge pressure
out peln Edge pressure
Definition at line 83 of file init_hydro.F90.
References drymadj(), multi_gases_mod::vicpqd(), multi_gases_mod::virq(), and multi_gases_mod::virqd().
Referenced by fv_nesting_mod::after_twoway_nest_update(), fv_restart_mod::fill_nested_grid_data_end(), fv_restart_mod::fv_restart(), external_ic_mod::get_external_ic(), test_cases_mod::init_case(), and test_cases_mod::init_double_periodic().
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/init_hydro.F90