fv_eta_mod Module Reference
The module 'fv_eta' contains routine to set up the reference (Eulerian) pressure coordinate.
Public Member Functions
subroutine, public set_eta (km, ks, ptop, ak, bk)
This is the version of set_eta used in fvGFS and AM4.
subroutine, public set_external_eta (ak, bk, ptop, ks)
The subroutine 'set_external_eta' sets 'ptop' (model top) and 'ks' (first level of pure pressure coordinates given the coefficients 'ak' and 'bk'.
subroutine, public hybrid_z_dz (km, dz, ztop, s_rate)
subroutine, public get_eta_level (npz, p_s, pf, ph, ak, bk, pscale)
The subroutine 'get_eta_level' returns the interface and layer-mean pressures for reference.
subroutine, public compute_dz (km, ztop, dz)
subroutine, public compute_dz_var (km, ztop, dz)
subroutine, public compute_dz_l32 (km, ztop, dz)
subroutine, public compute_dz_l101 (km, ztop, dz)
subroutine, public set_hybrid_z (is, ie, js, je, ng, km, ztop, dz, rgrav, hs, ze, dz3)
subroutine, public sm1_edge (is, ie, js, je, km, i, j, ze, ntimes)
subroutine, public gw_1d (km, p0, ak, bk, ptop, ztop, pt1)
Private Member Functions
subroutine var_les (km, ak, bk, ptop, ks, pint, s_rate)
subroutine var_gfs (km, ak, bk, ptop, ks, pint, s_rate)
subroutine var_hi (km, ak, bk, ptop, ks, pint, s_rate)
subroutine var_hi2 (km, ak, bk, ptop, ks, pint, s_rate)
subroutine var_dz (km, ak, bk, ptop, ks, pint, s_rate)
subroutine var55_dz (km, ak, bk, ptop, ks, pint, s_rate)
subroutine zflip (q, im, km)
Detailed Description
The module 'fv_eta' contains routine to set up the reference (Eulerian) pressure coordinate.
Definition at line 25 of file fv_eta.F90.
Member Function/Subroutine Documentation
subroutine, public fv_eta_mod::compute_dz (integer, intent(in) km, real, intent(in) ztop, real, dimension(km), intent(out) dz)
Definition at line 2622 of file fv_eta.F90.
subroutine, public fv_eta_mod::compute_dz_l101 (integer, intent(in) km, real, intent(out) ztop, real, dimension(km), intent(out) dz)
Definition at line 2797 of file fv_eta.F90.
Referenced by test_cases_mod::init_double_periodic().
subroutine, public fv_eta_mod::compute_dz_l32 (integer, intent(in) km, real, intent(out) ztop, real, dimension(km), intent(out) dz)
Definition at line 2728 of file fv_eta.F90.
References zflip().
Referenced by fv_restart_mod::fv_restart(), and test_cases_mod::init_case().
subroutine, public fv_eta_mod::compute_dz_var (integer, intent(in) km, real, intent(in) ztop, real, dimension(km), intent(out) dz)
Definition at line 2658 of file fv_eta.F90.
References sm1_edge().
Referenced by fv_restart_mod::fv_restart().
subroutine, public fv_eta_mod::get_eta_level (integer, intent(in) npz, real, intent(in) p_s, real, dimension(npz), intent(out) pf, real, dimension(npz+1), intent(out) ph, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, intent(in), optional pscale)
The subroutine 'get_eta_level' returns the interface and layer-mean pressures for reference.
Parameters
in p_s unit: pascal
Definition at line 2587 of file fv_eta.F90.
Referenced by atmosphere_mod::atmosphere_init(), fv_diagnostics_mod::fv_diag_init(), fv_update_phys_mod::fv_update_phys(), and fv_regional_mod::setup_regional_bc().
subroutine, public fv_eta_mod::gw_1d (integer, intent(in) km, real, intent(in) p0, real, dimension(km+1), intent(inout) ak, real, dimension(km+1), intent(inout) bk, real, intent(inout) ptop, real, intent(in) ztop, real, dimension(km), intent(out) pt1)
Definition at line 3014 of file fv_eta.F90.
Referenced by fv_diagnostics_mod::fv_diag(), fv_diagnostics_mod::fv_diag_init(), test_cases_mod::init_case(), and set_eta().
subroutine, public fv_eta_mod::hybrid_z_dz (integer, intent(in) km, real, dimension(km), intent(out) dz, real, intent(in) ztop, real, intent(in) s_rate)
Parameters
in s_rate between [1. 1.1]
Definition at line 2522 of file fv_eta.F90.
References sm1_edge().
Referenced by test_cases_mod::init_case().
subroutine, public fv_eta_mod::set_eta (integer, intent(in) km, integer, intent(out) ks, real, intent(out) ptop, real, dimension(km+1), intent(out) ak, real, dimension(km+1), intent(out) bk)
This is the version of set_eta used in fvGFS and AM4.
Note
01/2018: 'set_eta' is being cleaned up.
Parameters
in km vertical dimension
out ks number of pure p layers
out ptop model top (Pa)
Definition at line 419 of file fv_eta.F90.
References gw_1d(), var_dz(), var_gfs(), and var_hi().
Referenced by external_ic_mod::get_ecmwf_ic(), external_ic_mod::get_nggps_ic(), and fv_grid_utils_mod::grid_utils_init().
subroutine, public fv_eta_mod::set_external_eta (real, dimension(:), intent(in) ak, real, dimension(:), intent(in) bk, real, intent(out) ptop, integer, intent(out) ks)
The subroutine 'set_external_eta' sets 'ptop' (model top) and 'ks' (first level of pure pressure coordinates given the coefficients 'ak' and 'bk'.
Parameters
out ptop model top (Pa)
out ks number of pure p layers
Definition at line 1516 of file fv_eta.F90.
Referenced by fv_io_mod::fv_io_read_restart(), and external_ic_mod::get_nggps_ic().
subroutine, public fv_eta_mod::set_hybrid_z (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ng, integer, intent(in) km, real, intent(in) ztop, real, dimension(km), intent(in) dz, real, intent(in) rgrav, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(in) hs, real, dimension(is:ie,js:je,km+1), intent(inout) ze, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(out), optional dz3)
Parameters
in dz Reference vertical resolution for zs=0
Definition at line 2839 of file fv_eta.F90.
References dyn_core_mod::del2_cubed(), and sm1_edge().
Referenced by fv_restart_mod::fv_restart(), test_cases_mod::init_case(), and test_cases_mod::init_double_periodic().
subroutine, public fv_eta_mod::sm1_edge (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, integer, intent(in) i, integer, intent(in) j, real, dimension(is:ie,js:je,km+1), intent(inout) ze, integer, intent(in) ntimes)
Definition at line 2977 of file fv_eta.F90.
Referenced by compute_dz_var(), hybrid_z_dz(), set_hybrid_z(), var55_dz(), var_dz(), test_cases_mod::var_dz(), var_hi(), var_hi2(), and var_les().
subroutine fv_eta_mod::var55_dz (integer, intent(in) km, real, dimension(km+1), intent(out) ak, real, dimension(km+1), intent(out) bk, real, intent(in) ptop, integer, intent(out) ks, real, intent(inout) pint, real, intent(in) s_rate) [private]
Parameters
in s_rate between [1. 1.1]
Definition at line 2360 of file fv_eta.F90.
References sm1_edge().
subroutine fv_eta_mod::var_dz (integer, intent(in) km, real, dimension(km+1), intent(out) ak, real, dimension(km+1), intent(out) bk, real, intent(in) ptop, integer, intent(out) ks, real, intent(inout) pint, real, intent(in) s_rate) [private]
Parameters
in s_rate between [1. 1.1]
Definition at line 2199 of file fv_eta.F90.
References sm1_edge().
Referenced by test_cases_mod::init_case(), and set_eta().
subroutine fv_eta_mod::var_gfs (integer, intent(in) km, real, dimension(km+1), intent(out) ak, real, dimension(km+1), intent(out) bk, real, intent(in) ptop, integer, intent(out) ks, real, intent(inout) pint, real, intent(in) s_rate) [private]
Parameters
in s_rate between [1. 1.1]
Definition at line 1700 of file fv_eta.F90.
Referenced by set_eta().
subroutine fv_eta_mod::var_hi (integer, intent(in) km, real, dimension(km+1), intent(out) ak, real, dimension(km+1), intent(out) bk, real, intent(in) ptop, integer, intent(out) ks, real, intent(inout) pint, real, intent(in) s_rate) [private]
Parameters
in s_rate between [1. 1.1]
Definition at line 1864 of file fv_eta.F90.
References sm1_edge().
Referenced by set_eta().
subroutine fv_eta_mod::var_hi2 (integer, intent(in) km, real, dimension(km+1), intent(out) ak, real, dimension(km+1), intent(out) bk, real, intent(in) ptop, integer, intent(out) ks, real, intent(inout) pint, real, intent(in) s_rate) [private]
Parameters
in s_rate between [1. 1.1]
Definition at line 2040 of file fv_eta.F90.
References sm1_edge().
subroutine fv_eta_mod::var_les (integer, intent(in) km, real, dimension(km+1), intent(out) ak, real, dimension(km+1), intent(out) bk, real, intent(in) ptop, integer, intent(out) ks, real, intent(inout) pint, real, intent(in) s_rate) [private]
Parameters
in s_rate between [1. 1.1]
Definition at line 1538 of file fv_eta.F90.
References sm1_edge().
subroutine fv_eta_mod::zflip (real, dimension(im,km), intent(inout) q, integer, intent(in) im, integer, intent(in) km) [private]
Definition at line 3076 of file fv_eta.F90.
Referenced by compute_dz_l32().
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_eta.F90