fv_io_mod Module Reference
The module 'fv_io' contains restart facilities for FV core.
Public Member Functions
subroutine, public fv_io_init ()
Initialize the fv core restart facilities.
subroutine, public fv_io_exit
Close the fv core restart facilities.
subroutine, public fv_io_read_restart (fv_domain, Atm)
Write the fv core restart quantities.
subroutine, public fv_io_read_tracers (fv_domain, Atm)
The subroutine 'fv_io_read_tracers' reads in only tracers from restart files.
subroutine, public remap_restart (fv_domain, Atm)
The subroutine 'remap_restart' remaps the model state from remap files to a new set of Eulerian coordinates.
subroutine, public fv_io_register_nudge_restart (Atm)
The subroutine 'fv_io_register_nudge_restart' registers restarts for SST fields used in HiRAM.
subroutine, public fv_io_register_restart (fv_domain, Atm)
The subroutine 'fv_io_register_restart' registers model restart fields.
subroutine, public fv_io_write_restart (Atm, grids_on_this_pe, timestamp)
The subroutine 'fv_io_write_restart' writes restart files.
subroutine, public fv_io_register_restart_bcs (Atm)
The subroutine 'fv_io_register_restart_BCs' registers restarts for nested-grid boundary conditions.
subroutine, public fv_io_register_restart_bcs_nh (Atm)
subroutine, public fv_io_write_bcs (Atm, timestamp)
The subroutine 'fv_io_write_BCs' writes BCs to a restart file.
subroutine, public fv_io_read_bcs (Atm)
The subroutine 'fv_io_read_BCs' reads BCs from a restart file.
Private Member Functions
subroutine register_bcs_2d (Atm, BCfile_ne, BCfile_sw, fname_ne, fname_sw, var_name, var, var_bc, istag, jstag)
subroutine register_bcs_3d (Atm, BCfile_ne, BCfile_sw, fname_ne, fname_sw, var_name, var, var_bc, istag, jstag, mandatory)
Private Attributes
logical module_is_initialized = .FALSE.
integer grid_xtdimid
integer grid_ytdimid
integer haloid
integer pfullid
integer grid_xtstagdimid
integer grid_ytstagdimid
integer oneid
Detailed Description
The module 'fv_io' contains restart facilities for FV core.
This module writes and reads restart files for the FV core. Additionally it provides setup and calls routines necessary to provide a complete restart for the model.
Note
NOTE: Merging in the seasonal forecast initialization code has proven problematic in the past, since many conflicts occur. Leaving this for now --- lmh 10aug15
Definition at line 30 of file fv_io.F90.
Member Function/Subroutine Documentation
subroutine, public fv_io_mod::fv_io_exit ()
Close the fv core restart facilities.
Definition at line 137 of file fv_io.F90.
Referenced by fv_control_mod::fv_end().
subroutine, public fv_io_mod::fv_io_init ()
Initialize the fv core restart facilities.
Definition at line 131 of file fv_io.F90.
Referenced by fv_restart_mod::fv_restart_init().
subroutine, public fv_io_mod::fv_io_read_bcs (type(fv_atmos_type), intent(inout) Atm)
The subroutine 'fv_io_read_BCs' reads BCs from a restart file.
Definition at line 1009 of file fv_io.F90.
Referenced by fv_restart_mod::fv_restart().
subroutine, public fv_io_mod::fv_io_read_restart (type(domain2d), intent(inout) fv_domain, type(fv_atmos_type), dimension(:), intent(inout) Atm)
Write the fv core restart quantities.
Definition at line 143 of file fv_io.F90.
References fv_eta_mod::set_external_eta().
Referenced by fv_restart_mod::fv_restart().
subroutine, public fv_io_mod::fv_io_read_tracers (type(domain2d), intent(inout) fv_domain, type(fv_atmos_type), dimension(:), intent(inout) Atm)
The subroutine 'fv_io_read_tracers' reads in only tracers from restart files.
This subroutine is useful when initializing a cycled or nudged model from an analysis that does not have a whole set of microphysical, aerosol, or chemical tracers
Definition at line 224 of file fv_io.F90.
Referenced by external_ic_mod::get_external_ic().
subroutine, public fv_io_mod::fv_io_register_nudge_restart (type(fv_atmos_type), dimension(:), intent(inout) Atm)
The subroutine 'fv_io_register_nudge_restart' registers restarts for SST fields used in HiRAM.
Note
This option is currently not supported.
Definition at line 447 of file fv_io.F90.
subroutine, public fv_io_mod::fv_io_register_restart (type(domain2d), intent(inout) fv_domain, type(fv_atmos_type), dimension(:), intent(inout) Atm)
The subroutine 'fv_io_register_restart' registers model restart fields.
Definition at line 463 of file fv_io.F90.
Referenced by fv_restart_mod::fv_restart().
subroutine, public fv_io_mod::fv_io_register_restart_bcs (type(fv_atmos_type), intent(inout) Atm)
The subroutine 'fv_io_register_restart_BCs' registers restarts for nested-grid boundary conditions.
Definition at line 909 of file fv_io.F90.
References register_bcs_2d(), and register_bcs_3d().
Referenced by fv_restart_mod::fv_restart().
subroutine, public fv_io_mod::fv_io_register_restart_bcs_nh (type(fv_atmos_type), intent(inout) Atm)
Definition at line 974 of file fv_io.F90.
References register_bcs_3d().
Referenced by fv_restart_mod::fv_restart().
subroutine, public fv_io_mod::fv_io_write_bcs (type(fv_atmos_type), intent(inout) Atm, character(len=*), intent(in), optional timestamp)
The subroutine 'fv_io_write_BCs' writes BCs to a restart file.
Definition at line 998 of file fv_io.F90.
Referenced by fv_restart_mod::fv_restart_end(), and fv_restart_mod::fv_write_restart().
subroutine, public fv_io_mod::fv_io_write_restart (type(fv_atmos_type), dimension(:), intent(inout) Atm, logical, dimension(:), intent(in) grids_on_this_pe, character(len=*), intent(in), optional timestamp)
The subroutine 'fv_io_write_restart' writes restart files.
Definition at line 581 of file fv_io.F90.
Referenced by fv_restart_mod::fv_restart_end(), and fv_restart_mod::fv_write_restart().
subroutine fv_io_mod::register_bcs_2d (type(fv_atmos_type), intent(in) Atm, type(restart_file_type), intent(inout) BCfile_ne, type(restart_file_type), intent(inout) BCfile_sw, character(len=120), intent(in) fname_ne, character(len=120), intent(in) fname_sw, character(len=*), intent(in) var_name, real, dimension(:,:), intent(in), optional var, type(fv_nest_bc_type_3d), intent(in), optional var_bc, integer, intent(in), optional istag, integer, intent(in), optional jstag) [private]
Definition at line 617 of file fv_io.F90.
Referenced by fv_io_register_restart_bcs().
subroutine fv_io_mod::register_bcs_3d (type(fv_atmos_type), intent(in) Atm, type(restart_file_type), intent(inout) BCfile_ne, type(restart_file_type), intent(inout) BCfile_sw, character(len=120), intent(in) fname_ne, character(len=120), intent(in) fname_sw, character(len=*), intent(in) var_name, real, dimension(:,:,:), intent(in), optional var, type(fv_nest_bc_type_3d), intent(in), optional var_bc, integer, intent(in), optional istag, integer, intent(in), optional jstag, logical, intent(in), optional mandatory) [private]
Definition at line 761 of file fv_io.F90.
Referenced by fv_io_register_restart_bcs(), and fv_io_register_restart_bcs_nh().
subroutine, public fv_io_mod::remap_restart (type(domain2d), intent(inout) fv_domain, type(fv_atmos_type), dimension(:), intent(inout) Atm)
The subroutine 'remap_restart' remaps the model state from remap files to a new set of Eulerian coordinates.
Use if npz (run time z-dimension) /= npz_rst (restart z-dimension)
Definition at line 275 of file fv_io.F90.
References fv_mapz_mod::rst_remap().
Referenced by fv_restart_mod::fv_restart().
Member Data Documentation
integer fv_io_mod::grid_xtdimid [private]
Definition at line 124 of file fv_io.F90.
integer fv_io_mod::grid_xtstagdimid [private]
Definition at line 125 of file fv_io.F90.
integer fv_io_mod::grid_ytdimid [private]
Definition at line 124 of file fv_io.F90.
integer fv_io_mod::grid_ytstagdimid [private]
Definition at line 125 of file fv_io.F90.
integer fv_io_mod::haloid [private]
Definition at line 124 of file fv_io.F90.
logical fv_io_mod::module_is_initialized = .FALSE. [private]
Definition at line 121 of file fv_io.F90.
integer fv_io_mod::oneid [private]
Definition at line 125 of file fv_io.F90.
integer fv_io_mod::pfullid [private]
Definition at line 124 of file fv_io.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_io.F90