external_ic_mod Module Reference
The module 'external_ic_mod' contains routines that read in and remap initial conditions.
Public Member Functions
subroutine, public get_external_ic (Atm, fv_domain, cold_start)
subroutine, public get_cubed_sphere_terrain (Atm, fv_domain)
subroutine d2a3d (u, v, ua, va, im, jm, km, lon)
Private Member Functions
subroutine get_nggps_ic (Atm, fv_domain)
The subroutine 'get_nggps_ic' reads in data after it has been preprocessed with NCEP/EMC orography maker and 'global_chgres', and has been horiztontally interpolated to the current cubed-sphere grid.
subroutine get_ncep_ic (Atm, fv_domain, nq)
The subroutine 'get_ncep_ic' reads in the specified NCEP analysis or reanalysis dataset.
subroutine get_ecmwf_ic (Atm, fv_domain)
The subroutine 'get_ecmwf_ic' reads in initial conditions from ECMWF analyses (EXPERIMENTAL: contact Jan-Huey Chen jan-huey.chen@noaa.gov for support)
subroutine get_fv_ic (Atm, fv_domain, nq)
subroutine ncep2fms (im, jm, lon, lat, wk)
subroutine remap_coef (is, ie, js, je, isd, ied, jsd, jed, im, jm, lon, lat, id1, id2, jdc, s2c, agrid)
subroutine remap_scalar (im, jm, km, npz, nq, ncnst, ak0, bk0, psc, gzc, ta, qa, Atm)
subroutine remap_scalar_nggps (Atm, km, npz, ncnst, ak0, bk0, psc, t_in, qa, omga, zh)
subroutine remap_scalar_ec (Atm, km, npz, ncnst, ak0, bk0, psc, qa, wc, zh)
subroutine remap_scalar_single (Atm, km, npz, ak0, bk0, psc, qa, zh, iq)
subroutine mp_auto_conversion (ql, qr, qi, qs)
subroutine remap_dwinds (km, npz, ak0, bk0, psc, ud, vd, Atm)
subroutine remap_winds (im, jm, km, npz, ak0, bk0, psc, ua, va, Atm)
subroutine remap_xyz (im, jbeg, jend, jm, km, npz, nq, ncnst, lon, lat, ak0, bk0, ps0, gz0, ua, va, ta, qa, Atm)
subroutine cubed_a2d (npx, npy, npz, ua, va, u, v, gridstruct, fv_domain, bd)
The subroutine 'cubed_a2d' transforms the wind from the A Grid to the D Grid.
subroutine pmaxmin (qname, a, im, jm, fac)
subroutine pmaxmn (qname, q, is, ie, js, je, km, fac, area, domain)
subroutine p_maxmin (qname, q, is, ie, js, je, km, fac)
subroutine fillq (im, km, nq, q, dp)
subroutine compute_zh (im, jm, levp, ak0, bk0, ps, zs, t, q, nq, zh)
subroutine get_staggered_grid (is, ie, js, je, isd, ied, jsd, jed, pt_b, pt_c, pt_d)
Private Attributes
real, parameter zvir = rvgas/rdgas - 1.
real(kind=r_grid), parameter cnst_0p20 =0.20d0
real deg2rad
character(len=80) source
Detailed Description
The module 'external_ic_mod' contains routines that read in and remap initial conditions.
Definition at line 32 of file external_ic.F90.
Member Function/Subroutine Documentation
subroutine external_ic_mod::compute_zh (integer, intent(in) im, integer, intent(in) jm, integer, intent(in) levp, real, dimension(levp+1), intent(in) ak0, real, dimension(levp+1), intent(in) bk0, real(kind=4), dimension(im,jm), intent(in) ps, real(kind=4), dimension(im,jm), intent(in) zs, real(kind=4), dimension(im,jm,levp), intent(in) t, real(kind=4), dimension(im,jm,levp,nq), intent(in) q, integer, intent(in) nq, real(kind=4), dimension(im,jm,levp+1), intent(out) zh) [private]
Definition at line 4213 of file external_ic.F90.
Referenced by get_ecmwf_ic().
subroutine external_ic_mod::cubed_a2d (integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(inout) ua, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(inout) va, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1,npz), intent(out) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(out) v, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) fv_domain, type(fv_grid_bounds_type), intent(in) bd) [private]
The subroutine 'cubed_a2d' transforms the wind from the A Grid to the D Grid.
Definition at line 3821 of file external_ic.F90.
Referenced by remap_winds(), and remap_xyz().
subroutine external_ic_mod::d2a3d (real, dimension(im,jm,km), intent(in) u, real, dimension(im,jm,km), intent(in) v, real, dimension(im,jm,km), intent(out) ua, real, dimension(im,jm,km), intent(out) va, integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, real, dimension(im), intent(in) lon)
Definition at line 4005 of file external_ic.F90.
Referenced by get_fv_ic().
subroutine external_ic_mod::fillq (integer, intent(in) im, integer, intent(in) km, integer, intent(in) nq, real, dimension(im,km,nq), intent(inout) q, real, dimension(im,km), intent(in) dp) [private]
Parameters
in im No. of longitudes
in km No. of levels
in nq Total number of tracers
in dp pressure thickness
in,out q tracer mixing ratio
Definition at line 4178 of file external_ic.F90.
subroutine, public external_ic_mod::get_cubed_sphere_terrain (type(fv_atmos_type), dimension(:), intent(inout), target Atm, type(domain2d), intent(inout) fv_domain)
Definition at line 371 of file external_ic.F90.
References fv_grid_utils_mod::g_sum(), fv_diagnostics_mod::prt_maxmin(), and fv_surf_map_mod::surfdrv().
Referenced by get_external_ic().
subroutine external_ic_mod::get_ecmwf_ic (type(fv_atmos_type), dimension(:), intent(inout) Atm, type(domain2d), intent(inout) fv_domain) [private]
The subroutine 'get_ecmwf_ic' reads in initial conditions from ECMWF analyses (EXPERIMENTAL: contact Jan-Huey Chen jan-huey.chen@noaa.gov for support)
Authors
Jan-Huey Chen, Xi Chen, Shian-Jiann Lin
Definition at line 1370 of file external_ic.F90.
References compute_zh(), fv_grid_utils_mod::get_latlon_vector(), sim_nc_mod::get_ncdim1(), get_staggered_grid(), fv_grid_utils_mod::get_unit_vect2(), sim_nc_mod::get_var2_r4(), sim_nc_mod::get_var3_r4(), sim_nc_mod::get_var_att_double(), fv_grid_utils_mod::inner_prod(), fv_grid_utils_mod::mid_pt_sphere(), sim_nc_mod::open_ncfile(), remap_coef(), remap_dwinds(), remap_scalar_ec(), remap_scalar_single(), and fv_eta_mod::set_eta().
Referenced by get_external_ic().
subroutine, public external_ic_mod::get_external_ic (type(fv_atmos_type), dimension(:), intent(inout), target Atm, type(domain2d), intent(inout) fv_domain, logical, intent(in) cold_start)
Definition at line 210 of file external_ic.F90.
References fv_io_mod::fv_io_read_tracers(), get_cubed_sphere_terrain(), get_ecmwf_ic(), get_fv_ic(), get_ncep_ic(), get_nggps_ic(), init_hydro_mod::p_var(), fv_diagnostics_mod::prt_maxmin(), fv_timing_mod::timing_off(), and fv_timing_mod::timing_on().
Referenced by fv_restart_mod::fv_restart().
subroutine external_ic_mod::get_fv_ic (type(fv_atmos_type), dimension(:), intent(inout) Atm, type(domain2d), intent(inout) fv_domain, integer, intent(in) nq) [private]
Definition at line 2113 of file external_ic.F90.
References d2a3d(), pmaxmin(), and remap_xyz().
Referenced by get_external_ic().
subroutine external_ic_mod::get_ncep_ic (type(fv_atmos_type), dimension(:), intent(inout) Atm, type(domain2d), intent(inout) fv_domain, integer, intent(in) nq) [private]
The subroutine 'get_ncep_ic' reads in the specified NCEP analysis or reanalysis dataset.
Definition at line 1049 of file external_ic.F90.
References sim_nc_mod::close_ncfile(), sim_nc_mod::get_ncdim1(), sim_nc_mod::get_var2_real(), sim_nc_mod::get_var3_r4(), ncep2fms(), sim_nc_mod::open_ncfile(), pmaxmin(), fv_diagnostics_mod::prt_maxmin(), remap_coef(), remap_scalar(), and remap_winds().
Referenced by get_external_ic().
subroutine external_ic_mod::get_nggps_ic (type(fv_atmos_type), dimension(:), intent(inout) Atm, type(domain2d), intent(inout) fv_domain) [private]
The subroutine 'get_nggps_ic' reads in data after it has been preprocessed with NCEP/EMC orography maker and 'global_chgres', and has been horiztontally interpolated to the current cubed-sphere grid.
Parameters
in,out atm variables read in from 'gfs_ctrl.nc' VCOORD - level information maps to 'ak & bk' variables read in from 'sfc_data.nc' land_frac - land-sea-ice mask (L:0 / S:1) maps to 'oro' TSEA - surface skin temperature (k) maps to 'ts' variables read in from 'gfs_data.nc' ZH - GFS grid height at edges (m) PS - surface pressure (Pa) U_W - D-grid west face tangential wind component (m/s) V_W - D-grid west face normal wind component (m/s) U_S - D-grid south face tangential wind component (m/s) V_S - D-grid south face normal wind component (m/s) OMGA- vertical velocity 'omega' (Pa/s) Q - prognostic tracer fields Namelist variables filtered_terrain - use orography maker filtered terrain mapping
Definition at line 445 of file external_ic.F90.
References test_cases_mod::checker_tracers(), fv_surf_map_mod::del2_cubed_sphere(), fv_surf_map_mod::del4_cubed_sphere(), boundary_mod::extrapolation_bc(), fv_surf_map_mod::fv3_zs_filter(), fv_regional_mod::get_data_source(), fv_grid_utils_mod::get_latlon_vector(), fv_grid_utils_mod::get_unit_vect2(), fv_grid_utils_mod::inner_prod(), fv_grid_utils_mod::mid_pt_sphere(), remap_dwinds(), remap_scalar_nggps(), fv_eta_mod::set_eta(), fv_eta_mod::set_external_eta(), and fv_regional_mod::start_regional_cold_start().
Referenced by get_external_ic().
subroutine external_ic_mod::get_staggered_grid (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, dimension(isd:ied+1,jsd:jed+1,2), intent(in) pt_b, real, dimension(isd:ied+1,jsd:jed ,2), intent(out) pt_c, real, dimension(isd:ied ,jsd:jed+1,2), intent(out) pt_d) [private]
Definition at line 4255 of file external_ic.F90.
References fv_grid_utils_mod::mid_pt_sphere().
Referenced by get_ecmwf_ic(), and fv_treat_da_inc_mod::read_da_inc().
subroutine external_ic_mod::mp_auto_conversion (real, intent(inout) ql, real, intent(inout) qr, real, intent(inout) qi, real, intent(inout) qs) [private]
Definition at line 3345 of file external_ic.F90.
subroutine external_ic_mod::ncep2fms (integer, intent(in) im, integer, intent(in) jm, real, dimension(im), intent(in) lon, real, dimension(jm), intent(in) lat, real(kind=4), dimension(im,jm), intent(in) wk) [private]
Definition at line 2258 of file external_ic.F90.
Referenced by fv_nwp_nudge_mod::get_ncep_analysis(), and get_ncep_ic().
subroutine external_ic_mod::p_maxmin (character(len=*), intent(in) qname, real, dimension(is:ie, js:je, km), intent(in) q, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, real, intent(in) fac) [private]
Definition at line 4151 of file external_ic.F90.
subroutine external_ic_mod::pmaxmin (character(len=*) qname, real, dimension(im,jm) a, integer, intent(in) im, integer, intent(in) jm, real fac) [private]
Definition at line 4080 of file external_ic.F90.
Referenced by get_fv_ic(), fv_nwp_nudge_mod::get_ncep_analysis(), and get_ncep_ic().
subroutine external_ic_mod::pmaxmn (character(len=*), intent(in) qname, real, dimension(is:ie, js:je, km), intent(in) q, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, real, intent(in) fac, real(kind=r_grid), dimension(is-3:ie+3, js-3:je+3), intent(in) area, type(domain2d), intent(inout) domain) [private]
Definition at line 4115 of file external_ic.F90.
References fv_grid_utils_mod::g_sum().
subroutine external_ic_mod::remap_coef (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) im, integer, intent(in) jm, real, dimension(im), intent(in) lon, real, dimension(jm), intent(in) lat, integer, dimension(is:ie,js:je), intent(out) id1, integer, dimension(is:ie,js:je), intent(out) id2, integer, dimension(is:ie,js:je), intent(out) jdc, real, dimension(is:ie,js:je,4), intent(out) s2c, real, dimension(isd:ied,jsd:jed,2), intent(in) agrid) [private]
Definition at line 2349 of file external_ic.F90.
Referenced by fv_nwp_nudge_mod::fv_nwp_nudge_init(), get_ecmwf_ic(), get_ncep_ic(), fv_iau_mod::iau_initialize(), and fv_treat_da_inc_mod::read_da_inc().
subroutine external_ic_mod::remap_dwinds (integer, intent(in) km, integer, intent(in) npz, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je), intent(in) psc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je+1,km), intent(in) ud, real, dimension(atm%bd%is:atm%bd%ie+1,atm%bd%js:atm%bd%je,km), intent(in) vd, type(fv_atmos_type), intent(inout) Atm) [private]
Definition at line 3364 of file external_ic.F90.
References fv_mapz_mod::mappm().
Referenced by get_ecmwf_ic(), and get_nggps_ic().
subroutine external_ic_mod::remap_scalar (integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, integer, intent(in) npz, integer, intent(in) nq, integer, intent(in) ncnst, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je), intent(in) psc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je), intent(in) gzc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km), intent(in) ta, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km,ncnst), intent(in) qa, type(fv_atmos_type), intent(inout) Atm) [private]
Definition at line 2429 of file external_ic.F90.
References fv_mapz_mod::mappm(), fv_diagnostics_mod::prt_maxmin(), and multi_gases_mod::virq().
Referenced by get_ncep_ic().
subroutine external_ic_mod::remap_scalar_ec (type(fv_atmos_type), intent(inout) Atm, integer, intent(in) km, integer, intent(in) npz, integer, intent(in) ncnst, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je), intent(in) psc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km,ncnst), intent(in) qa, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km), intent(in) wc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km+1), intent(in) zh) [private]
Definition at line 2969 of file external_ic.F90.
References fv_regional_mod::fillq(), fv_fill_mod::fillz(), fv_mapz_mod::mappm(), fv_regional_mod::p_maxmin(), fv_regional_mod::pmaxmn(), fv_diagnostics_mod::prt_gb_nh_sh(), fv_diagnostics_mod::prt_height(), and multi_gases_mod::virq().
Referenced by get_ecmwf_ic().
subroutine external_ic_mod::remap_scalar_nggps (type(fv_atmos_type), intent(inout) Atm, integer, intent(in) km, integer, intent(in) npz, integer, intent(in) ncnst, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je), intent(in) psc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km), intent(in) t_in, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km,ncnst), intent(in) qa, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km), intent(in) omga, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km+1), intent(in) zh) [private]
Definition at line 2607 of file external_ic.F90.
References fv_regional_mod::fillq(), fv_fill_mod::fillz(), fv_mapz_mod::mappm(), fv_regional_mod::mp_auto_conversion(), fv_regional_mod::p_maxmin(), fv_regional_mod::pmaxmn(), fv_diagnostics_mod::prt_gb_nh_sh(), fv_diagnostics_mod::prt_height(), and multi_gases_mod::virq().
Referenced by get_nggps_ic().
subroutine external_ic_mod::remap_scalar_single (type(fv_atmos_type), intent(inout) Atm, integer, intent(in) km, integer, intent(in) npz, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je), intent(in) psc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km), intent(in) qa, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km+1), intent(in) zh, integer, intent(in) iq) [private]
Definition at line 3237 of file external_ic.F90.
References fv_regional_mod::fillq(), fv_fill_mod::fillz(), fv_mapz_mod::mappm(), and fv_regional_mod::p_maxmin().
Referenced by get_ecmwf_ic().
subroutine external_ic_mod::remap_winds (integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, integer, intent(in) npz, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je), intent(in) psc, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km), intent(in) ua, real, dimension(atm%bd%is:atm%bd%ie,atm%bd%js:atm%bd%je,km), intent(in) va, type(fv_atmos_type), intent(inout) Atm) [private]
Definition at line 3460 of file external_ic.F90.
References cubed_a2d(), fv_mapz_mod::mappm(), and fv_diagnostics_mod::prt_maxmin().
Referenced by get_ncep_ic().
subroutine external_ic_mod::remap_xyz (integer, intent(in) im, integer, intent(in) jbeg, integer, intent(in) jend, integer, intent(in) jm, integer, intent(in) km, integer, intent(in) npz, integer, intent(in) nq, integer, intent(in) ncnst, real, dimension(im), intent(in) lon, real, dimension(jm), intent(in) lat, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(im,jbeg:jend), intent(in) ps0, real, dimension(im,jbeg:jend), intent(in) gz0, real, dimension(im,jbeg:jend,km), intent(in) ua, real, dimension(im,jbeg:jend,km), intent(in) va, real, dimension(im,jbeg:jend,km), intent(in) ta, real, dimension(im,jbeg:jend,km,ncnst), intent(in) qa, type(fv_atmos_type), intent(inout), target Atm) [private]
Definition at line 3534 of file external_ic.F90.
References cubed_a2d(), fv_mapz_mod::mappm(), fv_diagnostics_mod::prt_maxmin(), multi_gases_mod::vicpqd(), multi_gases_mod::virq(), and multi_gases_mod::virqd().
Referenced by get_fv_ic().
Member Data Documentation
real(kind=r_grid), parameter external_ic_mod::cnst_0p20 =0.20d0 [private]
Definition at line 199 of file external_ic.F90.
real external_ic_mod::deg2rad [private]
Definition at line 200 of file external_ic.F90.
character (len = 80) external_ic_mod::source [private]
Definition at line 201 of file external_ic.F90.
real, parameter external_ic_mod::zvir = rvgas/rdgas - 1. [private]
Definition at line 198 of file external_ic.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/external_ic.F90