dycore_typedefs Module Reference
Data Types
type dycore_coupling_type
type dycore_data_type
type dycore_diag_type
type var_subtype
Public Member Functions
subroutine coupling_create (Coupling, IM, Ntracers)
subroutine diag_create (Diag, IM, Ntracers)
subroutine diag_zero (Diag)
Public Attributes
real(kind=r8_kind), parameter zero = 0.0_r8_kind
real(kind=r8_kind), parameter huge = 9.9999D15
real(kind=r8_kind), parameter clear_val = zero
Detailed Description
Definition at line 21 of file DYCORE_typedefs.F90.
Member Function/Subroutine Documentation
subroutine dycore_typedefs::coupling_create (class(dycore_coupling_type) Coupling, integer, intent(in) IM, integer, intent(in) Ntracers)
Definition at line 111 of file DYCORE_typedefs.F90.
Referenced by dycore_typedefs::dycore_coupling_type::create().
subroutine dycore_typedefs::diag_create (class(dycore_diag_type) Diag, integer, intent(in) IM, integer, intent(in) Ntracers)
Definition at line 148 of file DYCORE_typedefs.F90.
Referenced by dycore_typedefs::dycore_diag_type::create().
subroutine dycore_typedefs::diag_zero (class(dycore_diag_type) Diag)
Definition at line 161 of file DYCORE_typedefs.F90.
Referenced by dycore_typedefs::dycore_diag_type::zero().
Member Data Documentation
real(kind=r8_kind), parameter dycore_typedefs::clear_val = zero
Definition at line 30 of file DYCORE_typedefs.F90.
real(kind=r8_kind), parameter dycore_typedefs::huge = 9.9999D15
Definition at line 29 of file DYCORE_typedefs.F90.
real(kind=r8_kind), parameter dycore_typedefs::zero = 0.0_r8_kind
Definition at line 28 of file DYCORE_typedefs.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/driver/fvGFS/DYCORE_typedefs.F90