fv_treat_da_inc_mod Module Reference
'The module 'tread_da_increment' contains routines for treating the increments of the prognostic variables that are calculated by the DA process
Public Member Functions
subroutine, public read_da_inc (Atm, fv_domain)
The subroutine 'read_da_inc' reads the increments of the diagnostic variables from the DA-generated files.
subroutine, public remap_coef (is, ie, js, je, im, jm, lon, lat, id1, id2, jdc, s2c, agrid)
The subroutine 'remap_coef' calculates the coefficients for horizonal regridding.
Private Member Functions
subroutine get_staggered_grid (is, ie, js, je, isd, ied, jsd, jed, pt_b, pt_c, pt_d)
The subroutine 'get_staggered_grid' gets the lat-lon locations of the staggered points.
Detailed Description
'The module 'tread_da_increment' contains routines for treating the increments of the prognostic variables that are calculated by the DA process
This module includes functions to read in the externally calculated increments and applies the increments to the restart variables. Specifically, if the increments are zero, FV3 should reproduce directly from the restart files.
Note
Please treat the following subroutines as API interfaces, and consult the FV3 team code modification proposal.
Warning
Expanding the list of increments without the proper knowledge of the FV3 dynamical core is EXTREMELY RISKY, especially for the non-hydrostatic scenario. Such a modification could break the scientific consistency, possibly leading to a simulation crash.
Author
Xi.Chen xi.chen@noaa.gov
Date
02/12/2016
Definition at line 46 of file fv_treat_da_inc.F90.
Member Function/Subroutine Documentation
subroutine fv_treat_da_inc_mod::get_staggered_grid (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, dimension(isd:ied+1,jsd:jed+1,2), intent(in) pt_b, real, dimension(is:ie+1,js:je ,2), intent(out) pt_c, real, dimension(is:ie ,js:je+1,2), intent(out) pt_d) [private]
The subroutine 'get_staggered_grid' gets the lat-lon locations of the staggered points.
Definition at line 544 of file fv_treat_da_inc.F90.
References fv_grid_utils_mod::mid_pt_sphere().
subroutine, public fv_treat_da_inc_mod::read_da_inc (type(fv_atmos_type), dimension(:), intent(inout) Atm, type(domain2d), intent(inout) fv_domain)
The subroutine 'read_da_inc' reads the increments of the diagnostic variables from the DA-generated files.
Additional support of prognostic variables such as tracers can be assessed and added upon request.
Author
Xi.Chen xi.chen@noaa.gov
Date
02/12/2016
Definition at line 159 of file fv_treat_da_inc.F90.
References apply_inc_on_3d_scalar(), fv_grid_utils_mod::get_latlon_vector(), sim_nc_mod::get_ncdim1(), external_ic_mod::get_staggered_grid(), fv_grid_utils_mod::get_unit_vect2(), sim_nc_mod::get_var3_r4(), fv_grid_utils_mod::inner_prod(), fv_grid_utils_mod::mid_pt_sphere(), sim_nc_mod::open_ncfile(), and external_ic_mod::remap_coef().
Referenced by fv_restart_mod::fv_restart().
subroutine, public fv_treat_da_inc_mod::remap_coef (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) im, integer, intent(in) jm, real, dimension(im), intent(in) lon, real, dimension(jm), intent(in) lat, integer, dimension(is:ie,js:je), intent(out) id1, integer, dimension(is:ie,js:je), intent(out) id2, integer, dimension(is:ie,js:je), intent(out) jdc, real, dimension(is:ie,js:je,4), intent(out) s2c, real, dimension(is:ie,js:je,2), intent(in) agrid)
The subroutine 'remap_coef' calculates the coefficients for horizonal regridding.
Definition at line 463 of file fv_treat_da_inc.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_treat_da_inc.F90