sorted_index_mod Module Reference
The module 'sorted_index' sorts cell corner indices in lat-lon space to ensure the same order of operations regardless of the orientation in index space.
Public Member Functions
subroutine, public sorted_inta (isd, ied, jsd, jed, cubed_sphere, bgrid, iinta, jinta)
The subroutine 'sorted_inta' sorts cell corner indices in latlon space based on grid locations in index space..
subroutine, public sorted_intb (isd, ied, jsd, jed, is, ie, js, je, npx, npy, cubed_sphere, agrid, iintb, jintb)
The subroutine 'sorted_intb' sorts cell corner indices in latlon space based on grid locations in index space.
Detailed Description
The module 'sorted_index' sorts cell corner indices in lat-lon space to ensure the same order of operations regardless of the orientation in index space.
i/jinta are indices of b-grid locations needed for line integrals around an a-grid cell including ghosting. i/jintb are indices of a-grid locations needed for line integrals around a b-grid cell with no ghosting.
Definition at line 28 of file sorted_index.F90.
Member Function/Subroutine Documentation
subroutine, public sorted_index_mod::sorted_inta (integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, logical, intent(in) cubed_sphere, real(kind=r_grid), dimension(isd:ied+1,jsd:jed+1,2), intent(in) bgrid, integer, dimension(4,isd:ied,jsd:jed), intent(out) iinta, integer, dimension(4,isd:ied,jsd:jed), intent(out) jinta)
The subroutine 'sorted_inta' sorts cell corner indices in latlon space based on grid locations in index space..
If not the grid is notcubed_sphere, it assumes that the orientations in index and latlon space are identical. i/jinta are indices of b-grid locations needed for line integrals around an a-grid cell including ghosting. i/jintb are indices of a-grid locations needed for line integrals around a b-grid cell, no ghosting.
Definition at line 46 of file sorted_index.F90.
References sort_rectangle().
Referenced by fv_grid_tools_mod::init_grid().
subroutine, public sorted_index_mod::sorted_intb (integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) npx, integer, intent(in) npy, logical, intent(in) cubed_sphere, real(kind=r_grid), dimension(isd:ied,jsd:jed,2), intent(in) agrid, integer, dimension(4,is:ie+1,js:je+1), intent(out) iintb, integer, dimension(4,is:ie+1,js:je+1), intent(out) jintb)
The subroutine 'sorted_intb' sorts cell corner indices in latlon space based on grid locations in index space.
If not the grid is notcubed_sphere, it assumes that the orientations in index and latlon space are identical. i/jinta are indices of b-grid locations needed for line integrals around an a-grid cell including ghosting. i/jintb are indices of a-grid locations needed for line integrals around a b-grid cell, no ghosting.
Definition at line 233 of file sorted_index.F90.
References sort_rectangle(), and sort_triangle().
Referenced by fv_grid_tools_mod::init_grid().
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/sorted_index.F90