fv_nggps_diags_mod Module Reference
The module 'fv_nggps_diags' computes output diagnostics entirely on 3D pressure levels.
Public Member Functions
subroutine, public fv_nggps_diag_init (Atm, axes, Time)
subroutine, public fv_nggps_diag (Atm, zvir, Time)
subroutine, public fv_nggps_tavg (Atm, Time_step_atmos, avg_max_length, zvir)
Private Member Functions
subroutine store_data (id, work, Time, nstt, nend)
Private Attributes
real, parameter missing_value = -1.e10
real, parameter stndrd_atmos_ps = 101325.
real, parameter stndrd_atmos_lapse = 0.0065
logical master
integer id_ua
integer id_va
integer id_pt
integer id_delp
integer id_pfhy
integer id_pfnh
integer id_w
integer id_delz
integer id_diss
integer id_ps
integer id_hs
integer id_dbz
integer id_omga
integer kstt_ua
integer kstt_va
integer kstt_pt
integer kstt_delp
integer kstt_pfhy
integer kstt_pfnh
integer kstt_w
integer kstt_delz
integer kstt_diss
integer kstt_ps
integer kstt_hs
integer kend_ua
integer kend_va
integer kend_pt
integer kend_delp
integer kend_pfhy
integer kend_pfnh
integer kend_w
integer kend_delz
integer kend_diss
integer kend_ps
integer kend_hs
integer kstt_dbz
integer kend_dbz
integer kstt_omga
integer kend_omga
integer kstt_windvect
integer kend_windvect
integer id_wmaxup
integer id_wmaxdn
integer kstt_wup
integer kend_wup
integer kstt_wdn
integer kend_wdn
integer id_uhmax03
integer id_uhmin03
integer id_uhmax25
integer id_uhmin25
integer id_maxvort01
integer id_maxvorthy1
integer kstt_maxvorthy1
integer kstt_maxvort01
integer id_ustm
integer kend_maxvorthy1
integer kend_maxvort01
integer id_vstm
integer id_srh01
integer id_srh03
integer kstt_uhmax03
integer kstt_uhmin03
integer kend_uhmax03
integer kend_uhmin03
integer kstt_uhmax25
integer kstt_uhmin25
integer kend_uhmax25
integer kend_uhmin25
integer kstt_ustm
integer kstt_vstm
integer kend_ustm
integer kend_vstm
integer kstt_srh01
integer kstt_srh03
integer kend_srh01
integer kend_srh03
integer id_maxvort02
integer kstt_maxvort02
integer kend_maxvort02
integer isco
integer ieco
integer jsco
integer jeco
integer npzo
integer ncnsto
integer isdo
integer iedo
integer jsdo
integer jedo
integer nlevs
logical hydrostatico
integer, dimension(:), allocatable id_tracer
integer, dimension(:), allocatable all_axes
integer, dimension(:), allocatable kstt_tracer
integer, dimension(:), allocatable kend_tracer
real, dimension(:), allocatable ak
real, dimension(:), allocatable bk
character(20), dimension(:),
*
allocatable axis_name
character(20), dimension(:),
*
allocatable axis_name_vert
logical module_is_initialized =.false.
logical use_wrtgridcomp_output =.false.
integer sphum
integer liq_wat
integer ice_wat
GFDL physics.
integer rainwat
integer snowwat
integer graupel
real, dimension(2) vrange = (/ -330., 330. /)
winds
real, dimension(2) wrange = (/ -100., 100. /)
vertical wind
real, dimension(2) trange = (/ 100., 350. /)
temperature
real, dimension(2) skrange = (/ -10000000.0, 10000000.0 /)
dissipation estimate for SKEB
character(len=64) file_name = 'gfs_dyn'
character(len=128) tname
character(len=256) tlongname
character(len=256) tunits
real(4), dimension(:,:,:),
*
allocatable, target buffer_dyn
real(4), dimension(:,:,:,:),
*
allocatable, target windvect
real(4), dimension(:,:),
*
allocatable, target psurf
real, dimension(:,:), allocatable lon
real, dimension(:,:), allocatable lat
real, dimension(:,:), allocatable up2
real, dimension(:,:), allocatable dn2
real, dimension(:,:), allocatable uhmax03
real, dimension(:,:), allocatable uhmin03
real, dimension(:,:), allocatable uhmax25
real, dimension(:,:), allocatable uhmin25
real, dimension(:,:), allocatable maxvort01
real, dimension(:,:), allocatable maxvorthy1
real, dimension(:,:), allocatable maxvort02
Detailed Description
The module 'fv_nggps_diags' computes output diagnostics entirely on 3D pressure levels.
The module is designed for applications that process the full 3D fields through the NCEP post-processor.
Definition at line 28 of file fv_nggps_diag.F90.
Member Function/Subroutine Documentation
subroutine, public fv_nggps_diags_mod::fv_nggps_diag (type(fv_atmos_type), dimension(:), intent(inout) Atm, real, intent(in) zvir, type(time_type), intent(in) Time)
Definition at line 435 of file fv_nggps_diag.F90.
References fv_diagnostics_mod::bunkers_vector(), fv_diagnostics_mod::dbzcalc(), fv_diagnostics_mod::helicity_relative_caps(), fv_diagnostics_mod::range_check(), store_data(), and multi_gases_mod::virq().
Referenced by atmosphere_mod::atmosphere_end(), and atmosphere_mod::atmosphere_nggps_diag().
subroutine, public fv_nggps_diags_mod::fv_nggps_diag_init (type(fv_atmos_type), dimension(:), intent(inout), target Atm, integer, dimension(4), intent(in) axes, type(time_type), intent(in) Time)
Definition at line 153 of file fv_nggps_diag.F90.
Referenced by atmosphere_mod::atmosphere_nggps_diag().
subroutine, public fv_nggps_diags_mod::fv_nggps_tavg (type(fv_atmos_type), dimension(:), intent(inout) Atm, type(time_type), intent(in) Time_step_atmos, real avg_max_length, real, intent(in) zvir)
Definition at line 736 of file fv_nggps_diag.F90.
References fv_diagnostics_mod::get_vorticity(), fv_diagnostics_mod::max_uh(), fv_diagnostics_mod::max_vorticity(), fv_diagnostics_mod::max_vorticity_hy1(), and fv_diagnostics_mod::max_vv().
Referenced by atmosphere_mod::atmosphere_nggps_diag().
subroutine fv_nggps_diags_mod::store_data (integer, intent(in) id, real, dimension(isco:ieco,jsco:jeco,nend-nstt+1), intent(in) work, type(time_type), intent(in) Time, integer, intent(in) nstt, integer, intent(in) nend) [private]
Definition at line 832 of file fv_nggps_diag.F90.
Referenced by fv_nggps_diag().
Member Data Documentation
real, dimension(:), allocatable fv_nggps_diags_mod::ak [private]
Definition at line 119 of file fv_nggps_diag.F90.
integer, dimension(:), allocatable fv_nggps_diags_mod::all_axes [private]
Definition at line 117 of file fv_nggps_diag.F90.
character(20), dimension(:), allocatable fv_nggps_diags_mod::axis_name [private]
Definition at line 120 of file fv_nggps_diag.F90.
character(20), dimension(:), allocatable fv_nggps_diags_mod::axis_name_vert [private]
Definition at line 120 of file fv_nggps_diag.F90.
real, dimension(:), allocatable fv_nggps_diags_mod::bk [private]
Definition at line 119 of file fv_nggps_diag.F90.
real(4), dimension(:,:,:), allocatable, target fv_nggps_diags_mod::buffer_dyn [private]
Definition at line 139 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::dn2 [private]
Definition at line 143 of file fv_nggps_diag.F90.
character(len=64) fv_nggps_diags_mod::file_name = 'gfs_dyn' [private]
Definition at line 132 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::graupel [private]
Definition at line 125 of file fv_nggps_diag.F90.
logical fv_nggps_diags_mod::hydrostatico [private]
Definition at line 116 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::ice_wat [private]
GFDL physics.
Definition at line 124 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_dbz [private]
Definition at line 97 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_delp [private]
Definition at line 96 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_delz [private]
Definition at line 97 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_diss [private]
Definition at line 97 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_hs [private]
Definition at line 97 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_maxvort01 [private]
Definition at line 105 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_maxvort02 [private]
Definition at line 112 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_maxvorthy1 [private]
Definition at line 106 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_omga [private]
Definition at line 97 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_pfhy [private]
Definition at line 96 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_pfnh [private]
Definition at line 96 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_ps [private]
Definition at line 97 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_pt [private]
Definition at line 96 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_srh01 [private]
Definition at line 107 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_srh03 [private]
Definition at line 107 of file fv_nggps_diag.F90.
integer, dimension(:), allocatable fv_nggps_diags_mod::id_tracer [private]
Definition at line 117 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_ua [private]
Definition at line 96 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_uhmax03 [private]
Definition at line 105 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_uhmax25 [private]
Definition at line 105 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_uhmin03 [private]
Definition at line 105 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_uhmin25 [private]
Definition at line 105 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_ustm [private]
Definition at line 106 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_va [private]
Definition at line 96 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_vstm [private]
Definition at line 107 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_w [private]
Definition at line 97 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_wmaxdn [private]
Definition at line 104 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::id_wmaxup [private]
Definition at line 104 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::ieco [private]
Definition at line 113 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::iedo [private]
Definition at line 114 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::isco [private]
Definition at line 113 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::isdo [private]
Definition at line 114 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::jeco [private]
Definition at line 113 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::jedo [private]
Definition at line 114 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::jsco [private]
Definition at line 113 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::jsdo [private]
Definition at line 114 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_dbz [private]
Definition at line 102 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_delp [private]
Definition at line 100 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_delz [private]
Definition at line 101 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_diss [private]
Definition at line 101 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_hs [private]
Definition at line 101 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_maxvort01 [private]
Definition at line 107 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_maxvort02 [private]
Definition at line 112 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_maxvorthy1 [private]
Definition at line 107 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_omga [private]
Definition at line 102 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_pfhy [private]
Definition at line 100 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_pfnh [private]
Definition at line 101 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_ps [private]
Definition at line 101 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_pt [private]
Definition at line 100 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_srh01 [private]
Definition at line 111 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_srh03 [private]
Definition at line 111 of file fv_nggps_diag.F90.
integer, dimension(:), allocatable fv_nggps_diags_mod::kend_tracer [private]
Definition at line 118 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_ua [private]
Definition at line 100 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_uhmax03 [private]
Definition at line 108 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_uhmax25 [private]
Definition at line 109 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_uhmin03 [private]
Definition at line 108 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_uhmin25 [private]
Definition at line 109 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_ustm [private]
Definition at line 110 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_va [private]
Definition at line 100 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_vstm [private]
Definition at line 110 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_w [private]
Definition at line 101 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_wdn [private]
Definition at line 104 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_windvect [private]
Definition at line 103 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kend_wup [private]
Definition at line 104 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_dbz [private]
Definition at line 102 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_delp [private]
Definition at line 98 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_delz [private]
Definition at line 99 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_diss [private]
Definition at line 99 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_hs [private]
Definition at line 99 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_maxvort01 [private]
Definition at line 106 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_maxvort02 [private]
Definition at line 112 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_maxvorthy1 [private]
Definition at line 106 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_omga [private]
Definition at line 102 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_pfhy [private]
Definition at line 98 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_pfnh [private]
Definition at line 99 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_ps [private]
Definition at line 99 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_pt [private]
Definition at line 98 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_srh01 [private]
Definition at line 110 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_srh03 [private]
Definition at line 111 of file fv_nggps_diag.F90.
integer, dimension(:), allocatable fv_nggps_diags_mod::kstt_tracer [private]
Definition at line 118 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_ua [private]
Definition at line 98 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_uhmax03 [private]
Definition at line 108 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_uhmax25 [private]
Definition at line 109 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_uhmin03 [private]
Definition at line 108 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_uhmin25 [private]
Definition at line 109 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_ustm [private]
Definition at line 110 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_va [private]
Definition at line 98 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_vstm [private]
Definition at line 110 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_w [private]
Definition at line 99 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_wdn [private]
Definition at line 104 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_windvect [private]
Definition at line 103 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::kstt_wup [private]
Definition at line 104 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::lat [private]
Definition at line 142 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::liq_wat [private]
Definition at line 124 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::lon [private]
Definition at line 142 of file fv_nggps_diag.F90.
logical fv_nggps_diags_mod::master [private]
Definition at line 95 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::maxvort01 [private]
Definition at line 144 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::maxvort02 [private]
Definition at line 145 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::maxvorthy1 [private]
Definition at line 145 of file fv_nggps_diag.F90.
real, parameter fv_nggps_diags_mod::missing_value = -1.e10 [private]
Definition at line 91 of file fv_nggps_diag.F90.
logical fv_nggps_diags_mod::module_is_initialized =.false. [private]
Definition at line 122 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::ncnsto [private]
Definition at line 113 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::nlevs [private]
Definition at line 115 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::npzo [private]
Definition at line 113 of file fv_nggps_diag.F90.
real(4), dimension(:,:), allocatable, target fv_nggps_diags_mod::psurf [private]
Definition at line 141 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::rainwat [private]
Definition at line 125 of file fv_nggps_diag.F90.
real, dimension(2) fv_nggps_diags_mod::skrange = (/ -10000000.0, 10000000.0 /) [private]
dissipation estimate for SKEB
Definition at line 129 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::snowwat [private]
Definition at line 125 of file fv_nggps_diag.F90.
integer fv_nggps_diags_mod::sphum [private]
Definition at line 124 of file fv_nggps_diag.F90.
real, parameter fv_nggps_diags_mod::stndrd_atmos_lapse = 0.0065 [private]
Definition at line 93 of file fv_nggps_diag.F90.
real, parameter fv_nggps_diags_mod::stndrd_atmos_ps = 101325. [private]
Definition at line 92 of file fv_nggps_diag.F90.
character(len=256) fv_nggps_diags_mod::tlongname [private]
Definition at line 136 of file fv_nggps_diag.F90.
character(len=128) fv_nggps_diags_mod::tname [private]
Definition at line 135 of file fv_nggps_diag.F90.
real, dimension(2) fv_nggps_diags_mod::trange = (/ 100., 350. /) [private]
temperature
Definition at line 128 of file fv_nggps_diag.F90.
character(len=256) fv_nggps_diags_mod::tunits [private]
Definition at line 136 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::uhmax03 [private]
Definition at line 143 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::uhmax25 [private]
Definition at line 144 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::uhmin03 [private]
Definition at line 143 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::uhmin25 [private]
Definition at line 144 of file fv_nggps_diag.F90.
real, dimension(:,:), allocatable fv_nggps_diags_mod::up2 [private]
Definition at line 143 of file fv_nggps_diag.F90.
logical fv_nggps_diags_mod::use_wrtgridcomp_output =.false. [private]
Definition at line 123 of file fv_nggps_diag.F90.
real, dimension(2) fv_nggps_diags_mod::vrange = (/ -330., 330. /) [private]
winds
Definition at line 126 of file fv_nggps_diag.F90.
real(4), dimension(:,:,:,:), allocatable, target fv_nggps_diags_mod::windvect [private]
Definition at line 140 of file fv_nggps_diag.F90.
real, dimension(2) fv_nggps_diags_mod::wrange = (/ -100., 100. /) [private]
vertical wind
Definition at line 127 of file fv_nggps_diag.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/driver/fvGFS/fv_nggps_diag.F90