test_cases_mod Module Reference
my dog typed this comment: mjkkicdsddsds, my cat typed this comment: cdjkkjfdjkjf my dog also typed this comment: kmasdlckmc my cat meowed
Data Types
interface mp_update_dwinds
Public Member Functions
subroutine, public init_case (u, v, w, pt, delp, q, phis, ps, pe, peln, pk, pkz, uc, vc, ua, va, ak, bk, gridstruct, flagstruct, npx, npy, npz, ng, ncnst, nwat, ndims, nregions, dry_mass, mountain, moist_phys, hydrostatic, hybrid_z, delz, ze0, adiabatic, ks, npx_global, ptop, domain_in, tile_in, bd)
subroutine, public checker_tracers (i0, i1, j0, j1, ifirst, ilast, jfirst, jlast, nq, km, q, lon, lat, nx, ny, rn)
subroutine, public case9_forcing1 (phis, time_since_start)
subroutine, public case9_forcing2 (phis)
subroutine, public case51_forcing (delp, uc, vc, u, v, ua, va, pe, time, dt, gridstruct, npx, npy, npz, ptop, domain)
subroutine, public get_stats (dt, dtout, nt, maxnt, ndays, u, v, pt, delp, q, phis, ps, uc, vc, ua, va, npx, npy, npz, ncnst, ndims, nregions, gridstruct, stats_lun, consv_lun, monitorFreq, tile, domain, nested)
subroutine, public check_courant_numbers (uc, vc, ndt, n_split, gridstruct, npx, npy, npz, tile, noPrint)
subroutine, public init_double_periodic (u, v, w, pt, delp, q, phis, ps, pe, peln, pk, pkz, uc, vc, ua, va, ak, bk, gridstruct, flagstruct, npx, npy, npz, ng, ncnst, nwat, ndims, nregions, dry_mass, mountain, moist_phys, hydrostatic, hybrid_z, delz, ze0, ks, ptop, domain_in, tile_in, bd)
subroutine, public init_latlon (u, v, pt, delp, q, phis, ps, pe, peln, pk, pkz, uc, vc, ua, va, ak, bk, gridstruct, npx, npy, npz, ng, ncnst, ndims, nregions, dry_mass, mountain, moist_phys, hybrid_z, delz, ze0, domain_in, tile_in)
subroutine mp_update_dwinds_3d (u, v, npx, npy, npz, domain)
real function globalsum (p, npx, npy, ifirst, ilast, jfirst, jlast, isd, ied, jsd, jed, gridstruct, tile)
Public Attributes
integer, public test_case
logical, public bubble_do
real, public alpha
integer, public nsolitons
real, public soliton_size = 750.e3
real, public soliton_umax = 50.
real, dimension(:),
*
allocatable, public pz0
real, dimension(:),
*
allocatable, public zz0
integer, public tracer_test
integer, public wind_field
Private Member Functions
subroutine init_winds (UBar, u, v, ua, va, uc, vc, defOnGrid, npx, npy, ng, ndims, nregions, nested, gridstruct, domain, tile)
subroutine get_vorticity (isc, iec, jsc, jec, isd, ied, jsd, jed, npz, u, v, vort, dx, dy, rarea)
subroutine terminator_tracers (i0, i1, j0, j1, ifirst, ilast, jfirst, jlast, km, q, delp, ncnst, lon, lat)
subroutine rankine_vortex (ubar, r0, p1, u, v, grid)
real function gh_jet (npy, lat_in)
real function u_jet (lat)
subroutine get_case9_b (B, agrid)
subroutine get_pt_on_great_circle (p1, p2, dist, heading, p3)
subroutine get_scalar_stats (var, varT, npx, npy, ndims, nregions, vmin, vmax, L1_norm, L2_norm, Linf_norm, gridstruct, tile)
subroutine get_vector_stats (varU, varUT, varV, varVT, npx, npy, ndims, nregions, vmin, vmax, L1_norm, L2_norm, Linf_norm, gridstruct, tile)
subroutine pmxn (p, npx, npy, nregions, tile, gridstruct, pmin, pmax, i0, j0, n0)
subroutine superk_sounding (km, pe, p00, ze, pt, qz)
subroutine balanced_k (km, is, ie, js, je, ng, ps0, ze1, ts1, qs1, uz1, dudz, pe, pk, pt, delz, zvir, ptop, ak, bk, agrid)
subroutine superk_u (km, zz, um, dudz)
subroutine dcmip16_bc (delp, pt, u, v, q, w, delz, is, ie, js, je, isd, ied, jsd, jed, npz, nq, ak, bk, ptop, pk, peln, pe, pkz, gz, phis, ps, grid, agrid, hydrostatic, nwat, adiabatic, do_pert, domain)
subroutine dcmip16_tc (delp, pt, u, v, q, w, delz, is, ie, js, je, isd, ied, jsd, jed, npz, nq, ak, bk, ptop, pk, peln, pe, pkz, gz, phis, ps, grid, agrid, hydrostatic, nwat, adiabatic)
subroutine init_latlon_winds (UBar, u, v, ua, va, uc, vc, defOnGrid, gridstruct)
subroutine d2a2c (im, jm, km, ifirst, ilast, jfirst, jlast, ng, nested, u, v, ua, va, uc, vc, gridstruct, domain)
subroutine atob_s (qin, qout, npx, npy, dxa, dya, nested, cubed_sphere, altInterp)
subroutine atod (uin, vin, uout, vout, dxa, dya, dxc, dyc, npx, npy, ng, nested, domain)
subroutine dtoa (uin, vin, uout, vout, dx, dy, dxa, dya, dxc, dyc, npx, npy, ng)
subroutine atoc (uin, vin, uout, vout, dx, dy, dxa, dya, npx, npy, ng, nested, domain, noComm)
subroutine ctoa (uin, vin, uout, vout, dx, dy, dxc, dyc, dxa, dya, npx, npy, ng)
subroutine rotate_winds (myU, myV, p1, p2, p3, p4, t1, ndims, dir)
subroutine mp_update_dwinds_2d (u, v, npx, npy, domain)
subroutine get_unit_vector (p1, p2, p3, uvect)
subroutine normalize_vect (np, e)
subroutine mp_ghost_ew (im, jm, km, nq, ifirst, ilast, jfirst, jlast, kfirst, klast, ng_w, ng_e, ng_s, ng_n, q_ghst, q)
subroutine interp_left_edge_1d (qout, qin, dx, ifirst, ilast, order)
subroutine vpol5 (u, v, im, jm, coslon, sinlon, cosl5, sinl5, ng_d, ng_s, jfirst, jlast)
subroutine prt_m1 (qname, q, is, ie, js, je, n_g, km, fac)
subroutine var_dz (km, ztop, ze)
subroutine sm1_edge (is, ie, js, je, km, i, j, ze, ntimes)
Private Attributes
integer sphum
integer theta_d
real(kind=r_grid), parameter radius = cnst_radius
real(kind=r_grid), parameter one = 1.d0
real p0_c0 = 3.0
real rgamma = 5.0
real lat0 = pi/2.0
pi/4.8
real lon0 = 0.0
pi-0.8
real, parameter pi_shift = 0.0
3.0*pi/4.
integer, parameter initwindscase0 =-1
integer, parameter initwindscase1 = 1
integer, parameter initwindscase2 = 5
integer, parameter initwindscase5 = 5
integer, parameter initwindscase6 =-1
integer, parameter initwindscase9 =-1
real ubar
real vbar
real gh0
real, dimension(:,:), allocatable case9_b
real, dimension(2) aoft
real, dimension(:,:,:), allocatable phi0
Validating Field.
real, dimension(:,:,:), allocatable ua0
Validating U-Wind.
real, dimension(:,:,:), allocatable va0
Validating V-Windfms_io_exit, get_tile_string, &.
real, dimension(:), allocatable gh_table
real, dimension(:), allocatable lats_table
logical gh_initialized = .false.
real tmass_orig
total mass
real tvort_orig
enstrophy (integral of total vorticity)
real tener_orig
energy
integer, parameter interporder = 1
Detailed Description
my dog typed this comment: mjkkicdsddsds, my cat typed this comment: cdjkkjfdjkjf my dog also typed this comment: kmasdlckmc my cat meowed
Definition at line 27 of file test_cases.F90.
Member Function/Subroutine Documentation
subroutine test_cases_mod::atob_s (real, dimension(isd:ied ,jsd:jed), intent(in) qin, real, dimension(isd:ied+1,jsd:jed+1), intent(out) qout, integer, intent(in) npx, integer, intent(in) npy, real, dimension(isd:ied,jsd:jed), intent(in) dxa, real, dimension(isd:ied,jsd:jed), intent(in) dya, logical, intent(in) nested, logical, intent(in) cubed_sphere, integer, intent(in), optional altInterp) [private]
Parameters
in qin A-grid field
out qout Output B-grid field
Definition at line 8341 of file test_cases.F90.
References interp_left_edge_1d().
Referenced by pmxn().
subroutine test_cases_mod::atoc (real, dimension(isd:ied ,jsd:jed), intent(in) uin, real, dimension(isd:ied ,jsd:jed), intent(in) vin, real, dimension(isd:ied+1,jsd:jed), intent(out) uout, real, dimension(isd:ied ,jsd:jed+1), intent(out) vout, real, dimension(isd:ied,jsd:jed+1), intent(in) dx, real, dimension(isd:ied+1,jsd:jed), intent(in) dy, real, dimension(isd:ied,jsd:jed), intent(in) dxa, real, dimension(isd:ied,jsd:jed), intent(in) dya, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ng, logical, intent(in) nested, type(domain2d), intent(inout) domain, logical, intent(in), optional noComm) [private]
Parameters
in uin A-grid u-wind field
in vin A-grid v-wind field
out uout C-grid u-wind field
out vout C-grid v-wind field
Definition at line 8572 of file test_cases.F90.
References interp_left_edge_1d().
Referenced by case51_forcing(), d2a2c(), get_stats(), init_case(), and init_winds().
subroutine test_cases_mod::atod (real, dimension(isd:ied ,jsd:jed), intent(in) uin, real, dimension(isd:ied ,jsd:jed), intent(in) vin, real, dimension(isd:ied ,jsd:jed+1), intent(out) uout, real, dimension(isd:ied+1,jsd:jed), intent(out) vout, real, dimension(isd:ied,jsd:jed), intent(in) dxa, real, dimension(isd:ied,jsd:jed), intent(in) dya, real, dimension(isd:ied+1,jsd:jed), intent(in) dxc, real, dimension(isd:ied,jsd:jed+1), intent(in) dyc, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ng, logical, intent(in) nested, type(domain2d), intent(inout) domain) [private]
Parameters
in uin A-grid u-wind field
in vin A-grid v-wind field
out uout D-grid u-wind field
out vout D-grid v-wind field
Definition at line 8477 of file test_cases.F90.
References interp_left_edge_1d().
Referenced by init_case(), and init_winds().
subroutine test_cases_mod::balanced_k (integer, intent(in) km, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ng, real, intent(in) ps0, real, dimension(km+1), intent(in) ze1, real, dimension(km), intent(in) ts1, real, dimension(km), intent(in) qs1, real, dimension(km), intent(in) uz1, real, dimension(km), intent(in) dudz, real, dimension(is-1:ie+1,km+1,js-1:je+1), intent(inout) pe, real, dimension(is:ie,js:je,km+1), intent(out) pk, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(inout) pt, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(inout) delz, real, intent(in) zvir, real, intent(inout) ptop, real, dimension(km+1), intent(inout) ak, real, dimension(km+1), intent(inout) bk, real(kind=r_grid), dimension(is-ng:ie+ng,js-ng:je+ng,2), intent(in) agrid) [private]
Definition at line 6928 of file test_cases.F90.
References fv_diagnostics_mod::ppme(), and prt_m1().
Referenced by init_case().
subroutine, public test_cases_mod::case51_forcing (real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied+1,jsd:jed,npz), intent(inout) uc, real, dimension(isd:ied,jsd:jed+1,npz), intent(inout) vc, real, dimension(isd:ied,jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed,npz), intent(inout) v, real, dimension(isd:ied,jsd:jed,npz), intent(inout) ua, real, dimension(isd:ied,jsd:jed,npz), intent(inout) va, real, dimension(is-1:ie+1, npz+1,js-1:je+1), intent(inout) pe, real, intent(in) time, real, intent(in) dt, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, real, intent(inout) ptop, type(domain2d), intent(inout) domain)
Definition at line 4219 of file test_cases.F90.
References atoc(), dtoa(), fv_grid_utils_mod::get_latlon_vector(), fv_grid_utils_mod::get_unit_vect2(), fv_grid_utils_mod::inner_prod(), and fv_grid_utils_mod::mid_pt_sphere().
subroutine, public test_cases_mod::case9_forcing1 (real, dimension(isd:ied ,jsd:jed), intent(inout) phis, real, intent(in) time_since_start)
Definition at line 4166 of file test_cases.F90.
Referenced by dyn_core_mod::dyn_core().
subroutine, public test_cases_mod::case9_forcing2 (real, dimension(isd:ied ,jsd:jed), intent(inout) phis)
Definition at line 4201 of file test_cases.F90.
Referenced by dyn_core_mod::dyn_core().
subroutine, public test_cases_mod::check_courant_numbers (real, dimension(isd:ied+1,jsd:jed ,npz), intent(in) uc, real, dimension(isd:ied ,jsd:jed+1,npz), intent(in) vc, real, intent(in) ndt, integer, intent(in) n_split, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) tile, logical, intent(in), optional noPrint)
Definition at line 5205 of file test_cases.F90.
subroutine, public test_cases_mod::checker_tracers (integer, intent(in) i0, integer, intent(in) i1, integer, intent(in) j0, integer, intent(in) j1, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) jfirst, integer, intent(in) jlast, integer, intent(in) nq, integer, intent(in) km, real, dimension(ifirst:ilast,jfirst:jlast,km,nq), intent(out) q, real(kind=r_grid), dimension(i0:i1,j0:j1), intent(in) lon, real(kind=r_grid), dimension(i0:i1,j0:j1), intent(in) lat, real, intent(in) nx, real, intent(in) ny, real, intent(in), optional rn)
Definition at line 3859 of file test_cases.F90.
Referenced by external_ic_mod::get_nggps_ic(), and init_case().
subroutine test_cases_mod::ctoa (real, dimension(isd:ied+1,jsd:jed), intent(in) uin, real, dimension(isd:ied ,jsd:jed+1), intent(in) vin, real, dimension(isd:ied ,jsd:jed), intent(out) uout, real, dimension(isd:ied ,jsd:jed), intent(out) vout, real, dimension(isd:ied,jsd:jed+1), intent(in) dx, real, dimension(isd:ied+1,jsd:jed), intent(in) dy, real, dimension(isd:ied+1,jsd:jed), intent(in) dxc, real, dimension(isd:ied,jsd:jed+1), intent(in) dyc, real, dimension(isd:ied,jsd:jed), intent(in) dxa, real, dimension(isd:ied,jsd:jed), intent(in) dya, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ng) [private]
Parameters
in uin C-grid u-wind field
in vin C-grid v-wind field
out uout A-grid u-wind field
out vout A-grid v-wind field
Definition at line 8692 of file test_cases.F90.
References interp_left_edge_1d().
Referenced by init_winds().
subroutine test_cases_mod::d2a2c (integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) jfirst, integer, intent(in) jlast, integer, intent(in) ng, logical, intent(in) nested, real, dimension(isd:ied,jsd:jed+1), intent(inout) u, real, dimension(isd:ied+1,jsd:jed), intent(inout) v, real, dimension(isd:ied,jsd:jed), intent(inout) ua, real, dimension(isd:ied,jsd:jed), intent(inout) va, real, dimension(isd:ied+1,jsd:jed), intent(inout) uc, real, dimension(isd:ied,jsd:jed+1), intent(inout) vc, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) domain) [private]
Definition at line 8107 of file test_cases.F90.
References atoc(), dtoa(), tp_core_mod::mp_ghost_ew(), and vpol5().
subroutine test_cases_mod::dcmip16_bc (real, dimension(isd:ied,jsd:jed,npz), intent(out) delp, real, dimension(isd:ied,jsd:jed,npz), intent(out) pt, real, dimension(isd:ied,jsd:jed+1,npz), intent(out) u, real, dimension(isd:ied+1,jsd:jed,npz), intent(out) v, real, dimension(isd:ied,jsd:jed,npz,nq), intent(inout) q, real, dimension(isd:ied,jsd:jed,npz), intent(out) w, real, dimension(isd:ied,jsd:jed,npz), intent(out) delz, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npz, integer, intent(in) nq, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, intent(in) ptop, real, dimension(is:ie,js:je,npz+1), intent(out) pk, real, dimension(is:ie,npz+1,js:je), intent(out) peln, real, dimension(is-1:ie+1,npz+1,js-1:je+1), intent(out) pe, real, dimension(is:ie,js:je,npz), intent(out) pkz, real, dimension(isd:ied,jsd:jed,npz+1), intent(out) gz, real, dimension(isd:ied,jsd:jed), intent(out) phis, real, dimension(isd:ied,jsd:jed), intent(out) ps, real(kind=r_grid), dimension(isd:ied+1,jsd:jed+1,2), intent(in) grid, real(kind=r_grid), dimension(isd:ied,jsd:jed,2), intent(in) agrid, logical, intent(in) hydrostatic, integer, intent(in) nwat, logical, intent(in) adiabatic, logical, intent(in) do_pert, type(domain2d), intent(inout) domain) [private]
Definition at line 7118 of file test_cases.F90.
References dcmip16_bc_pressure(), dcmip16_bc_sphum(), dcmip16_bc_temperature(), dcmip16_bc_uwind(), dcmip16_bc_uwind_pert(), fv_grid_utils_mod::get_latlon_vector(), fv_grid_utils_mod::get_unit_vect2(), fv_grid_utils_mod::inner_prod(), fv_grid_utils_mod::mid_pt_sphere(), and terminator_tracers().
Referenced by init_case().
subroutine test_cases_mod::dcmip16_tc (real, dimension(isd:ied,jsd:jed,npz), intent(out) delp, real, dimension(isd:ied,jsd:jed,npz), intent(out) pt, real, dimension(isd:ied,jsd:jed+1,npz), intent(out) u, real, dimension(isd:ied+1,jsd:jed,npz), intent(out) v, real, dimension(isd:ied,jsd:jed,npz,nq), intent(inout) q, real, dimension(isd:ied,jsd:jed,npz), intent(out) w, real, dimension(isd:ied,jsd:jed,npz), intent(out) delz, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npz, integer, intent(in) nq, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, intent(in) ptop, real, dimension(is:ie,js:je,npz+1), intent(out) pk, real, dimension(is:ie,npz+1,js:je), intent(out) peln, real, dimension(is-1:ie+1,npz+1,js-1:je+1), intent(out) pe, real, dimension(is:ie,js:je,npz), intent(out) pkz, real, dimension(isd:ied,jsd:jed,npz+1), intent(out) gz, real, dimension(isd:ied,jsd:jed), intent(out) phis, real, dimension(isd:ied,jsd:jed), intent(out) ps, real(kind=r_grid), dimension(isd:ied+1,jsd:jed+1,2), intent(in) grid, real(kind=r_grid), dimension(isd:ied,jsd:jed,2), intent(in) agrid, logical, intent(in) hydrostatic, integer, intent(in) nwat, logical, intent(in) adiabatic) [private]
Definition at line 7491 of file test_cases.F90.
References dcmip16_tc_pressure(), dcmip16_tc_sphum(), dcmip16_tc_temperature(), dcmip16_tc_uwind_pert(), fv_grid_utils_mod::get_latlon_vector(), fv_grid_utils_mod::get_unit_vect2(), fv_grid_utils_mod::great_circle_dist(), fv_grid_utils_mod::inner_prod(), and fv_grid_utils_mod::mid_pt_sphere().
Referenced by init_case().
subroutine test_cases_mod::dtoa (real, dimension(isd:ied ,jsd:jed+1), intent(in) uin, real, dimension(isd:ied+1,jsd:jed), intent(in) vin, real, dimension(isd:ied ,jsd:jed), intent(out) uout, real, dimension(isd:ied ,jsd:jed), intent(out) vout, real, dimension(isd:ied,jsd:jed+1), intent(in) dx, real, dimension(isd:ied+1,jsd:jed), intent(in) dy, real, dimension(isd:ied,jsd:jed), intent(in) dxa, real, dimension(isd:ied,jsd:jed), intent(in) dya, real, dimension(isd:ied+1,jsd:jed), intent(in) dxc, real, dimension(isd:ied,jsd:jed+1), intent(in) dyc, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ng) [private]
Parameters
in uin D-grid u-wind field
in vin D-grid v-wind field
out uout A-grid u-wind field
out vout A-grid v-wind field
Definition at line 8520 of file test_cases.F90.
References interp_left_edge_1d().
Referenced by case51_forcing(), d2a2c(), get_stats(), init_case(), init_winds(), and pmxn().
subroutine test_cases_mod::get_case9_b (real, dimension(isd:ied,jsd:jed), intent(out) B, real, dimension(isd:ied,jsd:jed,2), intent(in) agrid) [private]
Definition at line 4137 of file test_cases.F90.
Referenced by init_case().
subroutine test_cases_mod::get_pt_on_great_circle (real, dimension(2), intent(in) p1, real, dimension(2), intent(in) p2, real, intent(in) dist, real, intent(in) heading, real, dimension(2), intent(out) p3) [private]
Definition at line 4985 of file test_cases.F90.
Referenced by get_stats(), and pmxn().
subroutine test_cases_mod::get_scalar_stats (real, dimension(isd:ied,jsd:jed), intent(in) var, real, dimension(isd:ied,jsd:jed), intent(in) varT, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ndims, integer, intent(in) nregions, real, intent(out) vmin, real, intent(out) vmax, real, intent(out) L1_norm, real, intent(out) L2_norm, real, intent(out) Linf_norm, type(fv_grid_type), target gridstruct, integer, intent(in) tile) [private]
Definition at line 5020 of file test_cases.F90.
References globalsum(), and pmxn().
Referenced by get_stats(), and init_case().
subroutine, public test_cases_mod::get_stats (real, intent(in) dt, real, intent(in) dtout, integer, intent(in) nt, integer, intent(in) maxnt, real, intent(in) ndays, real, dimension(isd:ied ,jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) v, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) pt, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) delp, real, dimension(isd:ied ,jsd:jed ,npz, ncnst), intent(inout) q, real, dimension(isd:ied ,jsd:jed), intent(inout) phis, real, dimension(isd:ied ,jsd:jed), intent(inout) ps, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) uc, real, dimension(isd:ied ,jsd:jed+1,npz), intent(inout) vc, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) ua, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) va, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ncnst, integer, intent(in) ndims, integer, intent(in) nregions, type(fv_grid_type), target gridstruct, integer, intent(in) stats_lun, integer, intent(in) consv_lun, integer, intent(in) monitorFreq, integer, intent(in) tile, type(domain2d), intent(inout) domain, logical, intent(in) nested)
Definition at line 4538 of file test_cases.F90.
References atoc(), dtoa(), get_pt_on_great_circle(), get_scalar_stats(), get_vector_stats(), globalsum(), fv_grid_utils_mod::great_circle_dist(), and pmxn().
subroutine test_cases_mod::get_unit_vector (real(kind=r_grid), dimension(2), intent(in) p1, real(kind=r_grid), dimension(2), intent(in) p2, real(kind=r_grid), dimension(2), intent(in) p3, real(kind=r_grid), dimension(3), intent(out) uvect) [private]
Definition at line 8918 of file test_cases.F90.
References fv_grid_utils_mod::normalize_vect(), fv_grid_utils_mod::project_sphere_v(), and fv_grid_tools_mod::spherical_to_cartesian().
Referenced by rotate_winds().
subroutine test_cases_mod::get_vector_stats (real, dimension(isd:ied,jsd:jed), intent(in) varU, real, dimension(isd:ied,jsd:jed), intent(in) varUT, real, dimension(isd:ied,jsd:jed), intent(in) varV, real, dimension(isd:ied,jsd:jed), intent(in) varVT, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ndims, integer, intent(in) nregions, real, intent(out) vmin, real, intent(out) vmax, real, intent(out) L1_norm, real, intent(out) L2_norm, real, intent(out) Linf_norm, type(fv_grid_type), target gridstruct, integer, intent(in) tile) [private]
Definition at line 5108 of file test_cases.F90.
References globalsum(), and pmxn().
Referenced by get_stats().
subroutine test_cases_mod::get_vorticity (integer isc, integer iec, integer jsc, integer jec, integer isd, integer ied, integer jsd, integer jed, integer npz, real, dimension(isd:ied, jsd:jed+1, npz), intent(in) u, real, dimension(isd:ied+1, jsd:jed, npz), intent(in) v, real, dimension(isc:iec, jsc:jec, npz), intent(out) vort, real, dimension(isd:ied,jsd:jed+1), intent(in) dx, real, dimension(isd:ied+1,jsd:jed), intent(in) dy, real, dimension(isd:ied,jsd:jed), intent(in) rarea) [private]
Definition at line 3826 of file test_cases.F90.
real function test_cases_mod::gh_jet (integer, intent(in) npy, real, intent(in) lat_in) [private]
Definition at line 4074 of file test_cases.F90.
References u_jet().
Referenced by init_case().
real function test_cases_mod::globalsum (real, dimension(ifirst:ilast,jfirst:jlast), intent(in) p, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) jfirst, integer, intent(in) jlast, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) tile)
Parameters
in p field to be summed
Definition at line 8821 of file test_cases.F90.
Referenced by get_scalar_stats(), get_stats(), and get_vector_stats().
subroutine, public test_cases_mod::init_case (real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(inout) v, real, dimension(bd%isd: ,bd%jsd: ,1:), intent(inout) w, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) pt, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) delp, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz, ncnst), intent(inout) q, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed), intent(inout) phis, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed), intent(inout) ps, real, dimension(bd%is-1:bd%ie+1,npz+1,bd%js-1:bd%je+1), intent(inout) pe, real, dimension(bd%is :bd%ie ,npz+1 ,bd%js:bd%je), intent(inout) peln, real, dimension(bd%is:bd%ie ,bd%js:bd%je ,npz+1), intent(inout) pk, real, dimension(bd%is:bd%ie ,bd%js:bd%je ,npz), intent(inout) pkz, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(inout) uc, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) vc, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) ua, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) va, real, dimension(npz+1), intent(inout) ak, real, dimension(npz+1), intent(inout) bk, type(fv_grid_type), target gridstruct, type(fv_flags_type), intent(in), target flagstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ng, integer, intent(in) ncnst, integer, intent(in) nwat, integer, intent(in) ndims, integer, intent(in) nregions, real, intent(in) dry_mass, logical, intent(in) mountain, logical, intent(in) moist_phys, logical, intent(in) hydrostatic, logical, intent(in) hybrid_z, real, dimension(bd%isd:,bd%jsd:,1:), intent(inout) delz, real, dimension(bd%is:,bd%js:,1:), intent(inout) ze0, logical, intent(in) adiabatic, integer, intent(in) ks, integer, intent(in) npx_global, real, intent(inout) ptop, type(domain2d), intent(in), target domain_in, integer, intent(in), target tile_in, type(fv_grid_bounds_type), intent(in) bd)
Definition at line 544 of file test_cases.F90.
References atoc(), atod(), balanced_k(), fv_grid_utils_mod::cart_to_latlon(), checker_tracers(), fv_eta_mod::compute_dz_l32(), dcmip16_bc(), dcmip16_tc(), dtoa(), fv_grid_utils_mod::g_sum(), get_case9_b(), fv_grid_utils_mod::get_latlon_vector(), get_scalar_stats(), fv_grid_utils_mod::get_unit_vect2(), fv_diagnostics_mod::get_vorticity(), gh_jet(), fv_grid_utils_mod::great_circle_dist(), fv_eta_mod::gw_1d(), fv_eta_mod::hybrid_z_dz(), init_hydro_mod::hydro_eq(), init_winds(), fv_grid_utils_mod::inner_prod(), fv_grid_utils_mod::latlon2xyz(), fv_grid_utils_mod::mid_pt_sphere(), init_hydro_mod::p_var(), fv_diagnostics_mod::prt_maxmin(), rankine_vortex(), rotate_winds(), fv_eta_mod::set_hybrid_z(), superk_sounding(), superk_u(), fv_surf_map_mod::surfdrv(), terminator_tracers(), u_jet(), and fv_eta_mod::var_dz().
Referenced by fv_restart_mod::fv_restart().
subroutine, public test_cases_mod::init_double_periodic (real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(inout) v, real, dimension(bd%isd: ,bd%jsd: ,1:), intent(inout) w, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) pt, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) delp, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz, ncnst), intent(inout) q, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed), intent(inout) phis, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed), intent(inout) ps, real, dimension(bd%is-1:bd%ie+1,npz+1,bd%js-1:bd%je+1), intent(inout) pe, real, dimension(bd%is :bd%ie ,npz+1 ,bd%js:bd%je), intent(inout) peln, real, dimension(bd%is:bd%ie ,bd%js:bd%je ,npz+1), intent(inout) pk, real, dimension(bd%is:bd%ie ,bd%js:bd%je ,npz), intent(inout) pkz, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(inout) uc, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) vc, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) ua, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed ,npz), intent(inout) va, real, dimension(npz+1), intent(inout) ak, real, dimension(npz+1), intent(inout) bk, type(fv_grid_type), target gridstruct, type(fv_flags_type), target flagstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ng, integer, intent(in) ncnst, integer, intent(in) nwat, integer, intent(in) ndims, integer, intent(in) nregions, real, intent(in) dry_mass, logical, intent(in) mountain, logical, intent(in) moist_phys, logical, intent(in) hydrostatic, logical, intent(in) hybrid_z, real, dimension(bd%isd:,bd%jsd:,1:), intent(inout) delz, real, dimension(bd%is:,bd%js:,1:), intent(inout) ze0, integer, intent(inout) ks, real, intent(inout) ptop, type(domain2d), intent(in), target domain_in, integer, intent(inout), target tile_in, type(fv_grid_bounds_type), intent(in) bd)
Definition at line 6076 of file test_cases.F90.
References fv_eta_mod::compute_dz_l101(), init_hydro_mod::hydro_eq(), fv_grid_utils_mod::make_eta_level(), init_hydro_mod::p_var(), fv_sg_mod::qsmith(), and fv_eta_mod::set_hybrid_z().
Referenced by fv_restart_mod::fv_restart().
subroutine, public test_cases_mod::init_latlon (real, dimension(isd:ied ,jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) v, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) pt, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) delp, real, dimension(isd:ied ,jsd:jed ,npz, ncnst), intent(inout) q, real, dimension(isd:ied ,jsd:jed), intent(inout) phis, real, dimension(isd:ied ,jsd:jed), intent(inout) ps, real, dimension(is-1:ie+1,npz+1,js-1:je+1), intent(inout) pe, real, dimension(is :ie ,npz+1 ,js:je), intent(inout) peln, real, dimension(is:ie ,js:je ,npz+1), intent(inout) pk, real, dimension(is:ie ,js:je ,npz), intent(inout) pkz, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) uc, real, dimension(isd:ied ,jsd:jed+1,npz), intent(inout) vc, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) ua, real, dimension(isd:ied ,jsd:jed ,npz), intent(inout) va, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ng, integer, intent(in) ncnst, integer, intent(in) ndims, integer, intent(in) nregions, real, intent(in) dry_mass, logical, intent(in) mountain, logical, intent(in) moist_phys, logical, intent(in) hybrid_z, real, dimension(isd:,jsd:,1:), intent(inout) delz, real, dimension(is:,js:,1:), intent(inout) ze0, type(domain2d), intent(in), target domain_in, integer, intent(in), target tile_in)
Definition at line 7842 of file test_cases.F90.
References fv_grid_utils_mod::great_circle_dist(), and init_latlon_winds().
Referenced by fv_restart_mod::fv_restart().
subroutine test_cases_mod::init_latlon_winds (real, intent(inout) UBar, real, dimension(isd:ied ,jsd:jed+1), intent(inout) u, real, dimension(isd:ied+1,jsd:jed), intent(inout) v, real, dimension(isd:ied ,jsd:jed), intent(inout) ua, real, dimension(isd:ied ,jsd:jed), intent(inout) va, real, dimension(isd:ied+1,jsd:jed), intent(inout) uc, real, dimension(isd:ied ,jsd:jed+1), intent(inout) vc, integer, intent(in) defOnGrid, type(fv_grid_type), intent(in), target gridstruct) [private]
Definition at line 8022 of file test_cases.F90.
Referenced by init_latlon().
subroutine test_cases_mod::init_winds (real, intent(inout) UBar, real, dimension(isd:ied ,jsd:jed+1), intent(inout) u, real, dimension(isd:ied+1,jsd:jed), intent(inout) v, real, dimension(isd:ied ,jsd:jed), intent(inout) ua, real, dimension(isd:ied ,jsd:jed), intent(inout) va, real, dimension(isd:ied+1,jsd:jed), intent(inout) uc, real, dimension(isd:ied ,jsd:jed+1), intent(inout) vc, integer, intent(in) defOnGrid, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ng, integer, intent(in) ndims, integer, intent(in) nregions, logical, intent(in) nested, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) domain, integer, intent(in) tile) [private]
Definition at line 251 of file test_cases.F90.
References atoc(), atod(), ctoa(), dtoa(), fv_grid_utils_mod::get_latlon_vector(), fv_grid_utils_mod::get_unit_vect2(), fv_grid_utils_mod::inner_prod(), fv_grid_utils_mod::mid_pt_sphere(), and rotate_winds().
Referenced by init_case().
subroutine test_cases_mod::interp_left_edge_1d (real, dimension(ifirst:), intent(out) qout, real, dimension(ifirst:), intent(in) qin, real, dimension(ifirst:), intent(in) dx, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) order) [private]
Definition at line 9018 of file test_cases.F90.
Referenced by atob_s(), atoc(), atod(), ctoa(), and dtoa().
subroutine test_cases_mod::mp_ghost_ew (integer, intent(in) im, integer, intent(in) jm, integer, intent(in) km, integer, intent(in) nq, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) jfirst, integer, intent(in) jlast, integer, intent(in) kfirst, integer, intent(in) klast, integer, intent(in) ng_w, integer, intent(in) ng_e, integer, intent(in) ng_s, integer, intent(in) ng_n, real, dimension(ifirst-ng_w:ilast+ng_e,jfirst-ng_s:jlast+ng_n,kfirst:klast,nq), intent(inout) q_ghst, real, dimension(ifirst:ilast,jfirst:jlast,kfirst:klast,nq), intent(in), optional q) [private]
Definition at line 8962 of file test_cases.F90.
subroutine test_cases_mod::mp_update_dwinds_2d (real, dimension(isd:ied ,jsd:jed+1), intent(inout) u, real, dimension(isd:ied+1,jsd:jed), intent(inout) v, integer, intent(in) npx, integer, intent(in) npy, type(domain2d), intent(inout) domain) [private]
Parameters
in,out u D-grid u-wind field
in,out v D-grid v-wind field
Definition at line 8786 of file test_cases.F90.
subroutine test_cases_mod::mp_update_dwinds_3d (real, dimension(isd:ied ,jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) v, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, type(domain2d), intent(inout) domain)
Parameters
in,out u D-grid u-wind field
in,out v D-grid v-wind field
Definition at line 8804 of file test_cases.F90.
subroutine test_cases_mod::normalize_vect (integer, intent(in) np, real(kind=r_grid), dimension(3,np), intent(inout) e) [private]
Definition at line 8938 of file test_cases.F90.
subroutine test_cases_mod::pmxn (real, dimension(isd:ied,jsd:jed), intent(in) p, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) nregions, integer, intent(in) tile, type(fv_grid_type), intent(in), target gridstruct, real, intent(out) pmin, real, intent(out) pmax, integer, intent(out) i0, integer, intent(out) j0, integer, intent(out) n0) [private]
Definition at line 5332 of file test_cases.F90.
References atob_s(), fv_grid_utils_mod::cubed_to_latlon(), dtoa(), get_pt_on_great_circle(), fv_grid_utils_mod::great_circle_dist(), fv_grid_utils_mod::mid_pt_sphere(), and rotate_winds().
Referenced by get_scalar_stats(), get_stats(), and get_vector_stats().
subroutine test_cases_mod::prt_m1 (character(len=*), intent(in) qname, real, dimension(is-n_g:ie+n_g, js-n_g:je+n_g, km), intent(in) q, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) n_g, integer, intent(in) km, real, intent(in) fac) [private]
Definition at line 9218 of file test_cases.F90.
Referenced by balanced_k(), and superk_sounding().
subroutine test_cases_mod::rankine_vortex (real, intent(in) ubar, real, intent(in) r0, real, dimension(2), intent(in) p1, real, dimension(isd:ied, jsd:jed+1), intent(inout) u, real, dimension(isd:ied+1,jsd:jed), intent(inout) v, real(kind=r_grid), dimension(isd:ied+1,jsd:jed+1,2), intent(in) grid) [private]
Definition at line 3997 of file test_cases.F90.
References fv_grid_utils_mod::get_latlon_vector(), fv_grid_utils_mod::get_unit_vect2(), fv_grid_utils_mod::inner_prod(), and fv_grid_utils_mod::mid_pt_sphere().
Referenced by init_case().
subroutine test_cases_mod::rotate_winds (real, intent(inout) myU, real, intent(inout) myV, real(kind=r_grid), dimension(ndims), intent(in) p1, real(kind=r_grid), dimension(ndims), intent(in) p2, real(kind=r_grid), dimension(ndims), intent(in) p3, real(kind=r_grid), dimension(ndims), intent(in) p4, real(kind=r_grid), dimension(ndims), intent(in) t1, integer, intent(in) ndims, integer, intent(in) dir) [private]
Parameters
in,out myu u-wind field
in,out myv v-wind field
in dir Direction ; 1=>sphere-to-cube 2=> cube-to-sphere
Definition at line 8743 of file test_cases.F90.
References get_unit_vector(), and fv_grid_utils_mod::inner_prod().
Referenced by init_case(), init_winds(), and pmxn().
subroutine test_cases_mod::sm1_edge (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, integer, intent(in) i, integer, intent(in) j, real, dimension(is:ie,js:je,km+1), intent(inout) ze, integer, intent(in) ntimes) [private]
Definition at line 9309 of file test_cases.F90.
subroutine test_cases_mod::superk_sounding (integer, intent(in) km, real, dimension(km+1), intent(inout) pe, real, intent(in) p00, real, dimension(km+1), intent(in) ze, real, dimension(km), intent(out) pt, real, dimension(km), intent(out) qz) [private]
Definition at line 6799 of file test_cases.F90.
References prt_m1().
Referenced by init_case().
subroutine test_cases_mod::superk_u (integer, intent(in) km, real, dimension(km), intent(in) zz, real, dimension(km), intent(out) um, real, dimension(km), intent(out) dudz) [private]
Definition at line 7083 of file test_cases.F90.
Referenced by init_case().
subroutine test_cases_mod::terminator_tracers (integer, intent(in) i0, integer, intent(in) i1, integer, intent(in) j0, integer, intent(in) j1, integer, intent(in) ifirst, integer, intent(in) ilast, integer, intent(in) jfirst, integer, intent(in) jlast, integer, intent(in) km, real, dimension(ifirst:ilast,jfirst:jlast,km,ncnst), intent(inout) q, real, dimension(ifirst:ilast,jfirst:jlast,km), intent(in) delp, integer, intent(in) ncnst, real(kind=r_grid), dimension(ifirst:ilast,jfirst:jlast), intent(in) lon, real(kind=r_grid), dimension(ifirst:ilast,jfirst:jlast), intent(in) lat) [private]
Definition at line 3928 of file test_cases.F90.
Referenced by dcmip16_bc(), and init_case().
real function test_cases_mod::u_jet (real lat) [private]
Definition at line 4121 of file test_cases.F90.
Referenced by gh_jet(), and init_case().
subroutine test_cases_mod::var_dz (integer, intent(in) km, real, intent(in) ztop, real, dimension(km+1), intent(out) ze) [private]
Definition at line 9248 of file test_cases.F90.
References fv_eta_mod::sm1_edge().
subroutine test_cases_mod::vpol5 (real, dimension(im,jfirst-ng_d:jlast+ng_s), intent(in) u, real, dimension(im,jfirst-ng_d:jlast+ng_d), intent(inout) v, integer im, integer jm, real, dimension(im,jm), intent(in) coslon, real, dimension(im,jm), intent(in) sinlon, real, dimension(im,jm), intent(in) cosl5, real, dimension(im,jm), intent(in) sinl5, integer, intent(in) ng_d, integer, intent(in) ng_s, integer jfirst, integer jlast) [private]
Parameters
im Total longitudes
jm Total latitudes
jfirst First PE latitude (no ghosting)
jlast Last PE latitude (no ghosting)
Definition at line 9125 of file test_cases.F90.
Referenced by d2a2c().
Member Data Documentation
real, public test_cases_mod::alpha
Definition at line 182 of file test_cases.F90.
real, dimension(2) test_cases_mod::aoft [private]
Definition at line 214 of file test_cases.F90.
logical, public test_cases_mod::bubble_do
Definition at line 181 of file test_cases.F90.
real, dimension(:,:), allocatable test_cases_mod::case9_b [private]
Definition at line 213 of file test_cases.F90.
real test_cases_mod::gh0 [private]
Definition at line 210 of file test_cases.F90.
logical test_cases_mod::gh_initialized = .false. [private]
Definition at line 223 of file test_cases.F90.
real, dimension(:), allocatable test_cases_mod::gh_table [private]
Definition at line 222 of file test_cases.F90.
integer, parameter test_cases_mod::initwindscase0 =-1 [private]
Definition at line 196 of file test_cases.F90.
integer, parameter test_cases_mod::initwindscase1 = 1 [private]
Definition at line 197 of file test_cases.F90.
integer, parameter test_cases_mod::initwindscase2 = 5 [private]
Definition at line 198 of file test_cases.F90.
integer, parameter test_cases_mod::initwindscase5 = 5 [private]
Definition at line 199 of file test_cases.F90.
integer, parameter test_cases_mod::initwindscase6 =-1 [private]
Definition at line 200 of file test_cases.F90.
integer, parameter test_cases_mod::initwindscase9 =-1 [private]
Definition at line 201 of file test_cases.F90.
integer, parameter test_cases_mod::interporder = 1 [private]
Definition at line 230 of file test_cases.F90.
real test_cases_mod::lat0 = pi/2.0 [private]
pi/4.8
Definition at line 189 of file test_cases.F90.
real, dimension(:), allocatable test_cases_mod::lats_table [private]
Definition at line 222 of file test_cases.F90.
real test_cases_mod::lon0 = 0.0 [private]
pi-0.8
Definition at line 190 of file test_cases.F90.
integer, public test_cases_mod::nsolitons
Definition at line 183 of file test_cases.F90.
real(kind=r_grid), parameter test_cases_mod::one = 1.d0 [private]
Definition at line 179 of file test_cases.F90.
real test_cases_mod::p0_c0 = 3.0 [private]
Definition at line 187 of file test_cases.F90.
real, dimension(:,:,:), allocatable test_cases_mod::phi0 [private]
Validating Field.
Definition at line 218 of file test_cases.F90.
real, parameter test_cases_mod::pi_shift = 0.0 [private]
3.0*pi/4.
Definition at line 193 of file test_cases.F90.
real, dimension(:), allocatable, public test_cases_mod::pz0
Definition at line 203 of file test_cases.F90.
real(kind=r_grid), parameter test_cases_mod::radius = cnst_radius [private]
Definition at line 178 of file test_cases.F90.
real test_cases_mod::rgamma = 5.0 [private]
Definition at line 188 of file test_cases.F90.
real, public test_cases_mod::soliton_size = 750.e3
Definition at line 184 of file test_cases.F90.
real, public test_cases_mod::soliton_umax = 50.
Definition at line 184 of file test_cases.F90.
integer test_cases_mod::sphum [private]
Definition at line 177 of file test_cases.F90.
real test_cases_mod::tener_orig [private]
energy
Definition at line 228 of file test_cases.F90.
integer, public test_cases_mod::test_case
Definition at line 180 of file test_cases.F90.
integer test_cases_mod::theta_d [private]
Definition at line 177 of file test_cases.F90.
real test_cases_mod::tmass_orig [private]
total mass
Definition at line 226 of file test_cases.F90.
integer, public test_cases_mod::tracer_test
Definition at line 205 of file test_cases.F90.
real test_cases_mod::tvort_orig [private]
enstrophy (integral of total vorticity)
Definition at line 227 of file test_cases.F90.
real, dimension(:,:,:), allocatable test_cases_mod::ua0 [private]
Validating U-Wind.
Definition at line 219 of file test_cases.F90.
real test_cases_mod::ubar [private]
Definition at line 208 of file test_cases.F90.
real, dimension(:,:,:), allocatable test_cases_mod::va0 [private]
Validating V-Windfms_io_exit, get_tile_string, &.
Definition at line 220 of file test_cases.F90.
real test_cases_mod::vbar [private]
Definition at line 208 of file test_cases.F90.
integer, public test_cases_mod::wind_field
Definition at line 205 of file test_cases.F90.
real, dimension(:), allocatable, public test_cases_mod::zz0
Definition at line 203 of file test_cases.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/test_cases.F90