fv_control_mod Module Reference
The module 'FV3_control' is for initialization and termination of the model, and controls namelist parameters in FV3.
Public Member Functions
subroutine, public fv_init (Atm, dt_atmos, grids_on_this_pe, p_split)
The subroutine 'fv_init' initializes FV3.
subroutine, public fv_end (Atm, grids_on_this_pe, restart_endfcst)
The subroutine 'fv_end' terminates FV3, deallocates memory, saves restart files, and stops I/O.
Public Attributes
integer, public ngrids = 1
integer, dimension(:),
*
allocatable, public pelist_all
Private Member Functions
subroutine run_setup (Atm, dt_atmos, grids_on_this_pe, p_split)
The subroutine 'run_setup' initializes the run from a namelist.
subroutine init_nesting (Atm, grids_on_this_pe, p_split)
subroutine setup_pointers (Atm)
The subroutine 'setup_pointers' associates the MODULE flag pointers with the ARRAY flag variables for the grid active on THIS pe so the flags can be read in from the namelist.
Private Attributes
character(len=80), pointer grid_name
character(len=120), pointer grid_file
integer, pointer grid_type
integer, pointer hord_mt
integer, pointer kord_mt
integer, pointer kord_wz
integer, pointer hord_vt
integer, pointer hord_tm
integer, pointer hord_dp
integer, pointer kord_tm
integer, pointer hord_tr
integer, pointer kord_tr
real, pointer scale_z
real, pointer w_max
real, pointer z_min
real, pointer lim_fac
integer, pointer nord
integer, pointer nord_tr
real, pointer dddmp
real, pointer d2_bg
real, pointer d4_bg
real, pointer vtdm4
real, pointer trdm2
real, pointer d2_bg_k1
real, pointer d2_bg_k2
real, pointer d2_divg_max_k1
real, pointer d2_divg_max_k2
real, pointer damp_k_k1
real, pointer damp_k_k2
integer, pointer n_zs_filter
integer, pointer nord_zs_filter
logical, pointer full_zs_filter
logical, pointer rf_fast
logical, pointer consv_am
logical, pointer do_sat_adj
logical, pointer do_f3d
logical, pointer no_dycore
logical, pointer convert_ke
logical, pointer do_vort_damp
logical, pointer use_old_omega
real, pointer beta
integer, pointer n_sponge
real, pointer d_ext
integer, pointer nwat
logical, pointer warm_start
logical, pointer inline_q
real, pointer shift_fac
logical, pointer do_schmidt
real(kind=r_grid), pointer stretch_fac
real(kind=r_grid), pointer target_lat
real(kind=r_grid), pointer target_lon
logical, pointer reset_eta
real, pointer p_fac
real, pointer a_imp
integer, pointer n_split
real, pointer fac_n_spl
real, pointer fhouri
integer, pointer m_split
integer, pointer k_split
logical, pointer use_logp
integer, pointer q_split
integer, pointer print_freq
logical, pointer write_3d_diags
integer, pointer npx
integer, pointer npy
integer, pointer npz
integer, pointer npz_rst
integer, pointer ncnst
integer, pointer pnats
integer, pointer dnats
integer, pointer ntiles
integer, pointer nf_omega
integer, pointer fv_sg_adj
integer, pointer na_init
logical, pointer nudge_dz
real, pointer p_ref
real, pointer dry_mass
integer, pointer nt_prog
integer, pointer nt_phys
real, pointer tau_h2o
real, pointer delt_max
real, pointer d_con
real, pointer ke_bg
real, pointer consv_te
real, pointer tau
real, pointer rf_cutoff
logical, pointer filter_phys
logical, pointer dwind_2d
logical, pointer breed_vortex_inline
logical, pointer range_warn
logical, pointer fill
logical, pointer fill_dp
logical, pointer fill_wz
logical, pointer check_negative
logical, pointer non_ortho
logical, pointer adiabatic
logical, pointer moist_phys
logical, pointer do_held_suarez
logical, pointer do_reed_physics
logical, pointer reed_cond_only
logical, pointer reproduce_sum
logical, pointer adjust_dry_mass
logical, pointer fv_debug
logical, pointer srf_init
logical, pointer mountain
logical, pointer remap_t
logical, pointer z_tracer
logical, pointer old_divg_damp
logical, pointer fv_land
logical, pointer nudge
logical, pointer nudge_ic
logical, pointer ncep_ic
logical, pointer nggps_ic
logical, pointer ecmwf_ic
logical, pointer gfs_phil
logical, pointer agrid_vel_rst
logical, pointer use_new_ncep
logical, pointer use_ncep_phy
logical, pointer fv_diag_ic
logical, pointer external_ic
logical, pointer external_eta
logical, pointer read_increment
character(len=128), pointer res_latlon_dynamics
character(len=128), pointer res_latlon_tracers
logical, pointer hydrostatic
logical, pointer phys_hydrostatic
logical, pointer use_hydro_pressure
logical, pointer do_uni_zfull
logical, pointer adj_mass_vmr
logical, pointer hybrid_z
logical, pointer make_nh
logical, pointer make_hybrid_z
logical, pointer nudge_qv
real, pointer add_noise
integer, pointer a2b_ord
integer, pointer c2l_ord
integer, pointer ndims
real(kind=r_grid), pointer dx_const
real(kind=r_grid), pointer dy_const
real(kind=r_grid), pointer deglon_start
real(kind=r_grid), pointer deglon_stop
real(kind=r_grid), pointer deglat_start
real(kind=r_grid), pointer deglat_stop
real(kind=r_grid), pointer deglat
logical, pointer nested
logical, pointer twowaynest
logical, pointer regional
integer, pointer bc_update_interval
integer, pointer parent_tile
integer, pointer refinement
integer, pointer nestbctype
integer, pointer nestupdate
integer, pointer nsponge
integer, pointer ioffset
integer, pointer joffset
real, pointer s_weight
real, pointer update_blend
integer, dimension(:), pointer layout
integer, dimension(:), pointer io_layout
integer ntilesme
real too_big = 1.E35
integer commid
integer max_refinement_of_global = 1.
integer gid
real umax = 350.
max wave speed for grid_type>3
integer parent_grid_num = -1
integer halo_update_type = 1
1 for two-interfaces non-block 2 for block 3 for four-interfaces non-block
Detailed Description
The module 'FV3_control' is for initialization and termination of the model, and controls namelist parameters in FV3.
Definition at line 29 of file fv_control.F90.
Member Function/Subroutine Documentation
subroutine, public fv_control_mod::fv_end (type(fv_atmos_type), dimension(:), intent(inout) Atm, logical, dimension(:), intent(inout) grids_on_this_pe, logical, intent(in) restart_endfcst)
The subroutine 'fv_end' terminates FV3, deallocates memory, saves restart files, and stops I/O.
Definition at line 595 of file fv_control.F90.
References fv_arrays_mod::deallocate_fv_atmos_type(), fv_io_mod::fv_io_exit(), fv_restart_mod::fv_restart_end(), fv_grid_utils_mod::grid_utils_end(), fv_timing_mod::timing_off(), and fv_timing_mod::timing_prt().
Referenced by atmosphere_mod::atmosphere_end().
subroutine, public fv_control_mod::fv_init (type(fv_atmos_type), dimension(:), intent(inout), allocatable, target Atm, real, intent(in) dt_atmos, logical, dimension(:), intent(inout), allocatable grids_on_this_pe, integer, intent(inout) p_split)
The subroutine 'fv_init' initializes FV3.
It allocates memory, sets up MPI and processor lists, sets up the grid, and controls FV3 namelist parameters.
Definition at line 372 of file fv_control.F90.
References fv_arrays_mod::allocate_fv_atmos_type(), fv_restart_mod::fv_restart_init(), fv_grid_utils_mod::grid_utils_init(), fv_grid_tools_mod::init_grid(), init_nesting(), run_setup(), setup_pointers(), fv_timing_mod::timing_init(), and fv_timing_mod::timing_on().
Referenced by atmosphere_mod::atmosphere_init().
subroutine fv_control_mod::init_nesting (type(fv_atmos_type), dimension(:), intent(inout), allocatable Atm, logical, dimension(:), intent(inout), allocatable grids_on_this_pe, integer, intent(inout) p_split) [private]
Definition at line 1049 of file fv_control.F90.
Referenced by fv_init().
subroutine fv_control_mod::run_setup (type(fv_atmos_type), dimension(:), intent(inout), target Atm, real, intent(in) dt_atmos, logical, dimension(:), intent(inout) grids_on_this_pe, integer, intent(inout) p_split) [private]
The subroutine 'run_setup' initializes the run from a namelist.
Definition at line 623 of file fv_control.F90.
References fv_diagnostics_mod::fv_diag_init_gn(), multi_gases_mod::multi_gases_init(), and setup_pointers().
Referenced by fv_init().
subroutine fv_control_mod::setup_pointers (type(fv_atmos_type), intent(inout), target Atm) [private]
The subroutine 'setup_pointers' associates the MODULE flag pointers with the ARRAY flag variables for the grid active on THIS pe so the flags can be read in from the namelist.
Definition at line 1173 of file fv_control.F90.
Referenced by fv_init(), and run_setup().
Member Data Documentation
integer, pointer fv_control_mod::a2b_ord [private]
Definition at line 320 of file fv_control.F90.
real, pointer fv_control_mod::a_imp [private]
Definition at line 230 of file fv_control.F90.
real, pointer fv_control_mod::add_noise [private]
Definition at line 318 of file fv_control.F90.
logical, pointer fv_control_mod::adiabatic [private]
Definition at line 279 of file fv_control.F90.
logical, pointer fv_control_mod::adj_mass_vmr [private]
Definition at line 313 of file fv_control.F90.
logical, pointer fv_control_mod::adjust_dry_mass [private]
Definition at line 285 of file fv_control.F90.
logical, pointer fv_control_mod::agrid_vel_rst [private]
Definition at line 300 of file fv_control.F90.
integer, pointer fv_control_mod::bc_update_interval [private]
Definition at line 333 of file fv_control.F90.
real, pointer fv_control_mod::beta [private]
Definition at line 216 of file fv_control.F90.
logical, pointer fv_control_mod::breed_vortex_inline [private]
Definition at line 272 of file fv_control.F90.
integer, pointer fv_control_mod::c2l_ord [private]
Definition at line 321 of file fv_control.F90.
logical, pointer fv_control_mod::check_negative [private]
Definition at line 277 of file fv_control.F90.
integer fv_control_mod::commid [private]
Definition at line 350 of file fv_control.F90.
logical, pointer fv_control_mod::consv_am [private]
Definition at line 208 of file fv_control.F90.
real, pointer fv_control_mod::consv_te [private]
Definition at line 267 of file fv_control.F90.
logical, pointer fv_control_mod::convert_ke [private]
Definition at line 212 of file fv_control.F90.
real, pointer fv_control_mod::d2_bg [private]
Definition at line 193 of file fv_control.F90.
real, pointer fv_control_mod::d2_bg_k1 [private]
Definition at line 197 of file fv_control.F90.
real, pointer fv_control_mod::d2_bg_k2 [private]
Definition at line 198 of file fv_control.F90.
real, pointer fv_control_mod::d2_divg_max_k1 [private]
Definition at line 199 of file fv_control.F90.
real, pointer fv_control_mod::d2_divg_max_k2 [private]
Definition at line 200 of file fv_control.F90.
real, pointer fv_control_mod::d4_bg [private]
Definition at line 194 of file fv_control.F90.
real, pointer fv_control_mod::d_con [private]
Definition at line 265 of file fv_control.F90.
real, pointer fv_control_mod::d_ext [private]
Definition at line 218 of file fv_control.F90.
real, pointer fv_control_mod::damp_k_k1 [private]
Definition at line 201 of file fv_control.F90.
real, pointer fv_control_mod::damp_k_k2 [private]
Definition at line 202 of file fv_control.F90.
real, pointer fv_control_mod::dddmp [private]
Definition at line 192 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::deglat [private]
Definition at line 329 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::deglat_start [private]
Definition at line 327 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::deglat_stop [private]
Definition at line 327 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::deglon_start [private]
Definition at line 327 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::deglon_stop [private]
Definition at line 327 of file fv_control.F90.
real, pointer fv_control_mod::delt_max [private]
Definition at line 264 of file fv_control.F90.
integer, pointer fv_control_mod::dnats [private]
Definition at line 251 of file fv_control.F90.
logical, pointer fv_control_mod::do_f3d [private]
Definition at line 210 of file fv_control.F90.
logical, pointer fv_control_mod::do_held_suarez [private]
Definition at line 281 of file fv_control.F90.
logical, pointer fv_control_mod::do_reed_physics [private]
Definition at line 282 of file fv_control.F90.
logical, pointer fv_control_mod::do_sat_adj [private]
Definition at line 209 of file fv_control.F90.
logical, pointer fv_control_mod::do_schmidt [private]
Definition at line 223 of file fv_control.F90.
logical, pointer fv_control_mod::do_uni_zfull [private]
Definition at line 312 of file fv_control.F90.
logical, pointer fv_control_mod::do_vort_damp [private]
Definition at line 213 of file fv_control.F90.
real, pointer fv_control_mod::dry_mass [private]
Definition at line 259 of file fv_control.F90.
logical, pointer fv_control_mod::dwind_2d [private]
Definition at line 271 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::dx_const [private]
Definition at line 325 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::dy_const [private]
Definition at line 326 of file fv_control.F90.
logical, pointer fv_control_mod::ecmwf_ic [private]
Definition at line 298 of file fv_control.F90.
logical, pointer fv_control_mod::external_eta [private]
Definition at line 305 of file fv_control.F90.
logical, pointer fv_control_mod::external_ic [private]
Definition at line 304 of file fv_control.F90.
real, pointer fv_control_mod::fac_n_spl [private]
Definition at line 233 of file fv_control.F90.
real, pointer fv_control_mod::fhouri [private]
Definition at line 234 of file fv_control.F90.
logical, pointer fv_control_mod::fill [private]
Definition at line 274 of file fv_control.F90.
logical, pointer fv_control_mod::fill_dp [private]
Definition at line 275 of file fv_control.F90.
logical, pointer fv_control_mod::fill_wz [private]
Definition at line 276 of file fv_control.F90.
logical, pointer fv_control_mod::filter_phys [private]
Definition at line 270 of file fv_control.F90.
logical, pointer fv_control_mod::full_zs_filter [private]
Definition at line 205 of file fv_control.F90.
logical, pointer fv_control_mod::fv_debug [private]
Definition at line 286 of file fv_control.F90.
logical, pointer fv_control_mod::fv_diag_ic [private]
Definition at line 303 of file fv_control.F90.
logical, pointer fv_control_mod::fv_land [private]
Definition at line 293 of file fv_control.F90.
integer, pointer fv_control_mod::fv_sg_adj [private]
Definition at line 254 of file fv_control.F90.
logical, pointer fv_control_mod::gfs_phil [private]
Definition at line 299 of file fv_control.F90.
integer fv_control_mod::gid [private]
Definition at line 351 of file fv_control.F90.
character(len=120), pointer fv_control_mod::grid_file [private]
Definition at line 174 of file fv_control.F90.
character(len=80), pointer fv_control_mod::grid_name [private]
Definition at line 173 of file fv_control.F90.
integer, pointer fv_control_mod::grid_type [private]
Definition at line 175 of file fv_control.F90.
integer fv_control_mod::halo_update_type = 1 [private]
1 for two-interfaces non-block 2 for block 3 for four-interfaces non-block
Definition at line 356 of file fv_control.F90.
integer, pointer fv_control_mod::hord_dp [private]
Definition at line 181 of file fv_control.F90.
integer, pointer fv_control_mod::hord_mt [private]
Definition at line 176 of file fv_control.F90.
integer, pointer fv_control_mod::hord_tm [private]
Definition at line 180 of file fv_control.F90.
integer, pointer fv_control_mod::hord_tr [private]
Definition at line 183 of file fv_control.F90.
integer, pointer fv_control_mod::hord_vt [private]
Definition at line 179 of file fv_control.F90.
logical, pointer fv_control_mod::hybrid_z [private]
Definition at line 314 of file fv_control.F90.
logical, pointer fv_control_mod::hydrostatic [private]
Definition at line 309 of file fv_control.F90.
logical, pointer fv_control_mod::inline_q [private]
Definition at line 221 of file fv_control.F90.
integer, dimension(:), pointer fv_control_mod::io_layout [private]
Definition at line 337 of file fv_control.F90.
integer, pointer fv_control_mod::ioffset [private]
Definition at line 334 of file fv_control.F90.
integer, pointer fv_control_mod::joffset [private]
Definition at line 334 of file fv_control.F90.
integer, pointer fv_control_mod::k_split [private]
Definition at line 237 of file fv_control.F90.
real, pointer fv_control_mod::ke_bg [private]
Definition at line 266 of file fv_control.F90.
integer, pointer fv_control_mod::kord_mt [private]
Definition at line 177 of file fv_control.F90.
integer, pointer fv_control_mod::kord_tm [private]
Definition at line 182 of file fv_control.F90.
integer, pointer fv_control_mod::kord_tr [private]
Definition at line 184 of file fv_control.F90.
integer, pointer fv_control_mod::kord_wz [private]
Definition at line 178 of file fv_control.F90.
integer, dimension(:), pointer fv_control_mod::layout [private]
Definition at line 337 of file fv_control.F90.
real, pointer fv_control_mod::lim_fac [private]
Definition at line 188 of file fv_control.F90.
integer, pointer fv_control_mod::m_split [private]
Definition at line 236 of file fv_control.F90.
logical, pointer fv_control_mod::make_hybrid_z [private]
Definition at line 316 of file fv_control.F90.
logical, pointer fv_control_mod::make_nh [private]
Definition at line 315 of file fv_control.F90.
integer fv_control_mod::max_refinement_of_global = 1. [private]
Definition at line 350 of file fv_control.F90.
logical, pointer fv_control_mod::moist_phys [private]
Definition at line 280 of file fv_control.F90.
logical, pointer fv_control_mod::mountain [private]
Definition at line 288 of file fv_control.F90.
integer, pointer fv_control_mod::n_split [private]
Definition at line 231 of file fv_control.F90.
integer, pointer fv_control_mod::n_sponge [private]
Definition at line 217 of file fv_control.F90.
integer, pointer fv_control_mod::n_zs_filter [private]
Definition at line 203 of file fv_control.F90.
integer, pointer fv_control_mod::na_init [private]
Definition at line 256 of file fv_control.F90.
logical, pointer fv_control_mod::ncep_ic [private]
Definition at line 296 of file fv_control.F90.
integer, pointer fv_control_mod::ncnst [private]
Definition at line 249 of file fv_control.F90.
integer, pointer fv_control_mod::ndims [private]
Definition at line 323 of file fv_control.F90.
integer, pointer fv_control_mod::nestbctype [private]
Definition at line 334 of file fv_control.F90.
logical, pointer fv_control_mod::nested [private]
Definition at line 331 of file fv_control.F90.
integer, pointer fv_control_mod::nestupdate [private]
Definition at line 334 of file fv_control.F90.
integer, pointer fv_control_mod::nf_omega [private]
Definition at line 253 of file fv_control.F90.
logical, pointer fv_control_mod::nggps_ic [private]
Definition at line 297 of file fv_control.F90.
integer, public fv_control_mod::ngrids = 1
Definition at line 348 of file fv_control.F90.
logical, pointer fv_control_mod::no_dycore [private]
Definition at line 211 of file fv_control.F90.
logical, pointer fv_control_mod::non_ortho [private]
Definition at line 278 of file fv_control.F90.
integer, pointer fv_control_mod::nord [private]
Definition at line 190 of file fv_control.F90.
integer, pointer fv_control_mod::nord_tr [private]
Definition at line 191 of file fv_control.F90.
integer, pointer fv_control_mod::nord_zs_filter [private]
Definition at line 204 of file fv_control.F90.
integer, pointer fv_control_mod::npx [private]
Definition at line 244 of file fv_control.F90.
integer, pointer fv_control_mod::npy [private]
Definition at line 245 of file fv_control.F90.
integer, pointer fv_control_mod::npz [private]
Definition at line 246 of file fv_control.F90.
integer, pointer fv_control_mod::npz_rst [private]
Definition at line 247 of file fv_control.F90.
integer, pointer fv_control_mod::nsponge [private]
Definition at line 334 of file fv_control.F90.
integer, pointer fv_control_mod::nt_phys [private]
Definition at line 261 of file fv_control.F90.
integer, pointer fv_control_mod::nt_prog [private]
Definition at line 260 of file fv_control.F90.
integer, pointer fv_control_mod::ntiles [private]
Definition at line 252 of file fv_control.F90.
integer fv_control_mod::ntilesme [private]
Definition at line 339 of file fv_control.F90.
logical, pointer fv_control_mod::nudge [private]
Definition at line 294 of file fv_control.F90.
logical, pointer fv_control_mod::nudge_dz [private]
Definition at line 257 of file fv_control.F90.
logical, pointer fv_control_mod::nudge_ic [private]
Definition at line 295 of file fv_control.F90.
logical, pointer fv_control_mod::nudge_qv [private]
Definition at line 317 of file fv_control.F90.
integer, pointer fv_control_mod::nwat [private]
Definition at line 219 of file fv_control.F90.
logical, pointer fv_control_mod::old_divg_damp [private]
Definition at line 292 of file fv_control.F90.
real, pointer fv_control_mod::p_fac [private]
Definition at line 229 of file fv_control.F90.
real, pointer fv_control_mod::p_ref [private]
Definition at line 258 of file fv_control.F90.
integer fv_control_mod::parent_grid_num = -1 [private]
Definition at line 354 of file fv_control.F90.
integer, pointer fv_control_mod::parent_tile [private]
Definition at line 334 of file fv_control.F90.
integer, dimension(:), allocatable, public fv_control_mod::pelist_all
Definition at line 349 of file fv_control.F90.
logical, pointer fv_control_mod::phys_hydrostatic [private]
Definition at line 310 of file fv_control.F90.
integer, pointer fv_control_mod::pnats [private]
Definition at line 250 of file fv_control.F90.
integer, pointer fv_control_mod::print_freq [private]
Definition at line 241 of file fv_control.F90.
integer, pointer fv_control_mod::q_split [private]
Definition at line 240 of file fv_control.F90.
logical, pointer fv_control_mod::range_warn [private]
Definition at line 273 of file fv_control.F90.
logical, pointer fv_control_mod::read_increment [private]
Definition at line 306 of file fv_control.F90.
logical, pointer fv_control_mod::reed_cond_only [private]
Definition at line 283 of file fv_control.F90.
integer, pointer fv_control_mod::refinement [private]
Definition at line 334 of file fv_control.F90.
logical, pointer fv_control_mod::regional [private]
Definition at line 332 of file fv_control.F90.
logical, pointer fv_control_mod::remap_t [private]
Definition at line 289 of file fv_control.F90.
logical, pointer fv_control_mod::reproduce_sum [private]
Definition at line 284 of file fv_control.F90.
character(len=128), pointer fv_control_mod::res_latlon_dynamics [private]
Definition at line 307 of file fv_control.F90.
character(len=128), pointer fv_control_mod::res_latlon_tracers [private]
Definition at line 308 of file fv_control.F90.
logical, pointer fv_control_mod::reset_eta [private]
Definition at line 228 of file fv_control.F90.
real, pointer fv_control_mod::rf_cutoff [private]
Definition at line 269 of file fv_control.F90.
logical, pointer fv_control_mod::rf_fast [private]
Definition at line 207 of file fv_control.F90.
real, pointer fv_control_mod::s_weight [private]
Definition at line 335 of file fv_control.F90.
real, pointer fv_control_mod::scale_z [private]
Definition at line 185 of file fv_control.F90.
real, pointer fv_control_mod::shift_fac [private]
Definition at line 222 of file fv_control.F90.
logical, pointer fv_control_mod::srf_init [private]
Definition at line 287 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::stretch_fac [private]
Definition at line 224 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::target_lat [private]
Definition at line 225 of file fv_control.F90.
real(kind=r_grid), pointer fv_control_mod::target_lon [private]
Definition at line 226 of file fv_control.F90.
real, pointer fv_control_mod::tau [private]
Definition at line 268 of file fv_control.F90.
real, pointer fv_control_mod::tau_h2o [private]
Definition at line 262 of file fv_control.F90.
real fv_control_mod::too_big = 1.E35 [private]
Definition at line 344 of file fv_control.F90.
real, pointer fv_control_mod::trdm2 [private]
Definition at line 196 of file fv_control.F90.
logical, pointer fv_control_mod::twowaynest [private]
Definition at line 331 of file fv_control.F90.
real fv_control_mod::umax = 350. [private]
max wave speed for grid_type>3
Definition at line 353 of file fv_control.F90.
real, pointer fv_control_mod::update_blend [private]
Definition at line 335 of file fv_control.F90.
logical, pointer fv_control_mod::use_hydro_pressure [private]
Definition at line 311 of file fv_control.F90.
logical, pointer fv_control_mod::use_logp [private]
Definition at line 238 of file fv_control.F90.
logical, pointer fv_control_mod::use_ncep_phy [private]
Definition at line 302 of file fv_control.F90.
logical, pointer fv_control_mod::use_new_ncep [private]
Definition at line 301 of file fv_control.F90.
logical, pointer fv_control_mod::use_old_omega [private]
Definition at line 214 of file fv_control.F90.
real, pointer fv_control_mod::vtdm4 [private]
Definition at line 195 of file fv_control.F90.
real, pointer fv_control_mod::w_max [private]
Definition at line 186 of file fv_control.F90.
logical, pointer fv_control_mod::warm_start [private]
Definition at line 220 of file fv_control.F90.
logical, pointer fv_control_mod::write_3d_diags [private]
Definition at line 242 of file fv_control.F90.
real, pointer fv_control_mod::z_min [private]
Definition at line 187 of file fv_control.F90.
logical, pointer fv_control_mod::z_tracer [private]
Definition at line 290 of file fv_control.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_control.F90