fv_regional_mod Module Reference
Data Types
interface dump_field
type fv_domain_sides
type fv_regional_bc_variables
Public Member Functions
subroutine, public setup_regional_bc (Atm, isd, ied, jsd, jed, npx, npy)
subroutine, public start_regional_cold_start (Atm, ak, bk, levp, is, ie, js, je, isd, ied, jsd, jed)
subroutine, public start_regional_restart (Atm, isc, iec, jsc, jec, isd, ied, jsd, jed)
subroutine, public read_new_bc_data (Atm, Time, Time_step_atmos, p_split, isd, ied, jsd, jed)
subroutine, public regional_bc_data (Atm, bc_hour, is, ie, js, je, isd, ied, jsd, jed, ak, bk)
subroutine, public set_regional_bcs (delp, delz, w, pt
subroutine, public regional_boundary_update (array, bc_vbl_name, lbnd_x, ubnd_x, lbnd_y, ubnd_y, ubnd_z, is, ie, js, je, isd, ied, jsd, jed, fcst_time, index4)
subroutine, public regional_bc_t1_to_t0 (BC_t1, BC_t0, nlev, ntracers, bnds)
subroutine, public exch_uv (domain, bd, npz, u, v)
subroutine, public get_data_source (source, regional)
Public Attributes
integer, parameter, public h_stagger = 1
integer, parameter, public u_stagger = 2
integer, parameter, public v_stagger = 3
real, public current_time_in_seconds
integer, save, public next_time_to_read_bcs
integer, save, public bc_hour
integer, save, public ntimesteps_per_bc_update
real, dimension(:),
*
allocatable, public ak_in
real, dimension(:),
*
allocatable, public bk_in
logical, save, public begin_regional_restart =.true.
type(fv_domain_sides), target,
*
save, public bc_t0
type(fv_domain_sides), target,
*
save, public bc_t1
-- Boundary values for all BC variables at successive times from the regional BC file
integer, public a_step
integer, public p_step
integer, public k_step
integer, public n_step
Private Member Functions
subroutine read_regional_bc_file (is_input, ie_input, js_input, je_input, nlev, ntracers, var_name_root, array_3d, array_4d, tlev, required)
subroutine check (status)
subroutine allocate_regional_bc_arrays (side, north_bc, south_bc, east_bc, west_bc, is_0, ie_0, js_0, je_0, is_sn, ie_sn, js_sn, je_sn, is_we, ie_we, js_we, je_we, klev, ntracers, BC_side)
subroutine remap_scalar_nggps_regional_bc (Atm, side, isd, ied, jsd, jed, is_bc, ie_bc, js_bc, je_bc, km, npz, ncnst, ak0, bk0, psc, t_in, qa, omga, zh, phis_reg, ps, BC_side)
subroutine remap_dwinds_regional_bc (Atm, is_input, ie_input, js_input, je_input, is_u, ie_u, js_u, je_u, is_v, ie_v, js_v, je_v, km, npz, ak0, bk0, psc, ud, vd, uc, vc, BC_side)
subroutine retrieve_bc_variable_data (bc_vbl_name, bc_side_t0, bc_side_t1, bc_t0, bc_t1, lbnd1, ubnd1, lbnd2, ubnd2, iq)
subroutine bc_time_interpolation (array, lbnd_x, ubnd_x, lbnd_y, ubnd_y, ubnd_z, bc_t0, bc_t1, lbnd1, ubnd1, lbnd2, ubnd2, i1, i2, j1, j2, fcst_time, bc_update_interval)
subroutine bc_time_interpolation_general (is, ie, js, je, is_s, ie_s, js_s, je_s, is_w, ie_w, js_w, je_w, fraction, t0, t1, Atm)
subroutine convert_to_virt_pot_temp (isd, ied, jsd, jed, npz, sphum, liq_wat)
subroutine p_maxmin (qname, q, is, ie, js, je, km, fac)
subroutine pmaxmn (qname, q, is, ie, js, je, km, fac, area, domain)
subroutine fillq (im, km, nq, q, dp)
subroutine mp_auto_conversion (ql, qr, qi, qs)
subroutine nudge_qv_bc (Atm, isd, ied, jsd, jed)
subroutine dump_field_3d (domain, name, field, isd, ied, jsd, jed, nlev, stag)
subroutine dump_field_2d (domain, name, field, isd, ied, jsd, jed, stag)
subroutine set_delp_and_tracers (BC_side, npz, nwat)
Private Attributes
integer, parameter nhalo_data =4
integer, parameter nhalo_model =3
real, parameter stretch_factor = 1.50
real, parameter target_lon = -97.5
real, parameter target_lat = 35.5
integer, parameter parent_tile = 6
integer, parameter refine_ratio = 3
integer, parameter cube_res = 96
integer, parameter istart_nest = 26
integer, parameter jstart_nest = 36
integer, parameter iend_nest = 167
integer, parameter jend_nest = 165
integer, save ncid
integer, save npz
integer, save ntracers
integer, save liq_water_index
integer, save sphum_index
-- Locations of tracer vbls in the tracers array
real(kind=r_grid), dimension(:,:,:),
*
allocatable agrid_reg
-- Lon/lat of cell centers
real(kind=r_grid), dimension(:,:,:),
*
allocatable grid_reg
-- Lon/lat of cell corners
real, dimension(:,:), allocatable phis_reg
-- Filtered sfc geopotential
logical, save north_bc
logical, save south_bc
logical, save east_bc
logical, save west_bc
type(fv_regional_bc_variables),
*
pointer, save bc_north_t0
type(fv_regional_bc_variables),
*
pointer, save bc_south_t0
type(fv_regional_bc_variables),
*
pointer, save bc_west_t0
type(fv_regional_bc_variables),
*
pointer, save bc_east_t0
type(fv_regional_bc_variables),
*
pointer, save bc_north_t1
type(fv_regional_bc_variables),
*
pointer, save bc_south_t1
type(fv_regional_bc_variables),
*
pointer, save bc_west_t1
type(fv_regional_bc_variables),
*
pointer, save bc_east_t1
type(fv_regional_bc_variables),
*
pointer bc_side_t0
type(fv_regional_bc_variables),
*
pointer bc_side_t1
type(fv_regional_bc_bounds_type),
*
pointer, save regional_bounds
real, parameter tice =273.16
real, parameter t_i0 =15.
real, parameter c_liq = 4185.5
real, parameter c_ice = 1972.0
real, parameter zvir = rvgas/rdgas - 1.
real, parameter cv_air = cp_air - rdgas
real, parameter cv_vap = cp_vapor - rvgas
real, dimension(:), allocatable dum1d
real, dimension(:), allocatable pref
character(len=100) grid_data ='grid.tile7.halo4.nc'
character(len=100) oro_data ='oro_data.tile7.halo4.nc'
real, parameter real_snan =x'FFF7FFFFFFFFFFFF'
real(kind=r_grid), parameter dbl_snan =x'FFF7FFFFFFFFFFFF'
integer, save bc_update_interval
character(len=80) data_source
Detailed Description
Definition at line 22 of file fv_regional_bc.F90.
Member Function/Subroutine Documentation
subroutine fv_regional_mod::allocate_regional_bc_arrays (character(len=5), intent(in) side, logical, intent(in) north_bc, logical, intent(in) south_bc, logical, intent(in) east_bc, logical, intent(in) west_bc, integer, intent(in) is_0, integer, intent(in) ie_0, integer, intent(in) js_0, integer, intent(in) je_0, integer, intent(in) is_sn, integer, intent(in) ie_sn, integer, intent(in) js_sn, integer, intent(in) je_sn, integer, intent(in) is_we, integer, intent(in) ie_we, integer, intent(in) js_we, integer, intent(in) je_we, integer, intent(in) klev, integer, intent(in) ntracers, type(fv_regional_bc_variables), intent(out) BC_side) [private]
Parameters
in je_0 -- Start/end BC indices for cell centers
in je_sn -- Start/end BC indices for south/north cell edges
in je_we -- Start/end BC indices for west/east cell edges
in side -- Which side are we allocating?
in west_bc -- Which sides is this task on?
out bc_side -- The BC arrays are already allocated so exit.
Definition at line 2601 of file fv_regional_bc.F90.
Referenced by setup_regional_bc().
subroutine fv_regional_mod::bc_time_interpolation (real, dimension(lbnd_x:ubnd_x,lbnd_y:ubnd_y,1:ubnd_z), intent(out) array, integer, intent(in) lbnd_x, integer, intent(in) ubnd_x, integer, intent(in) lbnd_y, integer, intent(in) ubnd_y, integer, intent(in) ubnd_z, real, dimension(lbnd1:ubnd1,lbnd2:ubnd2,1:ubnd_z) bc_t0, real, dimension(lbnd1:ubnd1,lbnd2:ubnd2,1:ubnd_z) bc_t1, integer, intent(in) lbnd1, integer, intent(in) ubnd1, integer, intent(in) lbnd2, integer, intent(in) ubnd2, integer, intent(in) i1, integer, intent(in) i2, integer, intent(in) j1, integer, intent(in) j2, real, intent(in) fcst_time, integer, intent(in) bc_update_interval) [private]
Parameters
in ubnd_z -- Dimensions of the array to be updated.
in ubnd2 -- Index limits of the BC arrays.
in j2 -- Index limits of the updated region.
in bc_update_interval -- Time (hours) between BC data states
in fcst_time -- Current forecast time (sec)
out array -- Update boundary points in this array.
Parameters
bc_t0 -- Interpolate between these
Definition at line 3843 of file fv_regional_bc.F90.
Referenced by regional_boundary_update().
subroutine fv_regional_mod::bc_time_interpolation_general (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) is_s, integer, intent(in) ie_s, integer, intent(in) js_s, integer, intent(in) je_s, integer, intent(in) is_w, integer, intent(in) ie_w, integer, intent(in) js_w, integer, intent(in) je_w, real, intent(in) fraction, type(fv_regional_bc_variables), intent(in) t0, type(fv_regional_bc_variables), intent(in) t1, type(fv_atmos_type), intent(inout) Atm) [private]
Parameters
in je_w -- Index limits for west/east edges of grid cells
in fraction -- Current time is this fraction between t0 ad t1.
in t1 -- BC variables at time levels t0 and t1.
in,out atm -- The Atm object
Parameters
je -- Index limits for centers of grid cells
je_s -- Index limits for south/north edges of grid cells
Definition at line 3924 of file fv_regional_bc.F90.
subroutine fv_regional_mod::check (integer, intent(in) status) [private]
Definition at line 2586 of file fv_regional_bc.F90.
Referenced by fv_grid_tools_mod::get_symmetry(), read_regional_bc_file(), read_regional_filtered_topo(), read_regional_lon_lat(), and regional_bc_data().
subroutine fv_regional_mod::convert_to_virt_pot_temp (integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npz, integer, intent(in) sphum, integer, intent(in) liq_wat) [private]
Definition at line 4267 of file fv_regional_bc.F90.
References compute_vpt().
Referenced by regional_bc_data().
subroutine fv_regional_mod::dump_field_2d (type(domain2d), intent(inout) domain, character(len=*), intent(in) name, real, dimension(isd:ied,jsd:jed), intent(inout) field, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) stag) [private]
Definition at line 4887 of file fv_regional_bc.F90.
subroutine fv_regional_mod::dump_field_3d (type(domain2d), intent(inout) domain, character(len=*), intent(in) name, real, dimension(isd:ied,jsd:jed,1:nlev), intent(inout) field, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) nlev, integer, intent(in) stag) [private]
Definition at line 4782 of file fv_regional_bc.F90.
subroutine, public fv_regional_mod::exch_uv (type(domain2d), intent(inout) domain, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npz, real, dimension (bd%isd:bd%ied ,bd%jsd:bd%jed+1,1:npz), intent(inout) u, real, dimension (bd%isd:bd%ied+1,bd%jsd:bd%jed ,1:npz), intent(inout) v)
Definition at line 4987 of file fv_regional_bc.F90.
Referenced by dyn_core_mod::dyn_core().
subroutine fv_regional_mod::fillq (integer, intent(in) im, integer, intent(in) km, integer, intent(in) nq, real, dimension(im,km,nq), intent(inout) q, real, dimension(im,km), intent(in) dp) [private]
Definition at line 4519 of file fv_regional_bc.F90.
Referenced by fv_sg_mod::neg_adj2(), fv_sg_mod::neg_adj3(), external_ic_mod::remap_scalar_ec(), external_ic_mod::remap_scalar_nggps(), remap_scalar_nggps_regional_bc(), and external_ic_mod::remap_scalar_single().
subroutine, public fv_regional_mod::get_data_source (character (len = 80) source, logical regional)
Definition at line 5167 of file fv_regional_bc.F90.
Referenced by external_ic_mod::get_nggps_ic(), start_regional_cold_start(), and start_regional_restart().
subroutine fv_regional_mod::mp_auto_conversion (real, intent(inout) ql, real, intent(inout) qr, real, intent(inout) qi, real, intent(inout) qs) [private]
Definition at line 4554 of file fv_regional_bc.F90.
Referenced by external_ic_mod::remap_scalar_nggps(), and remap_scalar_nggps_regional_bc().
subroutine fv_regional_mod::nudge_qv_bc (type(fv_atmos_type), intent(inout), target Atm, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed) [private]
Parameters
in jed -- Memory limits of task subdomain
in,out atm -- Atm object for the current domain
Definition at line 4574 of file fv_regional_bc.F90.
References get_q00().
Referenced by regional_bc_data().
subroutine fv_regional_mod::p_maxmin (character(len=*), intent(in) qname, real, dimension(is:ie, js:je, km), intent(in) q, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, real, intent(in) fac) [private]
Definition at line 4454 of file fv_regional_bc.F90.
Referenced by external_ic_mod::remap_scalar_ec(), external_ic_mod::remap_scalar_nggps(), and external_ic_mod::remap_scalar_single().
subroutine fv_regional_mod::pmaxmn (character(len=*), intent(in) qname, real, dimension(is:ie, js:je, km), intent(in) q, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, real, intent(in) fac, real(kind=r_grid), dimension(is-3:ie+3, js-3:je+3), intent(in) area, type(domain2d), intent(inout) domain) [private]
Definition at line 4482 of file fv_regional_bc.F90.
References fv_grid_utils_mod::g_sum().
Referenced by external_ic_mod::remap_scalar_ec(), and external_ic_mod::remap_scalar_nggps().
subroutine, public fv_regional_mod::read_new_bc_data (type(fv_atmos_type), intent(inout) Atm, type(time_type), intent(in) Time, type (time_type), intent(in) Time_step_atmos, integer, intent(in) p_split, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed)
Parameters
in,out atm -- Atm object for the current domain
in time -- Current forecast time
in time_step_atmos -- Large (physics) timestep
Parameters
jed -- Memory limits of task subdomain
Definition at line 1226 of file fv_regional_bc.F90.
References regional_bc_data(), and regional_bc_t1_to_t0().
Referenced by atmosphere_mod::atmosphere_dynamics().
subroutine fv_regional_mod::read_regional_bc_file (integer, intent(in) is_input, integer, intent(in) ie_input, integer, intent(in) js_input, integer, intent(in) je_input, integer, intent(in) nlev, integer, intent(in) ntracers, character(len=*), intent(in) var_name_root, real, dimension(is_input:ie_input,js_input:je_input,1:nlev), intent(out), optional array_3d, real, dimension(is_input:ie_input,js_input:je_input,1:nlev,1:ntracers), intent(out), optional array_4d, integer, intent(in), optional tlev, logical, intent(in), optional required) [private]
Parameters
in tlev -- Position of current tracer among all of them
in var_name_root -- Root of variable name in the boundary file
out array_3d -- The input 3-D variable's coverage of task subdomain
out array_4d -- The input 4-D variable's coverage of subdomain
Definition at line 2315 of file fv_regional_bc.F90.
References check().
Referenced by regional_bc_data().
subroutine, public fv_regional_mod::regional_bc_data (type(fv_atmos_type), intent(inout), target Atm, integer, intent(in) bc_hour, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, dimension(:), intent(in) ak, real, dimension(:), intent(in) bk)
Parameters
in bc_hour -- The forecast hour of the BC file to be read.
in jed -- Halo limits of task subdomain
in,out atm -- Atm object for the current domain
Parameters
je -- Compute limits of task subdomain
Definition at line 1307 of file fv_regional_bc.F90.
References fv_grid_utils_mod::cell_center2(), check(), convert_to_virt_pot_temp(), fill_divgd_bc(), fv_grid_utils_mod::get_latlon_vector(), fv_grid_utils_mod::get_unit_vect2(), fv_grid_utils_mod::inner_prod(), fv_grid_utils_mod::mid_pt_sphere(), nudge_qv_bc(), read_regional_bc_file(), remap_dwinds_regional_bc(), remap_scalar_nggps_regional_bc(), and set_delp_and_tracers().
Referenced by read_new_bc_data(), start_regional_cold_start(), and start_regional_restart().
subroutine, public fv_regional_mod::regional_bc_t1_to_t0 (type(fv_domain_sides), intent(in), target BC_t1, type(fv_domain_sides), intent(inout), target BC_t0, integer, intent(in) nlev, integer, intent(in) ntracers, type(fv_regional_bc_bounds_type), intent(in) bnds)
Parameters
in ntracers -- # of advected tracers
in bnds -- Index limits for all types of vbls in boundary region
Parameters
nlev -- # of model layers.
Definition at line 4061 of file fv_regional_bc.F90.
Referenced by read_new_bc_data(), and start_regional_cold_start().
subroutine, public fv_regional_mod::regional_boundary_update (real, dimension(lbnd_x:ubnd_x,lbnd_y:ubnd_y,1:ubnd_z), intent(out) array, character(len=*), intent(in) bc_vbl_name, integer, intent(in) lbnd_x, integer, intent(in) ubnd_x, integer, intent(in) lbnd_y, integer, intent(in) ubnd_y, integer, intent(in) ubnd_z, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, intent(in) fcst_time, integer, intent(in), optional index4)
Parameters
in ubnd_z -- Dimensions of full prognostic array to be updated.
in jed -- Memory limits
in index4 -- Index for the 4-D tracer array.
in fcst_time -- Forecast time (sec) at which BC update is applied.
in bc_vbl_name -- Name of the variable to be updated.
out array -- Update this full array's boundary region.
Parameters
je -- Compute limits
Definition at line 3520 of file fv_regional_bc.F90.
References bc_time_interpolation(), and retrieve_bc_variable_data().
Referenced by dyn_core_mod::dyn_core(), fv_dynamics_mod::fv_dynamics(), and fv_tracer2d_mod::tracer_2d_nested().
subroutine fv_regional_mod::remap_dwinds_regional_bc (type(fv_atmos_type), intent(inout) Atm, integer, intent(in) is_input, integer, intent(in) ie_input, integer, intent(in) js_input, integer, intent(in) je_input, integer, intent(in) is_u, integer, intent(in) ie_u, integer, intent(in) js_u, integer, intent(in) je_u, integer, intent(in) is_v, integer, intent(in) ie_v, integer, intent(in) js_v, integer, intent(in) je_v, integer, intent(in) km, integer, intent(in) npz, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(is_input:ie_input,js_input:je_input), intent(in) psc, real, dimension(is_u:ie_u,js_u:je_u,km), intent(in) ud, real, dimension(is_v:ie_v,js_v:je_v,km), intent(in) vd, real, dimension(is_v:ie_v,js_v:je_v,km), intent(in) uc, real, dimension(is_u:ie_u,js_u:je_u,km), intent(in) vc, type(fv_regional_bc_variables), intent(inout) BC_side) [private]
Parameters
in je_input -- index limits of the boundary arrays with nahlo=nhalo_data
in je_u -- index limits of D-grid u in this boundary region
in je_v -- index limits of D-grid v in this boundary region
in npz -- # of levels in final 3-D integration variables
in,out bc_side -- The BC variables on a domain side at the final integration levels.
Parameters
km -- # of levels in 3-D input variables
Definition at line 3111 of file fv_regional_bc.F90.
References fv_mapz_mod::mappm().
Referenced by regional_bc_data().
subroutine fv_regional_mod::remap_scalar_nggps_regional_bc (type(fv_atmos_type), intent(inout) Atm, character(len=5), intent(in) side, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) is_bc, integer, intent(in) ie_bc, integer, intent(in) js_bc, integer, intent(in) je_bc, integer, intent(in) km, integer, intent(in) npz, integer, intent(in) ncnst, real, dimension(km+1), intent(in) ak0, real, dimension(km+1), intent(in) bk0, real, dimension(is_bc:ie_bc,js_bc:je_bc), intent(in) psc, real, dimension(is_bc:ie_bc,js_bc:je_bc,km), intent(in) t_in, real, dimension(is_bc:ie_bc,js_bc:je_bc,km,ncnst), intent(in) qa, real, dimension(is_bc:ie_bc,js_bc:je_bc,km), intent(in) omga, real, dimension(is_bc:ie_bc,js_bc:je_bc,km+1), intent(in) zh, real, dimension(isd-1:ied+1,jsd-1:jed+1), intent(inout) phis_reg, real, dimension(is_bc:ie_bc,js_bc:je_bc), intent(out) ps, type(fv_regional_bc_variables), intent(inout) BC_side) [private]
Parameters
in jed -- index limits of the Atm arrays w/halo=nhalo_model
in je_bc -- index limits of working arrays on boundary task subdomains (halo=nhalo_data)
in ncnst -- # of tracer variables
in,out phis_reg -- Filtered sfc geopotential from preprocessing.
out ps -- sfc p in regional domain boundary region
in,out bc_side -- The BC variables on a domain side at the final integration levels.
Parameters
km -- # of levels in 3-D input variables
npz -- # of levels in final 3-D integration variables
Definition at line 2678 of file fv_regional_bc.F90.
References fillq(), fv_fill_mod::fillz(), fv_mapz_mod::mappm(), and mp_auto_conversion().
Referenced by regional_bc_data().
subroutine fv_regional_mod::retrieve_bc_variable_data (character(len=*), intent(in) bc_vbl_name, type(fv_regional_bc_variables), pointer bc_side_t0, type(fv_regional_bc_variables), pointer bc_side_t1, real, dimension(:,:,:), pointer bc_t0, real, dimension(:,:,:), pointer bc_t1, integer, intent(out) lbnd1, integer, intent(out) ubnd1, integer, intent(out) lbnd2, integer, intent(out) ubnd2, integer, intent(in) iq) [private]
Parameters
in iq -- Index used by 4-D tracer array.
   bc_side_t1 -- Boundary states for the given domain side.
out ubnd2 -- Horizontal dimensions of boundary array
   bc_t1 -- Boundary state values for the desired variable.
Definition at line 3739 of file fv_regional_bc.F90.
Referenced by regional_boundary_update().
subroutine fv_regional_mod::set_delp_and_tracers (type(fv_regional_bc_variables), intent(inout) BC_side, integer npz, integer nwat) [private]
Parameters
in,out bc_side -- The BC variables on a domain side at the final integration levels.
Definition at line 5188 of file fv_regional_bc.F90.
Referenced by regional_bc_data().
subroutine, public fv_regional_mod::set_regional_bcs (real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(out) delp, real, dimension(bd%isd:,bd%jsd:,1:), intent(out) delz, real, dimension(bd%isd:,bd%jsd:,1:), intent(out) w, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(out) pt)
Definition at line 3230 of file fv_regional_bc.F90.
References bc_values_into_arrays().
Referenced by fv_dynamics_mod::fv_dynamics().
subroutine, public fv_regional_mod::setup_regional_bc (type(fv_atmos_type), intent(inout), target Atm, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npx, integer, intent(in) npy)
Parameters
in,out atm -- Atm object for the current domain
Definition at line 190 of file fv_regional_bc.F90.
References allocate_regional_bc_arrays(), compute_regional_bc_indices(), fv_eta_mod::get_eta_level(), read_regional_filtered_topo(), and read_regional_lon_lat().
Referenced by start_regional_cold_start(), and start_regional_restart().
subroutine, public fv_regional_mod::start_regional_cold_start (type(fv_atmos_type), intent(inout) Atm, real, dimension(1:levp+1), intent(in) ak, real, dimension(1:levp+1), intent(in) bk, integer, intent(in) levp, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed)
Parameters
in,out atm -- Atm object for the current domain
Parameters
je -- Integration limits of task subdomain
jed -- Memory limits of task subdomain
Definition at line 1065 of file fv_regional_bc.F90.
References get_data_source(), regional_bc_data(), regional_bc_t1_to_t0(), and setup_regional_bc().
Referenced by external_ic_mod::get_nggps_ic().
subroutine, public fv_regional_mod::start_regional_restart (type(fv_atmos_type), intent(inout) Atm, integer, intent(in) isc, integer, intent(in) iec, integer, intent(in) jsc, integer, intent(in) jec, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed)
Parameters
in,out atm -- Atm object for the current domain
in jed -- Memory limits of task subdomain
Parameters
jec -- Integration limits of task subdomain
Definition at line 1137 of file fv_regional_bc.F90.
References get_data_source(), regional_bc_data(), and setup_regional_bc().
Referenced by atmosphere_mod::atmosphere_init().
Member Data Documentation
integer, public fv_regional_mod::a_step
Definition at line 183 of file fv_regional_bc.F90.
real(kind=r_grid), dimension(:,:,:), allocatable fv_regional_mod::agrid_reg [private]
-- Lon/lat of cell centers
Definition at line 113 of file fv_regional_bc.F90.
real, dimension(:), allocatable, public fv_regional_mod::ak_in
Definition at line 118 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_east_t0 [private]
Definition at line 143 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_east_t1 [private]
Definition at line 143 of file fv_regional_bc.F90.
integer, save, public fv_regional_mod::bc_hour
Definition at line 111 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_north_t0 [private]
Definition at line 143 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_north_t1 [private]
Definition at line 143 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer fv_regional_mod::bc_side_t0 [private]
Definition at line 152 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer fv_regional_mod::bc_side_t1 [private]
Definition at line 152 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_south_t0 [private]
Definition at line 143 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_south_t1 [private]
Definition at line 143 of file fv_regional_bc.F90.
type(fv_domain_sides), target, save, public fv_regional_mod::bc_t0
Definition at line 141 of file fv_regional_bc.F90.
type(fv_domain_sides), target, save, public fv_regional_mod::bc_t1
-- Boundary values for all BC variables at successive times from the regional BC file
Definition at line 141 of file fv_regional_bc.F90.
integer, save fv_regional_mod::bc_update_interval [private]
Definition at line 181 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_west_t0 [private]
Definition at line 143 of file fv_regional_bc.F90.
type(fv_regional_bc_variables), pointer, save fv_regional_mod::bc_west_t1 [private]
Definition at line 143 of file fv_regional_bc.F90.
logical, save, public fv_regional_mod::begin_regional_restart =.true.
Definition at line 120 of file fv_regional_bc.F90.
real, dimension(:), allocatable, public fv_regional_mod::bk_in
Definition at line 118 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::c_ice = 1972.0 [private]
Definition at line 159 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::c_liq = 4185.5 [private]
Definition at line 158 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::cube_res = 96 [private]
Definition at line 96 of file fv_regional_bc.F90.
real, public fv_regional_mod::current_time_in_seconds
Definition at line 108 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::cv_air = cp_air - rdgas [private]
Definition at line 160 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::cv_vap = cp_vapor - rvgas [private]
Definition at line 160 of file fv_regional_bc.F90.
character(len=80) fv_regional_mod::data_source [private]
Definition at line 185 of file fv_regional_bc.F90.
real(kind=r_grid), parameter fv_regional_mod::dbl_snan =x'FFF7FFFFFFFFFFFF' [private]
Definition at line 174 of file fv_regional_bc.F90.
real, dimension(:), allocatable fv_regional_mod::dum1d [private]
Definition at line 164 of file fv_regional_bc.F90.
logical, save fv_regional_mod::east_bc [private]
Definition at line 120 of file fv_regional_bc.F90.
character(len=100) fv_regional_mod::grid_data ='grid.tile7.halo4.nc' [private]
Definition at line 166 of file fv_regional_bc.F90.
real(kind=r_grid), dimension(:,:,:), allocatable fv_regional_mod::grid_reg [private]
-- Lon/lat of cell corners
Definition at line 113 of file fv_regional_bc.F90.
integer, parameter, public fv_regional_mod::h_stagger = 1
Definition at line 86 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::iend_nest = 167 [private]
Definition at line 99 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::istart_nest = 26 [private]
Definition at line 97 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::jend_nest = 165 [private]
Definition at line 100 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::jstart_nest = 36 [private]
Definition at line 98 of file fv_regional_bc.F90.
integer, public fv_regional_mod::k_step
Definition at line 183 of file fv_regional_bc.F90.
integer, save fv_regional_mod::liq_water_index [private]
Definition at line 110 of file fv_regional_bc.F90.
integer, public fv_regional_mod::n_step
Definition at line 183 of file fv_regional_bc.F90.
integer, save fv_regional_mod::ncid [private]
Definition at line 109 of file fv_regional_bc.F90.
integer, save, public fv_regional_mod::next_time_to_read_bcs
Definition at line 109 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::nhalo_data =4 [private]
Definition at line 83 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::nhalo_model =3 [private]
Definition at line 83 of file fv_regional_bc.F90.
logical, save fv_regional_mod::north_bc [private]
Definition at line 120 of file fv_regional_bc.F90.
integer, save fv_regional_mod::npz [private]
Definition at line 109 of file fv_regional_bc.F90.
integer, save, public fv_regional_mod::ntimesteps_per_bc_update
Definition at line 111 of file fv_regional_bc.F90.
integer, save fv_regional_mod::ntracers [private]
Definition at line 109 of file fv_regional_bc.F90.
character(len=100) fv_regional_mod::oro_data ='oro_data.tile7.halo4.nc' [private]
Definition at line 166 of file fv_regional_bc.F90.
integer, public fv_regional_mod::p_step
Definition at line 183 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::parent_tile = 6 [private]
Definition at line 93 of file fv_regional_bc.F90.
real, dimension(:,:), allocatable fv_regional_mod::phis_reg [private]
-- Filtered sfc geopotential
Definition at line 116 of file fv_regional_bc.F90.
real, dimension(:), allocatable fv_regional_mod::pref [private]
Definition at line 164 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::real_snan =x'FFF7FFFFFFFFFFFF' [private]
Definition at line 172 of file fv_regional_bc.F90.
integer, parameter fv_regional_mod::refine_ratio = 3 [private]
Definition at line 94 of file fv_regional_bc.F90.
type(fv_regional_bc_bounds_type), pointer, save fv_regional_mod::regional_bounds [private]
Definition at line 154 of file fv_regional_bc.F90.
logical, save fv_regional_mod::south_bc [private]
Definition at line 120 of file fv_regional_bc.F90.
integer, save fv_regional_mod::sphum_index [private]
-- Locations of tracer vbls in the tracers array
Definition at line 110 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::stretch_factor = 1.50 [private]
Definition at line 90 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::t_i0 =15. [private]
Definition at line 156 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::target_lat = 35.5 [private]
Definition at line 92 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::target_lon = -97.5 [private]
Definition at line 91 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::tice =273.16 [private]
Definition at line 156 of file fv_regional_bc.F90.
integer, parameter, public fv_regional_mod::u_stagger = 2
Definition at line 87 of file fv_regional_bc.F90.
integer, parameter, public fv_regional_mod::v_stagger = 3
Definition at line 88 of file fv_regional_bc.F90.
logical, save fv_regional_mod::west_bc [private]
Definition at line 120 of file fv_regional_bc.F90.
real, parameter fv_regional_mod::zvir = rvgas/rdgas - 1. [private]
Definition at line 160 of file fv_regional_bc.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_regional_bc.F90