dyn_core_mod Module Reference
The module 'dyn_core' peforms the Lagrangian acoustic dynamics described by .
Public Member Functions
subroutine, public dyn_core (npx, npy, npz, ng, sphum, nq, bdt, n_split, zvir, cp, akap, cappa,
subroutine, public del2_cubed (q, cd, gridstruct, domain, npx, npy, km, nmax, bd)
The subroutine 'del2-cubed' filters the omega field for the physics.
subroutine, public init_ijk_mem (i1, i2, j1, j2, km, array, var)
Private Member Functions
subroutine pk3_halo (is, ie, js, je, isd, ied, jsd, jed, npz, ptop, akap, pk3, delp)
subroutine pln_halo (is, ie, js, je, isd, ied, jsd, jed, npz, ptop, pk3, delp)
subroutine pe_halo (is, ie, js, je, isd, ied, jsd, jed, npz, ptop, pe, delp)
subroutine adv_pe (ua, va, pem, om, gridstruct, bd, npx, npy, npz, ng)
subroutine p_grad_c (dt2, npz, delpc, pkc, gz, uc, vc, bd, rdxc, rdyc, hydrostatic)
subroutine nh_p_grad (u, v, pp, gz, delp, pk, dt, ng, gridstruct, bd, npx, npy, npz, use_logp)
subroutine split_p_grad (u, v, pp, gz, delp, pk, beta, dt, ng, gridstruct, bd, npx, npy, npz, use_logp)
subroutine one_grad_p (u, v, pk, gz, divg2, delp, dt, ng, gridstruct, bd, npx, npy, npz, ptop, hydrostatic, a2b_ord, d_ext)
subroutine grad1_p_update (divg2, u, v, pk, gz, dt, ng, gridstruct, bd, npx, npy, npz, ptop, beta, a2b_ord)
subroutine mix_dp (hydrostatic, w, delp, pt, km, ak, bk, CG, fv_debug, bd)
subroutine geopk (ptop, pe, peln, delp, pk, gz, hs, pt,
The subroutine 'geopk' calculates geopotential and pressure to the kappa.
subroutine ray_fast (dt, npx, npy, npz, pfull, tau, u, v, w, ks, dp, ptop, hydrostatic, rf_cutoff, bd)
The subroutine 'Ray_fast' computes a simple `inline` version of the Rayleigh friction (EXPERIMENTAL - NOT FOR GENERAL USE).
Private Attributes
real ptk
real peln1
real rgrav
real d3_damp
real, dimension(:,:,:), allocatable ut
real, dimension(:,:,:), allocatable vt
real, dimension(:,:,:), allocatable crx
real, dimension(:,:,:), allocatable cry
real, dimension(:,:,:), allocatable xfx
real, dimension(:,:,:), allocatable yfx
real, dimension(:,:,:), allocatable divgd
real, dimension(:,:,:), allocatable zh
real, dimension(:,:,:), allocatable du
real, dimension(:,:,:), allocatable dv
real, dimension(:,:,:), allocatable pkc
real, dimension(:,:,:), allocatable delpc
real, dimension(:,:,:), allocatable pk3
real, dimension(:,:,:), allocatable ptc
real, dimension(:,:,:), allocatable gz
real(kind=r_grid), parameter cnst_0p20 =0.20d0
real, dimension(:), allocatable rf
integer k_rf = 0
logical rff_initialized = .false.
logical first_call = .true.
integer kmax =1
Detailed Description
The module 'dyn_core' peforms the Lagrangian acoustic dynamics described by .
The forward timestep is handled by routines in 'sw_core.F90'. The backwards-in-time PGF is evaluated in one_grad_p or split_p_grad (hydrostatic) and nh_p_grad (nonhydrostatic) see . The nonhydrostatic components are handled by 'nh_core.F90'.
Definition at line 28 of file dyn_core.F90.
Member Function/Subroutine Documentation
subroutine dyn_core_mod::adv_pe (real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(in) ua, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(in) va, real, dimension(bd%is-1:bd%ie+1,1:npz+1,bd%js-1:bd%je+1), intent(in) pem, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(inout) om, type(fv_grid_type), intent(inout), target gridstruct, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ng) [private]
Definition at line 1553 of file dyn_core.F90.
References a2b_edge_mod::a2b_ord2().
Referenced by dyn_core().
subroutine, public dyn_core_mod::del2_cubed (real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,km), intent(inout) q, real(kind=r_grid), intent(in) cd, type(fv_grid_type), intent(in), target gridstruct, type(domain2d), intent(inout) domain, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) km, integer, intent(in) nmax, type(fv_grid_bounds_type), intent(in) bd)
The subroutine 'del2-cubed' filters the omega field for the physics.
Parameters
in cd cd = K * da_min; 0 < K < 0.25
Definition at line 2420 of file dyn_core.F90.
References tp_core_mod::copy_corners(), fv_timing_mod::timing_off(), and fv_timing_mod::timing_on().
Referenced by atmosphere_mod::atmosphere_diss_est(), dyn_core(), fv_dynamics_mod::fv_dynamics(), and fv_eta_mod::set_hybrid_z().
subroutine, public dyn_core_mod::dyn_core (integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, integer, intent(in) ng, integer, intent(in) sphum, integer, intent(in) nq, real, intent(in) bdt, integer, intent(in) n_split, real, intent(in) zvir, real, intent(in) cp, real, intent(in) akap, real, dimension(bd%isd:,bd%jsd:,1:), intent(inout) cappa)
Parameters
in,out cappa moist kappa
Definition at line 171 of file dyn_core.F90.
References a2b_edge_mod::a2b_ord2(), adv_pe(), fv_nwp_nudge_mod::breed_slp_inline(), sw_core_mod::c_sw(), test_cases_mod::case9_forcing1(), test_cases_mod::case9_forcing2(), sw_core_mod::d_sw(), del2_cubed(), fv_regional_mod::exch_uv(), geopk(), grad1_p_update(), init_ijk_mem(), mix_dp(), nh_utils_mod::nest_halo_nh(), boundary_mod::nested_grid_bc_apply_intt(), nh_p_grad(), one_grad_p(), p_grad_c(), pe_halo(), pk3_halo(), pln_halo(), fv_diagnostics_mod::prt_mxm(), ray_fast(), fv_regional_mod::regional_boundary_update(), nh_core_mod::riem_solver3(), nh_utils_mod::riem_solver_c(), split_p_grad(), fv_timing_mod::timing_off(), fv_timing_mod::timing_on(), fv_update_phys_mod::update_dwinds_phys(), nh_utils_mod::update_dz_c(), nh_utils_mod::update_dz_d(), multi_gases_mod::vicvqd(), and multi_gases_mod::virqd().
Referenced by fv_dynamics_mod::fv_dynamics().
subroutine dyn_core_mod::geopk (real, intent(in) ptop, real, dimension(bd%is-1:bd%ie+1,km+1,bd%js-1:bd%je+1), intent(out) pe, real, dimension(bd%is:bd%ie,km+1,bd%js:bd%je), intent(out) peln, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,km), intent(in) delp, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,km+1), intent(out) pk, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,km+1), intent(out) gz, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(in) hs, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,km), intent(in) pt) [private]
The subroutine 'geopk' calculates geopotential and pressure to the kappa.
Parameters
out peln ln(pe)
Definition at line 2242 of file dyn_core.F90.
Referenced by dyn_core().
subroutine dyn_core_mod::grad1_p_update (real, dimension(bd%is:bd%ie+1,bd%js:bd%je+1), intent(in) divg2, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(inout) v, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed ,npz+1), intent(inout) pk, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed ,npz+1), intent(inout) gz, real, intent(in) dt, integer, intent(in) ng, type(fv_grid_type), intent(inout), target gridstruct, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, real, intent(in) ptop, real, intent(in) beta, integer, intent(in) a2b_ord) [private]
Definition at line 2069 of file dyn_core.F90.
References a2b_edge_mod::a2b_ord2(), and a2b_edge_mod::a2b_ord4().
Referenced by dyn_core().
subroutine, public dyn_core_mod::init_ijk_mem (integer, intent(in) i1, integer, intent(in) i2, integer, intent(in) j1, integer, intent(in) j2, integer, intent(in) km, real, dimension(i1:i2,j1:j2,km), intent(inout) array, real, intent(in) var)
Definition at line 2531 of file dyn_core.F90.
Referenced by dyn_core(), and fv_dynamics_mod::fv_dynamics().
subroutine dyn_core_mod::mix_dp (logical, intent(in) hydrostatic, real, dimension(bd%isd:,bd%jsd:,1:), intent(inout) w, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,km), intent(inout) delp, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,km), intent(inout) pt, integer, intent(in) km, real, dimension(km+1), intent(in) ak, real, dimension(km+1), intent(in) bk, logical, intent(in) CG, logical, intent(in) fv_debug, type(fv_grid_bounds_type), intent(in) bd) [private]
Definition at line 2163 of file dyn_core.F90.
Referenced by dyn_core().
subroutine dyn_core_mod::nh_p_grad (real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1,npz), intent(inout) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed, npz), intent(inout) v, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz+1), intent(inout) pp, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz+1), intent(inout) gz, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz), intent(inout) delp, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz+1), intent(inout) pk, real, intent(in) dt, integer, intent(in) ng, type(fv_grid_type), intent(inout), target gridstruct, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, logical, intent(in) use_logp) [private]
Parameters
in,out pp perturbation pressure
in,out pk p**kappa
in,out gz g * h
Definition at line 1721 of file dyn_core.F90.
References a2b_edge_mod::a2b_ord4().
Referenced by dyn_core().
subroutine dyn_core_mod::one_grad_p (real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(inout) v, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed ,npz+1), intent(inout) pk, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed ,npz+1), intent(inout) gz, real, dimension(bd%is:bd%ie+1,bd%js:bd%je+1), intent(in) divg2, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed ,npz), intent(inout) delp, real, intent(in) dt, integer, intent(in) ng, type(fv_grid_type), intent(inout), target gridstruct, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, real, intent(in) ptop, logical, intent(in) hydrostatic, integer, intent(in) a2b_ord, real, intent(in) d_ext) [private]
Definition at line 1933 of file dyn_core.F90.
References a2b_edge_mod::a2b_ord2(), and a2b_edge_mod::a2b_ord4().
Referenced by dyn_core().
subroutine dyn_core_mod::p_grad_c (real, intent(in) dt2, integer, intent(in) npz, real, dimension(bd%isd:, bd%jsd: ,:), intent(in) delpc, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed ,npz+1), intent(in) pkc, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed ,npz+1), intent(in) gz, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed ,npz), intent(inout) uc, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) vc, type(fv_grid_bounds_type), intent(in) bd, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed+1), intent(in) rdxc, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed), intent(in) rdyc, logical, intent(in) hydrostatic) [private]
Parameters
in pkc pkc is pe**cappa if hydrostatic pkc is full pressure if non-hydrostatic
in gz pkc is pe**cappa if hydrostatic pkc is full pressure if non-hydrostatic
Definition at line 1659 of file dyn_core.F90.
Referenced by dyn_core().
subroutine dyn_core_mod::pe_halo (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npz, real, intent(in) ptop, real, dimension(is-1:ie+1,npz+1,js-1:je+1), intent(inout) pe, real, dimension(isd:ied,jsd:jed,npz), intent(in) delp) [private]
Definition at line 1522 of file dyn_core.F90.
Referenced by dyn_core().
subroutine dyn_core_mod::pk3_halo (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npz, real, intent(in) ptop, real, intent(in) akap, real, dimension(isd:ied,jsd:jed,npz+1), intent(inout) pk3, real, dimension(isd:ied,jsd:jed,npz), intent(in) delp) [private]
Definition at line 1419 of file dyn_core.F90.
Referenced by dyn_core().
subroutine dyn_core_mod::pln_halo (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npz, real, intent(in) ptop, real, dimension(isd:ied,jsd:jed,npz+1), intent(inout) pk3, real, dimension(isd:ied,jsd:jed,npz), intent(in) delp) [private]
Definition at line 1473 of file dyn_core.F90.
Referenced by dyn_core().
subroutine dyn_core_mod::ray_fast (real, intent(in) dt, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, real, dimension(npz), intent(in) pfull, real, intent(in) tau, real, dimension(bd%isd:bd%ied ,bd%jsd:bd%jed+1,npz), intent(inout) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed,npz), intent(inout) v, real, dimension(bd%isd: ,bd%jsd: ,1:), intent(inout) w, integer, intent(in) ks, real, dimension(npz), intent(in) dp, real, intent(in) ptop, logical, intent(in) hydrostatic, real, intent(in) rf_cutoff, type(fv_grid_bounds_type), intent(in) bd) [private]
The subroutine 'Ray_fast' computes a simple `inline` version of the Rayleigh friction (EXPERIMENTAL - NOT FOR GENERAL USE).
Parameters
in tau time scale (days)
in,out u D grid zonal wind (m/s)
in,out v D grid meridional wind (m/s)
in,out w cell center vertical wind (m/s)
Definition at line 2549 of file dyn_core.F90.
Referenced by dyn_core().
subroutine dyn_core_mod::split_p_grad (real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed+1,npz), intent(inout) u, real, dimension(bd%isd:bd%ied+1,bd%jsd:bd%jed, npz), intent(inout) v, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz+1), intent(inout) pp, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz+1), intent(inout) gz, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz), intent(inout) delp, real, dimension(bd%isd:bd%ied, bd%jsd:bd%jed, npz+1), intent(inout) pk, real, intent(in) beta, real, intent(in) dt, integer, intent(in) ng, type(fv_grid_type), intent(inout), target gridstruct, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, logical, intent(in) use_logp) [private]
Parameters
in,out pp perturbation pressure
in,out pk p**kappa
in,out gz g * h
Definition at line 1819 of file dyn_core.F90.
References a2b_edge_mod::a2b_ord4().
Referenced by dyn_core().
Member Data Documentation
real(kind=r_grid), parameter dyn_core_mod::cnst_0p20 =0.20d0 [private]
Definition at line 157 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::crx [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::cry [private]
Definition at line 153 of file dyn_core.F90.
real dyn_core_mod::d3_damp [private]
Definition at line 152 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::delpc [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::divgd [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::du [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::dv [private]
Definition at line 153 of file dyn_core.F90.
logical dyn_core_mod::first_call = .true. [private]
Definition at line 162 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::gz [private]
Definition at line 153 of file dyn_core.F90.
integer dyn_core_mod::k_rf = 0 [private]
Definition at line 160 of file dyn_core.F90.
integer dyn_core_mod::kmax =1 [private]
Definition at line 163 of file dyn_core.F90.
real dyn_core_mod::peln1 [private]
Definition at line 151 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::pk3 [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::pkc [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::ptc [private]
Definition at line 153 of file dyn_core.F90.
real dyn_core_mod::ptk [private]
Definition at line 151 of file dyn_core.F90.
real, dimension(:), allocatable dyn_core_mod::rf [private]
Definition at line 159 of file dyn_core.F90.
logical dyn_core_mod::rff_initialized = .false. [private]
Definition at line 161 of file dyn_core.F90.
real dyn_core_mod::rgrav [private]
Definition at line 151 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::ut [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::vt [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::xfx [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::yfx [private]
Definition at line 153 of file dyn_core.F90.
real, dimension(:,:,:), allocatable dyn_core_mod::zh [private]
Definition at line 153 of file dyn_core.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/dyn_core.F90