fv_update_phys_mod Module Reference
The module 'fv_update_phys' applies physics tendencies consistent with the FV3 discretization and definition of the prognostic variables.
Public Member Functions
subroutine, public fv_update_phys (dt, is, ie, js, je, isd, ied, jsd, jed, ng, nq, u, v, w, delp, pt, q, qdiag, ua, va, ps, pe, peln, pk, pkz, ak, bk, phis, u_srf, v_srf, ts, delz, hydrostatic, u_dt, v_dt, t_dt, moist_phys, Time, nudge, gridstruct, lona, lata, npx, npy, npz, flagstruct, neststruct, bd, domain, ptop, q_dt)
subroutine, public del2_phys (qdt, delp, gridstruct, cd, npx, npy, km, is, ie, js, je, isd, ied, jsd, jed, ngc, domain)
The subroutine 'del2_phys' is for filtering the physics tendency.
subroutine update_dwinds_phys (is, ie, js, je, isd, ied, jsd, jed, dt, u_dt, v_dt, u, v, gridstruct, npx, npy, npz, domain)
The subroutine 'update_dwinds_phys' transforms the wind tendencies from the A grid to the D grid for the final update.
subroutine update2d_dwinds_phys (is, ie, js, je, isd, ied, jsd, jed, dt, u_dt, v_dt, u, v, gridstruct, npx, npy, npz, domain)
The subroutine 'update2d_dwinds_phys' transforms the wind tendencies from the A grid to the D grid for the final update.
Public Attributes
real, parameter con_cp = cp_air
Detailed Description
The module 'fv_update_phys' applies physics tendencies consistent with the FV3 discretization and definition of the prognostic variables.
Definition at line 26 of file fv_update_phys.F90.
Member Function/Subroutine Documentation
subroutine, public fv_update_phys_mod::del2_phys (real, dimension(is-ngc:ie+ngc,js-ngc:je+ngc,km), intent(inout) qdt, real, dimension(isd:ied,jsd:jed,km), intent(in) delp, type(fv_grid_type), intent(in), target gridstruct, real, intent(in) cd, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) km, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) ngc, type(domain2d), intent(inout) domain)
The subroutine 'del2_phys' is for filtering the physics tendency.
Parameters
in cd cd = K * da_min; 0 < K < 0.25
Definition at line 710 of file fv_update_phys.F90.
References fv_timing_mod::timing_off(), and fv_timing_mod::timing_on().
subroutine, public fv_update_phys_mod::fv_update_phys (real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) ng, integer, intent(in) nq, real, dimension(isd:ied ,jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) v, real, dimension(isd: ,jsd: ,1:), intent(inout) w, real, dimension(isd:ied,jsd:jed,npz), intent(inout) delp, real, dimension(isd:ied,jsd:jed,npz), intent(inout) pt, real, dimension(isd:ied,jsd:jed,npz,nq), intent(inout) q, real, dimension(isd:ied,jsd:jed,npz,nq+1:flagstruct%ncnst), intent(inout) qdiag, real, dimension(isd:ied,jsd:jed,npz), intent(inout) ua, real, dimension(isd:ied,jsd:jed,npz), intent(inout) va, real, dimension (isd:ied ,jsd:jed), intent(inout) ps, real, dimension (is-1:ie+1, npz+1,js-1:je+1), intent(inout) pe, real, dimension(is:ie,npz+1,js:je), intent(inout) peln, real, dimension (is:ie,js:je , npz+1), intent(inout) pk, real, dimension (is:ie,js:je,npz), intent(inout) pkz, real, dimension(npz+1), intent(in) ak, real, dimension(npz+1), intent(in) bk, real, dimension(isd:ied,jsd:jed), intent(in) phis, real, dimension(is:ie,js:je), intent(out) u_srf, real, dimension(is:ie,js:je), intent(out) v_srf, real, dimension(is:ie,js:je), intent(out) ts, real, dimension(isd:,jsd:,1:), intent(inout) delz, logical, intent(in) hydrostatic, real, dimension(isd:ied,jsd:jed,npz), intent(inout) u_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) v_dt, real, dimension(is:ie,js:je,npz), intent(inout) t_dt, logical, intent(in) moist_phys, type (time_type), intent(in) Time, logical, intent(in) nudge, type(fv_grid_type) gridstruct, real, dimension(isd:ied,jsd:jed), intent(in), optional lona, real, dimension(isd:ied,jsd:jed), intent(in), optional lata, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, type(fv_flags_type) flagstruct, type(fv_nest_type) neststruct, type(fv_grid_bounds_type), intent(in) bd, type(domain2d), intent(inout) domain, real, intent(in) ptop, real, dimension(is:ie,js:je,npz,nq), intent(inout), optional q_dt)
Parameters
in lata A-grid (physics) lon and lat
in,out u D grid zonal wind (m/s)
in,out v D grid meridional wind (m/s)
in,out q specific humidity and constituents
in,out qdiag diagnostic tracers
in,out ps Surface pressure (pascal)
in,out pe edge pressure (pascal)
in,out pk pe**cappa
in,out peln ln(pe)
in,out pkz finite-volume mean pk
Definition at line 135 of file fv_update_phys.F90.
References fv_grid_utils_mod::cubed_to_latlon(), fv_nwp_nudge_mod::fv_nwp_nudge(), fv_eta_mod::get_eta_level(), fv_mapz_mod::moist_cp(), fv_mapz_mod::moist_cv(), fv_diagnostics_mod::prt_maxmin(), fv_timing_mod::timing_off(), fv_timing_mod::timing_on(), update2d_dwinds_phys(), update_dwinds_phys(), multi_gases_mod::vicpqd(), and multi_gases_mod::virqd().
Referenced by atmosphere_mod::atmosphere_state_update().
subroutine fv_update_phys_mod::update2d_dwinds_phys (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, intent(in) dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) u_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) v_dt, real, dimension(isd:ied, jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) v, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, type(domain2d), intent(inout) domain)
The subroutine 'update2d_dwinds_phys' transforms the wind tendencies from the A grid to the D grid for the final update.
Definition at line 1002 of file fv_update_phys.F90.
References fv_timing_mod::timing_off(), and fv_timing_mod::timing_on().
Referenced by fv_update_phys().
subroutine fv_update_phys_mod::update_dwinds_phys (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, intent(in) dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) u_dt, real, dimension(isd:ied,jsd:jed,npz), intent(inout) v_dt, real, dimension(isd:ied, jsd:jed+1,npz), intent(inout) u, real, dimension(isd:ied+1,jsd:jed ,npz), intent(inout) v, type(fv_grid_type), intent(in), target gridstruct, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npz, type(domain2d), intent(inout) domain)
The subroutine 'update_dwinds_phys' transforms the wind tendencies from the A grid to the D grid for the final update.
Definition at line 814 of file fv_update_phys.F90.
Referenced by dyn_core_mod::dyn_core(), and fv_update_phys().
Member Data Documentation
real, parameter fv_update_phys_mod::con_cp = cp_air
Definition at line 131 of file fv_update_phys.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_update_phys.F90