fv_restart_mod Module Reference
Public Member Functions
subroutine, public fv_restart_init ()
subroutine, public fv_restart (fv_domain, Atm, dt_atmos, seconds, days, cold_start, grid_type, grids_on_this_pe)
The subroutine 'fv_restart' initializes the model state, including prognaostic variables and several auxiliary pressure variables.
subroutine, public setup_nested_boundary_halo (Atm, proc_in)
subroutine, public fv_write_restart (Atm, grids_on_this_pe, timestamp)
The subroutine 'fv_write_restart' writes restart files to disk.
subroutine, public fv_restart_end (Atm, grids_on_this_pe, restart_endfcst)
The subroutine 'fv_restart_end' writes ending restart files, terminates I/O, and prints out diagnostics including global totals and checksums.
subroutine, public d2c_setup (u, v, ua, va, uc, vc, dord4, isd, ied, jsd, jed, is, ie, js, je, npx, npy, grid_type, nested, se_corner, sw_corner, ne_corner, nw_corner, rsin_u, rsin_v, cosa_s, rsin2, regional)
subroutine, public d2a_setup (u, v, ua, va, dord4, isd, ied, jsd, jed, is, ie, js, je, npx, npy, grid_type, nested, cosa_s, rsin2, regional)
Private Member Functions
subroutine fill_nested_grid_topo_halo (Atm, proc_in)
subroutine fill_nested_grid_topo (Atm, proc_in)
The subroutine 'fill_nested_grid_topo' fills the nested grid with topo to enable boundary smoothing.
subroutine fill_nested_grid_data (Atm, proc_in)
subroutine fill_nested_grid_data_end (Atm, proc_in)
The subroutine ' fill_nested_grid_data_end' actually sets up the coarse-grid TOPOGRAPHY.
subroutine pmaxmn_g (qname, q, is, ie, js, je, km, fac, area, domain)
The subroutine 'pmaxn_g' writes domain max, min, and averages quantities.
Private Attributes
real(kind=r_grid), parameter cnst_0p20 =0.20d0
logical module_is_initialized = .FALSE.
Detailed Description
Definition at line 22 of file fv_restart.F90.
Member Function/Subroutine Documentation
subroutine, public fv_restart_mod::d2a_setup (real, dimension(isd:ied,jsd:jed+1), intent(in) u, real, dimension(isd:ied+1,jsd:jed), intent(in) v, real, dimension(isd:ied ,jsd:jed), intent(out) ua, real, dimension(isd:ied ,jsd:jed), intent(out) va, logical, intent(in) dord4, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) grid_type, logical, intent(in) nested, real, dimension(isd:ied,jsd:jed), intent(in) cosa_s, real, dimension(isd:ied,jsd:jed), intent(in) rsin2, logical, intent(in) regional)
Definition at line 1826 of file fv_restart.F90.
subroutine, public fv_restart_mod::d2c_setup (real, dimension(isd:ied,jsd:jed+1), intent(in) u, real, dimension(isd:ied+1,jsd:jed), intent(in) v, real, dimension(isd:ied ,jsd:jed), intent(out) ua, real, dimension(isd:ied ,jsd:jed), intent(out) va, real, dimension(isd:ied+1,jsd:jed), intent(out) uc, real, dimension(isd:ied ,jsd:jed+1), intent(out) vc, logical, intent(in) dord4, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) grid_type, logical, intent(in) nested, logical, intent(in) se_corner, logical, intent(in) sw_corner, logical, intent(in) ne_corner, logical, intent(in) nw_corner, real, dimension(isd:ied+1,jsd:jed), intent(in) rsin_u, real, dimension(isd:ied,jsd:jed+1), intent(in) rsin_v, real, dimension(isd:ied,jsd:jed), intent(in) cosa_s, real, dimension(isd:ied,jsd:jed), intent(in) rsin2, logical, intent(in) regional)
Definition at line 1548 of file fv_restart.F90.
Referenced by fv_nesting_mod::setup_nested_grid_bcs().
subroutine fv_restart_mod::fill_nested_grid_data (type(fv_atmos_type), dimension(:), intent(inout) Atm, logical, intent(in), optional proc_in) [private]
Definition at line 944 of file fv_restart.F90.
References fv_timing_mod::timing_off(), fv_timing_mod::timing_on(), and multi_gases_mod::virq().
Referenced by fv_restart().
subroutine fv_restart_mod::fill_nested_grid_data_end (type(fv_atmos_type), intent(inout) Atm, logical, intent(in), optional proc_in) [private]
The subroutine ' fill_nested_grid_data_end' actually sets up the coarse-grid TOPOGRAPHY.
Definition at line 1322 of file fv_restart.F90.
References init_hydro_mod::p_var().
Referenced by fv_restart().
subroutine fv_restart_mod::fill_nested_grid_topo (type(fv_atmos_type), intent(inout) Atm, logical, intent(in), optional proc_in) [private]
The subroutine 'fill_nested_grid_topo' fills the nested grid with topo to enable boundary smoothing.
Interior topography is then over-written in get_external_ic.
Definition at line 884 of file fv_restart.F90.
References fv_timing_mod::timing_off(), and fv_timing_mod::timing_on().
Referenced by fv_restart().
subroutine fv_restart_mod::fill_nested_grid_topo_halo (type(fv_atmos_type), intent(inout) Atm, logical, intent(in), optional proc_in) [private]
Definition at line 863 of file fv_restart.F90.
Referenced by fv_restart().
subroutine, public fv_restart_mod::fv_restart (type(domain2d), intent(inout) fv_domain, type(fv_atmos_type), dimension(:), intent(inout) Atm, real, intent(in) dt_atmos, integer, intent(out) seconds, integer, intent(out) days, logical, intent(inout) cold_start, integer, intent(in) grid_type, logical, dimension(:), intent(inout) grids_on_this_pe)
The subroutine 'fv_restart' initializes the model state, including prognaostic variables and several auxiliary pressure variables.
The modules also writes out restart files at the end of the model run, and prints out diagnostics of the initial state. There are several options to control the initialization process.
Definition at line 195 of file fv_restart.F90.
References fv_eta_mod::compute_dz_l32(), fv_eta_mod::compute_dz_var(), fv_grid_utils_mod::cubed_to_latlon(), fv_surf_map_mod::del2_cubed_sphere(), fv_surf_map_mod::del4_cubed_sphere(), fill_nested_grid_data(), fill_nested_grid_data_end(), fill_nested_grid_topo(), fill_nested_grid_topo_halo(), fv_io_mod::fv_io_read_bcs(), fv_io_mod::fv_io_read_restart(), fv_io_mod::fv_io_register_restart(), fv_io_mod::fv_io_register_restart_bcs(), fv_io_mod::fv_io_register_restart_bcs_nh(), external_ic_mod::get_external_ic(), test_cases_mod::init_case(), test_cases_mod::init_double_periodic(), test_cases_mod::init_latlon(), init_hydro_mod::p_var(), pmaxmn_g(), fv_diagnostics_mod::prt_maxmin(), fv_treat_da_inc_mod::read_da_inc(), fv_io_mod::remap_restart(), fv_eta_mod::set_hybrid_z(), and setup_nested_boundary_halo().
Referenced by atmosphere_mod::atmosphere_init().
subroutine, public fv_restart_mod::fv_restart_end (type(fv_atmos_type), dimension(:), intent(inout) Atm, logical, dimension(:), intent(inout) grids_on_this_pe, logical, intent(in) restart_endfcst)
The subroutine 'fv_restart_end' writes ending restart files, terminates I/O, and prints out diagnostics including global totals and checksums.
Definition at line 1437 of file fv_restart.F90.
References fv_io_mod::fv_io_write_bcs(), fv_io_mod::fv_io_write_restart(), pmaxmn_g(), and fv_diagnostics_mod::prt_maxmin().
Referenced by fv_control_mod::fv_end().
subroutine, public fv_restart_mod::fv_restart_init ()
Definition at line 185 of file fv_restart.F90.
References fv_io_mod::fv_io_init().
Referenced by fv_control_mod::fv_init().
subroutine, public fv_restart_mod::fv_write_restart (type(fv_atmos_type), dimension(:), intent(inout) Atm, logical, dimension(:), intent(in) grids_on_this_pe, character(len=*), intent(in) timestamp)
The subroutine 'fv_write_restart' writes restart files to disk.
This subroutine may be called during an integration to write out intermediate restart files.
Definition at line 1419 of file fv_restart.F90.
References fv_io_mod::fv_io_write_bcs(), and fv_io_mod::fv_io_write_restart().
Referenced by atmosphere_mod::atmosphere_restart().
subroutine fv_restart_mod::pmaxmn_g (character(len=*), intent(in) qname, real, dimension(is-3:ie+3, js-3:je+3, km), intent(in) q, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, real, intent(in) fac, real(kind=r_grid), dimension(is-3:ie+3, js-3:je+3), intent(in) area, type(domain2d), intent(inout) domain) [private]
The subroutine 'pmaxn_g' writes domain max, min, and averages quantities.
Definition at line 1962 of file fv_restart.F90.
References fv_grid_utils_mod::g_sum().
Referenced by fv_restart(), and fv_restart_end().
subroutine, public fv_restart_mod::setup_nested_boundary_halo (type(fv_atmos_type), intent(inout) Atm, logical, intent(in), optional proc_in)
Definition at line 715 of file fv_restart.F90.
Referenced by fv_restart().
Member Data Documentation
real(kind=r_grid), parameter fv_restart_mod::cnst_0p20 =0.20d0 [private]
Definition at line 178 of file fv_restart.F90.
logical fv_restart_mod::module_is_initialized = .FALSE. [private]
Definition at line 180 of file fv_restart.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_restart.F90