nh_utils_mod Module Reference
The module 'nh_utils' peforms non-hydrostatic computations.
Public Member Functions
subroutine, public update_dz_c (is, ie, js, je, km, ng, dt, dp0, zs, area, ut, vt, gz, ws, npx, npy, sw_corner, se_corner, ne_corner, nw_corner, bd, grid_type)
subroutine, public update_dz_d (ndif, damp, hord, is, ie, js, je, km, ng, npx, npy, area, rarea, dp0, zs, zh, crx, cry, xfx, yfx, delz, ws, rdt, gridstruct, bd, lim_fac, regional)
subroutine, public riem_solver_c (ms,dt,is,ie,js, je, km,ng,akap, cappa, cp,
subroutine, public rim_2d (ms, bdt, is, ie, km, rgas, gama, gm2,
subroutine, public sim3_solver (dt,is,ie, km, rgas, gama, kappa,
subroutine, public sim3p0_solver (dt,is,ie, km, rgas, gama, kappa,
subroutine, public sim1_solver (dt,is,ie, km, rgas, gama, gm2, cp2, kappa,
subroutine, public sim_solver (dt,is,ie, km, rgas, gama, gm2, cp2, kappa,
subroutine, public nest_halo_nh (ptop, grav, kappa, cp, delp, delz, pt, phis,
Private Member Functions
subroutine riem_solver3test (ms, dt,is,ie,js, je, km, ng,isd, ied, jsd, jed, akap, cappa, cp,
GFDL - This routine will not give absoulte reproducibility when compiled with -fast-transcendentals. GFDL - It is now inside of nh_core.F90 and being compiled without -fast-transcendentals.
subroutine imp_diff_w (j, is, ie, js, je, ng, km, cd, delz, ws, w, w3)
subroutine edge_scalar (q1, qe, i1, i2, km, id)
subroutine edge_profile (q1, q2, q1e, q2e, i1, i2, j1, j2, j, km, dp0, uniform_grid, limiter)
Private Attributes
real, parameter dz_min = 2.
real, parameter r3 = 1./3.
Detailed Description
The module 'nh_utils' peforms non-hydrostatic computations.
Author
S. J. Lin, NOAA/GFDL
Definition at line 26 of file nh_utils.F90.
Member Function/Subroutine Documentation
subroutine nh_utils_mod::edge_profile (real, dimension(i1:i2,j1:j2,km), intent(in) q1, real, dimension(i1:i2,j1:j2,km), intent(in) q2, real, dimension(i1:i2,j1:j2,km+1), intent(out) q1e, real, dimension(i1:i2,j1:j2,km+1), intent(out) q2e, integer, intent(in) i1, integer, intent(in) i2, integer, intent(in) j1, integer, intent(in) j2, integer, intent(in) j, integer, intent(in) km, real, dimension(km), intent(in) dp0, logical, intent(in) uniform_grid, integer, intent(in) limiter) [private]
Definition at line 1790 of file nh_utils.F90.
Referenced by update_dz_d().
subroutine nh_utils_mod::edge_scalar (real, dimension(i1:i2,km), intent(in) q1, real, dimension(i1:i2,km+1), intent(out) qe, integer, intent(in) i1, integer, intent(in) i2, integer, intent(in) km, integer, intent(in) id) [private]
Definition at line 1740 of file nh_utils.F90.
subroutine nh_utils_mod::imp_diff_w (integer, intent(in) j, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ng, integer, intent(in) km, real, intent(in) cd, real, dimension(is-ng:ie+ng, km), intent(in) delz, real, dimension(is:ie), intent(in) ws, real, dimension(is:ie, km), intent(in) w, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(out) w3) [private]
Parameters
in delz delta-height (m)
in w vertical vel. (m/s)
Definition at line 679 of file nh_utils.F90.
subroutine, public nh_utils_mod::nest_halo_nh (real, intent(in) ptop, real, intent(in) grav, real, intent(in) kappa, real, intent(in) cp, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(in) delp, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(in) delz, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed,npz), intent(in) pt, real, dimension(bd%isd:bd%ied,bd%jsd:bd%jed), intent(in) phis)
Definition at line 1898 of file nh_utils.F90.
References multi_gases_mod::vicpqd(), and multi_gases_mod::vicvqd().
Referenced by dyn_core_mod::dyn_core().
subroutine nh_utils_mod::riem_solver3test (integer, intent(in) ms, real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, integer, intent(in) ng, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, real, intent(in) akap, real, dimension(isd:,jsd:,1:), intent(in) cappa, real, intent(in) cp) [private]
GFDL - This routine will not give absoulte reproducibility when compiled with -fast-transcendentals. GFDL - It is now inside of nh_core.F90 and being compiled without -fast-transcendentals.
Definition at line 474 of file nh_utils.F90.
References rim_2d(), sim1_solver(), sim3_solver(), sim3p0_solver(), and sim_solver().
subroutine, public nh_utils_mod::riem_solver_c (integer, intent(in) ms, real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, integer, intent(in) ng, real, intent(in) akap, real, dimension(is-ng:,js-ng:,1:), intent(in) cappa, real, intent(in) cp)
Definition at line 331 of file nh_utils.F90.
References rim_2d(), sim1_solver(), and sim3p0_solver().
Referenced by dyn_core_mod::dyn_core().
subroutine, public nh_utils_mod::rim_2d (integer, intent(in) ms, real, intent(in) bdt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) km, real, intent(in) rgas, real, intent(in) gama, real, dimension(is:ie,km), intent(in) gm2)
Definition at line 742 of file nh_utils.F90.
Referenced by nh_core_mod::riem_solver3(), riem_solver3test(), and riem_solver_c().
subroutine, public nh_utils_mod::sim1_solver (real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) km, real, intent(in) rgas, real, intent(in) gama, real, dimension(is:ie,km), intent(in) gm2, real, dimension(is:ie,km), intent(in) cp2, real, intent(in) kappa)
Definition at line 1373 of file nh_utils.F90.
Referenced by nh_core_mod::riem_solver3(), riem_solver3test(), and riem_solver_c().
subroutine, public nh_utils_mod::sim3_solver (real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) km, real, intent(in) rgas, real, intent(in) gama, real, intent(in) kappa)
Definition at line 1006 of file nh_utils.F90.
Referenced by nh_core_mod::riem_solver3(), and riem_solver3test().
subroutine, public nh_utils_mod::sim3p0_solver (real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) km, real, intent(in) rgas, real, intent(in) gama, real, intent(in) kappa)
Definition at line 1193 of file nh_utils.F90.
Referenced by nh_core_mod::riem_solver3(), riem_solver3test(), and riem_solver_c().
subroutine, public nh_utils_mod::sim_solver (real, intent(in) dt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) km, real, intent(in) rgas, real, intent(in) gama, real, dimension(is:ie,km), intent(in) gm2, real, dimension(is:ie,km), intent(in) cp2, real, intent(in) kappa)
Definition at line 1544 of file nh_utils.F90.
Referenced by nh_core_mod::riem_solver3(), and riem_solver3test().
subroutine, public nh_utils_mod::update_dz_c (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, integer, intent(in) ng, real, intent(in) dt, real, dimension(km), intent(in) dp0, real, dimension(is-ng:ie+ng, js-ng:je+ng), intent(in) zs, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(in) area, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(in) ut, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(in) vt, real, dimension(is-ng:ie+ng,js-ng:je+ng,km+1), intent(inout) gz, real, dimension(is-ng:ie+ng, js-ng:je+ng), intent(out) ws, integer, intent(in) npx, integer, intent(in) npy, logical, intent(in) sw_corner, logical, intent(in) se_corner, logical, intent(in) ne_corner, logical, intent(in) nw_corner, type(fv_grid_bounds_type), intent(in) bd, integer, intent(in) grid_type)
Definition at line 74 of file nh_utils.F90.
References sw_core_mod::fill_4corners().
Referenced by dyn_core_mod::dyn_core().
subroutine, public nh_utils_mod::update_dz_d (integer, dimension(km+1), intent(inout) ndif, real, dimension(km+1), intent(inout) damp, integer, intent(in) hord, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) km, integer, intent(in) ng, integer, intent(in) npx, integer, intent(in) npy, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(in) area, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(in) rarea, real, dimension(km), intent(in) dp0, real, dimension(is-ng:ie+ng,js-ng:je+ng), intent(in) zs, real, dimension(is-ng:ie+ng,js-ng:je+ng,km+1), intent(inout) zh, real, dimension(is:ie+1,js-ng:je+ng,km), intent(inout) crx, real, dimension(is-ng:ie+ng,js:je+1,km), intent(inout) cry, real, dimension(is:ie+1,js-ng:je+ng,km), intent(inout) xfx, real, dimension(is-ng:ie+ng,js:je+1,km), intent(inout) yfx, real, dimension(is-ng:ie+ng,js-ng:je+ng,km), intent(out) delz, real, dimension(is:ie,js:je), intent(out) ws, real, intent(in) rdt, type(fv_grid_type), intent(in), target gridstruct, type(fv_grid_bounds_type), intent(in) bd, real, intent(in) lim_fac, logical, intent(in) regional)
Definition at line 214 of file nh_utils.F90.
References sw_core_mod::del6_vt_flux(), edge_profile(), and tp_core_mod::fv_tp_2d().
Referenced by dyn_core_mod::dyn_core().
Member Data Documentation
real, parameter nh_utils_mod::dz_min = 2. [private]
Definition at line 69 of file nh_utils.F90.
real, parameter nh_utils_mod::r3 = 1./3. [private]
Definition at line 70 of file nh_utils.F90.
The documentation for this module was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/nh_utils.F90