/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_treat_da_inc.F90 File Reference
Data Types
module fv_treat_da_inc_mod
'The module 'tread_da_increment' contains routines for treating the increments of the prognostic variables that are calculated by the DA process
Macros
#define _GET_VAR1 get_var1_double
Functions/Subroutines
subroutine apply_inc_on_3d_scalar (field_name, var)
The subroutine 'apply_inc_on3d_scalar' applies the input increments to the prognostic variables.
Macro Definition Documentation
#define _GET_VAR1 get_var1_double
Function/Subroutine Documentation
subroutine read_da_inc::apply_inc_on_3d_scalar (character(len=*), intent(in) field_name, real, dimension(isd:ied,jsd:jed,1:km), intent(inout) var) [private]
The subroutine 'apply_inc_on3d_scalar' applies the input increments to the prognostic variables.
Definition at line 430 of file fv_treat_da_inc.F90.
References sim_nc_mod::check_var_exists(), and sim_nc_mod::get_var3_r4().
Referenced by fv_treat_da_inc_mod::read_da_inc().