/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_regional_bc.F90 File Reference
Data Types
module fv_regional_mod
type fv_regional_mod::fv_regional_bc_variables
type fv_regional_mod::fv_domain_sides
interface fv_regional_mod::dump_field
Functions/Subroutines
subroutine compute_regional_bc_indices (regional_bc_bounds)
subroutine read_regional_lon_lat
subroutine read_regional_filtered_topo
subroutine fill_divgd_bc
subroutine bc_values_into_arrays (side_t0, side_t1, side, i1, i2, j1, j2, i1_uvs, i2_uvs, j1_uvs, j2_uvs, i1_uvw, i2_uvw, j1_uvw, j2_uvw)
subroutine compute_vpt
subroutine get_q00
Function/Subroutine Documentation
subroutine set_regional_bcs::bc_values_into_arrays (type(fv_regional_bc_variables), intent(in) side_t0, type(fv_regional_bc_variables), intent(in) side_t1, character(len=*), intent(in) side, integer, intent(in) i1, integer, intent(in) i2, integer, intent(in) j1, integer, intent(in) j2, integer, intent(in) i1_uvs, integer, intent(in) i2_uvs, integer, intent(in) j1_uvs, integer, intent(in) j2_uvs, integer, intent(in) i1_uvw, integer, intent(in) i2_uvw, integer, intent(in) j1_uvw, integer, intent(in) j2_uvw) [private]
Definition at line 3381 of file fv_regional_bc.F90.
Referenced by fv_regional_mod::set_regional_bcs().
subroutine setup_regional_bc::compute_regional_bc_indices (type(fv_regional_bc_bounds_type), intent(out) regional_bc_bounds)
Definition at line 616 of file fv_regional_bc.F90.
Referenced by fv_regional_mod::setup_regional_bc().
subroutine convert_to_virt_pot_temp::compute_vpt () [private]
Definition at line 4391 of file fv_regional_bc.F90.
Referenced by fv_regional_mod::convert_to_virt_pot_temp().
subroutine regional_bc_data::fill_divgd_bc () [private]
Definition at line 1984 of file fv_regional_bc.F90.
Referenced by fv_regional_mod::regional_bc_data().
subroutine nudge_qv_bc::get_q00 () [private]
Definition at line 4745 of file fv_regional_bc.F90.
Referenced by fv_regional_mod::nudge_qv_bc().
subroutine setup_regional_bc::read_regional_filtered_topo ()
Definition at line 992 of file fv_regional_bc.F90.
References fv_regional_mod::check().
Referenced by fv_regional_mod::setup_regional_bc().
subroutine setup_regional_bc::read_regional_lon_lat () [private]
Definition at line 892 of file fv_regional_bc.F90.
References fv_grid_utils_mod::cell_center2(), and fv_regional_mod::check().
Referenced by fv_regional_mod::setup_regional_bc().