/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/model/fv_grid_utils.F90 File Reference
#include <fms_platform.h>
*
Data Types
module fv_grid_utils_mod
The module 'fv_grid_utils' contains routines for setting up and computing grid-related quantities.
interface fv_grid_utils_mod::fill_ghost
Functions/Subroutines
subroutine get_nearest ()
subroutine check_local (x1, x2, local)
Function/Subroutine Documentation
subroutine check_local (real(kind=r_grid), dimension(3), intent(in) x1, real(kind=r_grid), dimension(3), intent(in) x2, logical, intent(out) local) [private]
Definition at line 2132 of file fv_grid_utils.F90.
Referenced by fv_grid_utils_mod::intersect(), and fv_grid_utils_mod::intersect_cross().
subroutine get_nearest () [private]
Definition at line 2118 of file fv_grid_utils.F90.
Referenced by fv_grid_utils_mod::intersect(), and fv_grid_utils_mod::intersect_cross().