/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/fv_grid_tools.F90 File Reference
#include <netcdf.inc>
*
Data Types
module fv_grid_tools_mod
Functions/Subroutines
subroutine setup_cartesian (npx, npy, dx_const, dy_const, deglat, bd)
subroutine setup_aligned_nest (Atm)
subroutine setup_latlon (deglon_start, deglon_stop, deglat_start, deglat_stop, bd)
Function/Subroutine Documentation
subroutine init_grid::setup_aligned_nest (type(fv_atmos_type), intent(inout), target Atm) [private]
Definition at line 1273 of file fv_grid_tools.F90.
References fv_grid_utils_mod::cell_center2(), fv_grid_utils_mod::dist2side_latlon(), fv_grid_utils_mod::great_circle_dist(), fv_grid_utils_mod::mid_pt_sphere(), and fv_grid_utils_mod::spherical_linear_interpolation().
Referenced by fv_grid_tools_mod::init_grid().
subroutine init_grid::setup_cartesian (integer, intent(in) npx, integer, intent(in) npy, real(kind=r_grid), intent(in) dx_const, real(kind=r_grid), intent(in) dy_const, real(kind=r_grid), intent(in) deglat, type(fv_grid_bounds_type), intent(in) bd) [private]
Definition at line 1205 of file fv_grid_tools.F90.
Referenced by fv_grid_tools_mod::init_grid().
subroutine init_grid::setup_latlon (real(kind=r_grid), intent(in) deglon_start, real(kind=r_grid), intent(in) deglon_stop, real(kind=r_grid), intent(in) deglat_start, real(kind=r_grid), intent(in) deglat_stop, type(fv_grid_bounds_type), intent(in) bd) [private]
Definition at line 1800 of file fv_grid_tools.F90.