/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/sorted_index.F90 File Reference
Data Types
module sorted_index_mod
The module 'sorted_index' sorts cell corner indices in lat-lon space to ensure the same order of operations regardless of the orientation in index space.
Functions/Subroutines
subroutine sort_rectangle (iind, jind)
subroutine sort_triangle ()
Function/Subroutine Documentation
subroutine sort_rectangle (integer, dimension(4), intent(inout) iind, integer, dimension(4), intent(inout) jind) [private]
Definition at line 90 of file sorted_index.F90.
Referenced by sorted_index_mod::sorted_inta(), and sorted_index_mod::sorted_intb().
subroutine sorted_intb::sort_triangle () [private]
Definition at line 453 of file sorted_index.F90.
Referenced by sorted_index_mod::sorted_intb().