dycore_typedefs::dycore_diag_type Type Reference
Public Member Functions
procedure create => diag_create
procedure zero => diag_zero
Public Attributes
character(len=32) name
variable name in source
character(len=32) output_name
output name for variable
character(len=32) mod_name
module name (e.g. physics, radiation, etc)
character(len=32) file_name
output file name for variable
character(len=128) desc
long description of field
character(len=32) unit
units associated with fields
character(len=32) type_stat_proc
type of statistic processing: average, accumulation, maximal,
character(len=32) level_type
vertical level of the field
integer level
vertical level(s)
real(kind=r8_kind) cnvfac
conversion factors to output in specified units
real(kind=r8_kind) zhour
forecast hour when bucket was last emptied for statistical processing
real(kind=r8_kind) fcst_hour
current forecast hour (same as fhour)
type(var_subtype), dimension(:),
*
allocatable data
holds pointers to data in packed format (allocated to nblks)
Detailed Description
Definition at line 69 of file DYCORE_typedefs.F90.
Member Function/Subroutine Documentation
procedure dycore_typedefs::dycore_diag_type::create ()
Definition at line 86 of file DYCORE_typedefs.F90.
References dycore_typedefs::dycore_coupling_type::create(), and dycore_typedefs::diag_create().
procedure dycore_typedefs::dycore_diag_type::zero ()
Definition at line 87 of file DYCORE_typedefs.F90.
References dycore_typedefs::diag_zero().
Member Data Documentation
real(kind=r8_kind) dycore_typedefs::dycore_diag_type::cnvfac
conversion factors to output in specified units
Definition at line 81 of file DYCORE_typedefs.F90.
type(var_subtype), dimension(:), allocatable dycore_typedefs::dycore_diag_type::data
holds pointers to data in packed format (allocated to nblks)
Definition at line 84 of file DYCORE_typedefs.F90.
character(len=128) dycore_typedefs::dycore_diag_type::desc
long description of field
Definition at line 74 of file DYCORE_typedefs.F90.
real(kind=r8_kind) dycore_typedefs::dycore_diag_type::fcst_hour
current forecast hour (same as fhour)
Definition at line 83 of file DYCORE_typedefs.F90.
character(len=32) dycore_typedefs::dycore_diag_type::file_name
output file name for variable
Definition at line 73 of file DYCORE_typedefs.F90.
integer dycore_typedefs::dycore_diag_type::level
vertical level(s)
Definition at line 80 of file DYCORE_typedefs.F90.
character(len=32) dycore_typedefs::dycore_diag_type::level_type
vertical level of the field
Definition at line 79 of file DYCORE_typedefs.F90.
character(len=32) dycore_typedefs::dycore_diag_type::mod_name
module name (e.g. physics, radiation, etc)
Definition at line 72 of file DYCORE_typedefs.F90.
character(len=32) dycore_typedefs::dycore_diag_type::name
variable name in source
Definition at line 70 of file DYCORE_typedefs.F90.
character(len=32) dycore_typedefs::dycore_diag_type::output_name
output name for variable
Definition at line 71 of file DYCORE_typedefs.F90.
character(len=32) dycore_typedefs::dycore_diag_type::type_stat_proc
type of statistic processing: average, accumulation, maximal,
Definition at line 76 of file DYCORE_typedefs.F90.
character(len=32) dycore_typedefs::dycore_diag_type::unit
units associated with fields
Definition at line 75 of file DYCORE_typedefs.F90.
real(kind=r8_kind) dycore_typedefs::dycore_diag_type::zhour
forecast hour when bucket was last emptied for statistical processing
Definition at line 82 of file DYCORE_typedefs.F90.
The documentation for this type was generated from the following file:
/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/driver/fvGFS/DYCORE_typedefs.F90