/scratch2/NAGAPE/aoml-hafs1/Kyle.Ahern/acs_master_readonly/tools/test_cases.F90 File Reference
Data Types
module test_cases_mod
my dog typed this comment: mjkkicdsddsds, my cat typed this comment: cdjkkjfdjkjf my dog also typed this comment: kmasdlckmc my cat meowed
interface test_cases_mod::mp_update_dwinds
Functions/Subroutines
real function dcmip16_bc_temperature (z, lat)
real function dcmip16_bc_pressure (z, lat)
real function dcmip16_bc_uwind (z, T, lat)
real function dcmip16_bc_uwind_pert (z, lat, lon)
real function dcmip16_bc_sphum (p, ps, lat, lon)
real function dcmip16_tc_temperature (z, r)
real function dcmip16_tc_pressure (z, r)
subroutine dcmip16_tc_uwind_pert (z, r, lon, lat, uu, vv)
real function dcmip16_tc_sphum (z)
Function/Subroutine Documentation
real function dcmip16_bc::dcmip16_bc_pressure (real, intent(in) z, real(kind=r_grid), intent(in) lat) [private]
Definition at line 7425 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_bc().
real function dcmip16_bc::dcmip16_bc_sphum (real, intent(in) p, real, intent(in) ps, real(kind=r_grid), intent(in) lat, real(kind=r_grid), intent(in) lon) [private]
Definition at line 7474 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_bc().
real function dcmip16_bc::dcmip16_bc_temperature (real, intent(in) z, real(kind=r_grid), intent(in) lat) [private]
Definition at line 7408 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_bc().
real function dcmip16_bc::dcmip16_bc_uwind (real, intent(in) z, real, intent(in) T, real(kind=r_grid), intent(in) lat) [private]
Definition at line 7441 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_bc().
real function dcmip16_bc::dcmip16_bc_uwind_pert (real, intent(in) z, real(kind=r_grid), intent(in) lat, real(kind=r_grid), intent(in) lon) [private]
Definition at line 7457 of file test_cases.F90.
References fv_grid_utils_mod::great_circle_dist().
Referenced by test_cases_mod::dcmip16_bc().
real function dcmip16_tc::dcmip16_tc_pressure (real, intent(in) z, real, intent(in) r) [private]
Definition at line 7785 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_tc().
real function dcmip16_tc::dcmip16_tc_sphum (real, intent(in) z) [private]
Definition at line 7829 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_tc().
real function dcmip16_tc::dcmip16_tc_temperature (real, intent(in) z, real, intent(in) r) [private]
Definition at line 7767 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_tc().
subroutine dcmip16_tc::dcmip16_tc_uwind_pert (real, intent(in) z, real, intent(in) r, real(kind=r_grid), intent(in) lon, real(kind=r_grid), intent(in) lat, real, intent(out) uu, real, intent(out) vv) [private]
Definition at line 7798 of file test_cases.F90.
Referenced by test_cases_mod::dcmip16_tc().